<div class="box panel panel-default" id="module_cart">
    <div class="panel-heading"><?php echo $heading_title; ?></div>
    <div class="panel-body panel-content">
        <div class="cart-module">
            <?php if ($products || $vouchers) { ?>
                <table class="cart table table-responsive table-bordered table-condensed">
                    <?php foreach ($products as $product) : ?>
                     
                        <tr>
                            <td class="name" colspan="2"><?php echo $product['quantity']; ?>&nbsp;x <a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a>
                                <div class="clearfix">

                                    - <small><?php echo $product['option']['title']; ?></small><br />
                                     - <small><?php echo $product['price']; ?> each</small><br />
                                    <a href="<?php echo $product['remove']; ?>" class="btn btn-xs btn-danger pull-right" alt="<?php echo $button_remove; ?>" title="<?php echo $button_remove; ?>" ><?php echo $button_remove; ?></a>
                                </div></td>
                        </tr>
                    <?php endforeach; ?>
                        <?php foreach ($vouchers as $voucher) { ?>
                        <tr>
                            <td class="name">1 x <?php echo $voucher['description']; ?>
                                <div class="clearfix">
                                    - <small><?php echo $voucher['amount']; ?></small><br />
                                    <a href="<?php echo $voucher['remove']; ?>" class="btn btn-xs btn-danger pull-right" alt="<?php echo $button_remove; ?>" title="<?php echo $button_remove; ?>" ><?php echo $button_remove; ?></a>
                                </div>
                            </td>
                            </tr>
                    <?php } ?>  
                </table>


                
                <table class="total table table-responsive table-condensed">
                    <?php foreach ($totals as $total) { ?>
                        <tr>
                            <td class="text-right"><b><?php echo $total['title']; ?></b></td>
                            <td class="text-right"><?php echo $total['text']; ?></td>
                        </tr>
                    <?php } ?>
                        <tr>
                            <td> <a href="<?php echo $cart; ?>" class="btn btn-primary btn-sm"><span><?php echo $text_cart; ?></span></a></td>
                            <td class="text-right"><a href="<?php echo $checkout; ?>" class="btn btn-primary btn-sm"><span><?php echo $button_checkout; ?></span></a></td>
                        </tr>
                </table>
               
            <?php } else { ?>
                <div class="empty alert alert-info"><?php echo $text_empty; ?></div>
            <?php } ?>

        </div>
    </div>
</div>