<div class="panel panel-default">
    <div class="panel-heading"><?php echo $heading_title; ?></div>
    <div class="panel-body">
        <ul class="list-group panel-ul-category">
            <?php foreach ($categories as $category) { ?>
                <li class="list-group-item">
                    <?php if ($this->config->get('config_product_count')): ?>
                        <span class="badge"><?php echo $category['total']; ?></span>
                    <?php endif; ?>
                    <?php if ($category['category_id'] == $category_id) { ?>
                        <a href="<?php echo $category['href']; ?>" class="active"><?php echo $category['name']; ?></a>
                    <?php } else { ?>
                        <a href="<?php echo $category['href']; ?>"><?php echo $category['name']; ?></a>
                    <?php } ?>
                    <?php if ($category['children']) { ?>
                        <ul>
                            <?php foreach ($category['children'] as $child) { ?>
                                <li>
                                    <?php if ($child['category_id'] == $child_id) { ?>
                                        <a href="<?php echo $child['href']; ?>" class="active"> - <?php echo $child['name']; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $child['href']; ?>"> - <?php echo $child['name']; ?></a>
                                    <?php } ?>
                                </li>
                            <?php } ?>
                        </ul>
                    <?php } ?>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>
