

<div class="panel panel-default">
    <div class="panel-heading">Comments (<fb:comments-count href="<?php echo $siteurl; ?>"></fb:comments-count>)</div>
    <div class="panel-body">
        <div class="box-product" id="facebook_comments_<?php echo $module; ?>">
            <div class="fb-comments" data-href="<?php echo $siteurl; ?>" data-num-posts="<?php echo $numpost; ?>" data-width="<?php echo ($width == 'auto')?'100%':$width . 'px'; ?>" data-colorscheme="<?php echo $colorscheme; ?>"></div>
        </div>
    </div>
</div>
<div id="fb-root"></div>
<script>
//    window.fbAsyncInit = function() {
//        FB.init({
//            appId: '<?php echo $appid; ?>', // App ID
//            status: true, // check login status
//            cookie: true, // enable cookies to allow the server to access the session
//            xfbml: true  // parse XFBML
//        });
//    };
    
   (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=<?php echo $appid; ?>&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>