<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>elFinder 2.0</title>
        <base href="<?php echo $base; ?>" />
        <!-- jQuery and jQuery UI (REQUIRED) -->
        <link href="view/theme/default/css/jQueryUI/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" type="text/css" />


        <script src="view/javascript/jquery-1.10.2.js"></script>
        <script src="http://code.jquery.com/jquery-migrate-1.2.1.js"></script>
        <script src="view/javascript/jquery-ui-1.10.4.custom.min.js"></script>


        <!-- elFinder CSS (REQUIRED) -->
        <link rel="stylesheet" type="text/css" media="screen" href="view/elfinder/css/elfinder.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="view/elfinder/css/theme.css">

        <!-- elFinder JS (REQUIRED) -->
        <script type="text/javascript" src="view/elfinder/js/elfinder.min.js"></script>

        <!-- elFinder translation (OPTIONAL) -->
        <?php if ($filemanger_langfile): ?>
            <script type="text/javascript" src="j<?php echo $filemanger_langfile; ?>"></script>
        <?php endif; ?>

        <!-- elFinder initialization (REQUIRED) -->
        <script type="text/javascript" charset="utf-8">


            $().ready(function() {
                var elf = $('#elfinder').elfinder({
                    url: '<?php echo $this->url->link('common/filemanager/connector'); ?>&token=<?php echo $this->session->data['token']; ?>', // connector URL (REQUIRED)
                                lang: '<?php echo $lang; ?>', // language (OPTIONAL)
                                getFileCallback: function(file) {
<?php if ($fckeditor) : ?>
                                        window.opener.CKEDITOR.tools.callFunction('<?php echo $fckeditor; ?>', '<?php echo $image_url; ?>' + file.path);
                                        self.close();
<?php else: ?>
                                        parent.console.log(file);
                                        parent.$('#<?php echo $field; ?>').attr('value', file.path);
                                        parent.$('#dialog').dialog('close');

                                        parent.$('#dialog').remove();
<?php endif; ?>

                                }
                            }).elfinder('instance');
                        });
        </script>
    </head>
    <body>

        <!-- Element where elFinder will be created (REQUIRED) -->
        <div id="elfinder"></div>

    </body>
</html>
