<div id="footer"><?php echo $text_footer; ?></div> 
</aside><!-- /.right-side -->
</div><!-- ./wrapper -->


<!-- jQuery 2.0.2 -->
<script src="view/javascript/jquery-1.10.2.js"></script>
<!--UI -->
<script src="view/theme/default/js/jquery-ui-1.10.4.custom.min.js"></script>
<!-- Bootstrap -->
<script src="view/theme/default/js/bootstrap.min.js" type="text/javascript"></script>

<script src="view/javascript/jquery.validate.min.js" type="text/javascript"></script>
<script src="view/javascript/additional-methods.min.js" type="text/javascript"></script>

<!-- AdminLTE App -->
<script src="view/theme/default/js/AdminLTE/app.js" type="text/javascript"></script>
<?php foreach ($scripts as $script) { ?>
    <script type="text/javascript" src="<?php echo $script; ?>"></script>
<?php } ?>
<script type="text/javascript">


//-----------------------------------------
// Confirm Actions (delete, uninstall)
//-----------------------------------------
    $(document).ready(function() {
        $.each(onReadyCallbacks, function(i, callback) {
            if (callback instanceof Function) {
                callback();
            }
        });
        // Confirm Delete
        $('#form').submit(function() {
            if ($(this).attr('action').indexOf('delete', 1) != -1) {
                if (!confirm('<?php echo $text_confirm; ?>')) {
                    return false;
                }
            }
        });
        // Confirm Uninstall
        $('a').click(function() {
            if ($(this).attr('href') != null && $(this).attr('href').indexOf('uninstall', 1) != -1) {
                if (!confirm('<?php echo $text_confirm; ?>')) {
                    return false;
                }
            }
        });
    });

    //Form Validation
    $('.form-validate').validate({
        highlight: function(element, errorClass, validClass) {
            $(element).closest('.form-group').addClass('has-error');
            
        },
        unhighlight: function(element, errorClass, validClass) {
            $(element).closest('.form-group').removeClass('has-error');
        },
        invalidHandler: function(event, validator) {
            // 'this' refers to the form
            var errors = validator.numberOfInvalids();
            if (errors) {
                var message = errors == 1
                        ? '<?php echo $form_missed_one; ?>'
                        : '<?php echo $form_missed_x; ?>'.replace("{{errors}}", errors);
                $("div#form-error span").html(message);
                $("div#form-error").show();
            } else {
                $("div#form-error").hide();
            }
        }

    });


</script>