<?php echo $header; ?>  
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <?php echo $heading_title; ?>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>
<!-- Main content -->
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"> 403</h2>
        <div class="error-content">
             <h3><i class="fa fa-warning text-yellow"></i> <?php echo $heading_title; ?></h3>
            <p>
               <?php echo $text_permission; ?>
            </p>
        </div><!-- /.error-content -->
    </div><!-- /.error-page -->

</section><!-- /.content -->
<?php echo $footer; ?>