<?php
$listlanguages = scandir(DIR_CATALOG . 'language/');
unset($listlanguages[0]); //Deletes the .
unset($listlanguages[1]); //Deletes the ..

if (isset($this->request->get['file']) && substr($this->request->get['file'], 0, 1) != ".") {
    $title = explode('/', $this->request->get['file']);
    $selectedfile = ucfirst($name_language) . ' :: ';
    $selectedfile .= ucwords(str_replace('_', ' ', $title[0])) . ' :: ';
    $selectedfile .= ucwords(str_replace('_', ' ', $title[1]));
    $selectedfile .= ' <span>(' . $title[1] . '.php)</span>';
} else {
    $selectedfile = ucfirst($name_language) . ' :: ' . ucfirst($name_language) . ' <span>(' . $name_language . '.php)</span>';
};
?>

<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>


<!-- Main content -->
<section class="content">
    <?php if (isset($showmsg) && $showmsg == 'error') { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $msg_error; ?>
        </div>
    <?php } ?>

    <?php if (isset($showmsg) && $showmsg == 'success') { ?>
        <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $msg_success; ?>
        </div>
    <?php } ?>
    <div id="form-error" class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <span></span>
    </div>

    <div class="box">
        <div class="box-header">
            <h3 class="box-title"> 
                <?php echo $selectedfile ?>
            </h3>

        </div>
        <div class="box-body">
            <form action="<?php echo $action_select; ?>" method = "POST" id="form" class="form-horizontal">
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="sectionlist" class="col-md-4">
                                <?php echo $entry_selectSection; ?>
                            </label>
                            <div class="col-md-8">
                                <?php
                                $selected_back_end = null;
                                $selected_front_end = null;
                                if ($section == $menu_frontend) {
                                    $selected_front_end = ' selected="selected"';
                                } else {
                                    $selected_back_end = ' selected="selected"';
                                }
                                ?>
                                <select name="sectionlist" class="form-control">
                                    <option value="catalog"<?PHP echo $selected_front_end; ?>><?php echo ucwords($menu_frontend); ?></option>
                                    <option value="admin"<?PHP echo $selected_back_end; ?>><?php echo ucwords($menu_backend); ?></option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5 col-md-offset-1">
                        <div class="form-group">
                            <label for="sectionlist" class="col-md-4">
                                <?php echo $entry_selectLang; ?>
                            </label>
                            <div class="col-md-8">
                                <select name="listlanguages" class="form-control">
                                    <?php
                                    foreach ($listlanguages as $language) {

                                        if (isset($name_language) && $name_language == $language) {
                                            ?><option value="<?php echo $language; ?>" selected="selected"><?php echo ucwords($language); ?></option><?PHP
                                        } else {
                                            ?><option value="<?php echo $language; ?>"><?php echo ucwords($language); ?></option><?PHP
                                        }
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-1">
                        <a class="btn btn-primary pull-right" onclick = "$('#form').submit()"><span><?php echo $btn_select; ?></span></a>
                    </div>
                </div>
            </form>
            <hr />
            <div class="row">
                <div class="col-md-4 right">
                    <table class="table table-responsive table-bordered">

                        <?php if (is_file(DIR_CATALOG . "language/" . $name_language . "/" . $name_language . ".php")) : ?>
                            <tr>
                                <th colspan="3" class="text-center">Core Language File</th>
                            </tr>
                            <tr>
                                <td colspan="3"><a href = "<?php echo $file_link . './' . $name_language; ?>"><?php echo $name_language; ?></a></td>

                            </tr>

                        <?php endif; ?>
                        <?php foreach ($files as $key => $value) : ?>
                            <?php foreach ($value as $dir => $filenames) : ?>
                                <?php
                                if ($dir == ".") {
                                    continue;
                                }
                                ?>
                                <tr>
                                    <th colspan="3" class="text-center"><?php echo ucfirst($dir); ?></th>
                                </tr>
                                <tr>
                                    <?php
                                    $i = 0;
                                    $passes = 0;
                                    ?>
                                    <?php foreach ($filenames as $filename) : ?>
                                        <td width = "33%"><a href = "<?php echo $file_link . $dir . '/' . $filename; ?>" ><?php echo $filename; ?></a></td>
                                        <?PHP
                                        $i++;
                                        $passes++;
                                        if ($i % 3 == 0 && $passes < count($filenames)) {
                                            echo "</tr><tr>";
                                            $i = 0;
                                        } else {
                                            if ($passes == count($filenames) && $i % 3 == 2) {
                                                echo "<td></td>";
                                            }


                                            if ($passes == count($filenames) && $i % 3 == 1) {
                                                echo "<td></td><td></td>";
                                            }
                                        }
                                        ?>
                                    <?php endforeach; ?>
                                </tr>
                            <?php endforeach; ?>
                        <?php endforeach; ?>


                    </table>
                </div>
                <div class="col-md-8">
                    <table  class="table table-responsive table-bordered">
                        <thead>
                            <tr>
                                <th class="left"><?PHP echo $menu_variable; ?></th>
                                <th class="left"><?PHP echo $menu_value; ?></th>
                                <?PHP
                                if (!isset($string)) {
                                    ?>
                                    <th align = "center"><?PHP echo $menu_edit; ?></th>
                                    <?PHP
                                } else {
                                    ?>
                                    <th align = "center" ><?PHP echo $menu_action; ?></th>
                                    <?PHP
                                }
                                ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?PHP
                            if ($file_vars) {

                                if (!isset($string)) {

                                    foreach ($file_vars as $key => $val) {
                                        ?>
                                        <tr>
                                            <td class="left"><?php echo $key; ?></td>
                                            <td class="left"><?php echo $val; ?></td>
                                            <td align = "center"><a class="btn btn-primary btn-sm" href = "<?php echo $action_edit . $key; ?>"><?php echo $entry_edit; ?></a></td>
                                        </tr>
                                        <?php
                                    }
                                } else {
                                    ?>
                                    <tr>
                                        <td  valign="top" width="10%"><?php echo $string; ?></td>
                                        <td class="left">
                                            <form id="updateform" action="<?php echo $viewing_file_link; ?>" method = "POST" class="form-inline">
                                                <textarea name = "strvalue" rows = "20" class="form-control"><?PHP echo $file_vars[$string]; ?></textarea>
                                                <input type = "hidden" name = "poststr" value = "<?PHP echo $string; ?>">
                                            </form>
                                        </td>
                                        <td width="10%" valign="top"><a class="btn btn-primary btn-sm" onclick = "$('#updateform').submit()"><span><?php echo $btn_save; ?></span> <a class="btn btn-default btn-sm" href = "<?PHP echo $viewing_file_link; ?>"><span><?php echo $btn_back; ?></span></td>
                                                    </tr>
                                                    <?php
                                                }
                                            } else {
                                                ?>
                                                <tr>
                                                    <td class="left" colspan = "3"><?php echo $msg_nofile; ?></td>
                                                </tr>
                                                <?php
                                            }
                                            ?>
                                            </tbody>
                                            </table>
                                            </div>
                                            </div>

                                            </div>

                                            </div>

                                            </section><!-- /.content -->

                                            <?php echo $footer; ?>