<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="box">
        <div class="box-body">
        <div class='row'>
            <div class='col-xs-12'>
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">

                        <li class="active"><a href="#tab-general" data-toggle="tab"><?php echo $tab_general; ?></a></li>  
                        <li><a href="#tab-store" data-toggle="tab"><?php echo $tab_store; ?></a></li>  
                        <li><a href="#tab-local" data-toggle="tab"><?php echo $tab_local; ?></a></li>  
                        <li><a href="#tab-option" data-toggle="tab"><?php echo $tab_option; ?></a></li>  
                        <li><a href="#tab-image" data-toggle="tab"><?php echo $tab_image; ?></a></li>  
                        <li><a href="#tab-ftp" data-toggle="tab"><?php echo $tab_ftp; ?></a></li>  
                        <li><a href="#tab-mail" data-toggle="tab"><?php echo $tab_mail; ?></a></li>  
                       <!-- <li><a href="#tab-fraud" data-toggle="tab"><?php echo $tab_fraud; ?></a></li>  -->
                        <li><a href="#tab-server" data-toggle="tab"><?php echo $tab_server; ?></a></li>                               
                    </ul>
                    <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form" class="form-horizontal">
                        <div class="tab-content">

                            <div class="tab-pane active" id="tab-general" >

                                <div class="form-group">
                                    <label for="config_name" class="col-sm-2 control-label required"><?php echo $entry_name; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_name" value="<?php echo $config_name; ?>" class="form-control required" id="config_name" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_owner" class="col-sm-2 control-label required"><?php echo $entry_owner; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_owner" value="<?php echo $config_owner; ?>" class="form-control required" id="config_owner" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_address" class="col-sm-2 control-label required"><?php echo $entry_address; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_address" value="<?php echo $config_address; ?>" class="form-control required" id="config_address" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_email" class="col-sm-2 control-label required"><?php echo $entry_email; ?></label>
                                    <div class="col-sm-9">
                                        <input type="email" name="config_email" value="<?php echo $config_email; ?>" class="form-control required" id="config_email" />
                                        <?php if ($error_email) { ?>
                                            <span class="error text-danger"><?php echo $error_email; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_telephone" class="col-sm-2 control-label required"><?php echo $entry_telephone; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_telephone" value="<?php echo $config_telephone; ?>" class="form-control required" id="config_telephone" />
                                        <?php if ($error_telephone) { ?>
                                            <span class="error text-danger"><?php echo $error_telephone; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_fax" class="col-sm-2 control-label"><?php echo $entry_fax; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_fax" value="<?php echo $config_fax; ?>" class="form-control" id="config_fax" />

                                    </div>
                                </div>




                            </div>

                            <div class="tab-pane" id="tab-store">

                                <div class="form-group">
                                    <label for="config_title" class="col-sm-2 control-label required"><?php echo $entry_title; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_title" value="<?php echo $config_title; ?>" class="form-control" id="config_title" />
                                        <?php if ($error_title) { ?>
                                            <span class="error text-danger"><?php echo $error_title; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_meta_description" class="col-sm-2 control-label"><?php echo $entry_meta_description; ?></label>
                                    <div class="col-sm-9"><textarea style="resize: none;" name="config_meta_description" id="config_meta_description" class="form-control" rows="5"><?php echo $config_meta_description; ?></textarea></div>
                                </div>




                                <div class="form-group">
                                    <label for="config_template" class="col-sm-2 control-label"><?php echo $entry_template; ?></label>
                                    <div class="col-sm-9"><select class="form-control" id="config_template" name="config_template" onchange="$('#template').load('index.php?route=setting/setting/template&token=<?php echo $token; ?>&template=' + encodeURIComponent(this.value));">
                                            <?php foreach ($templates as $template) { ?>
                                                <?php if ($template == $config_template) { ?>
                                                    <option value="<?php echo $template; ?>" selected="selected"><?php echo $template; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $template; ?>"><?php echo $template; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select></div>
                                </div>
                                <div class="form-group">
                                    <label for="template" class="col-sm-2 control-label">&nbsp;</label>
                                    <div class="col-sm-9" id="template"></div>
                                </div>
                                <div class="form-group">
                                    <label for="config_layout_id" class="col-sm-2 control-label"><?php echo $entry_layout; ?></label>
                                    <div class="col-sm-9"><select name="config_layout_id" id="config_layout_id" class="form-control">
                                            <?php foreach ($layouts as $layout) { ?>
                                                <?php if ($layout['layout_id'] == $config_layout_id) { ?>
                                                    <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select></div>
                                </div>


                            </div>

                            <div class="tab-pane" id="tab-local">



                                <div class="form-group">
                                    <label for="config_country_id" class="col-sm-2 control-label"><?php echo $entry_country; ?></label>
                                    <div class="col-sm-9"><select id="config_country_id" name="config_country_id" class="form-control">
                                            <?php foreach ($countries as $country) { ?>
                                                <?php if ($country['country_id'] == $config_country_id) { ?>
                                                    <option value="<?php echo $country['country_id']; ?>" selected="selected"><?php echo $country['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $country['country_id']; ?>"><?php echo $country['name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select></div>
                                </div>

                                <div class="form-group">
                                    <label for="config_zone_id" class="col-sm-2 control-label"><?php echo $entry_zone; ?></label>
                                    <div class="col-sm-9"><select id="config_zone_id" name="config_zone_id" class="form-control">
                                        </select></div>
                                </div>

                                <div class="form-group">
                                    <label for="config_city_id" class="col-sm-2 control-label"><?php echo $this->language->get("entry_city"); ?></label>
                                    <div class="col-sm-9"><select id="config_city_id" name="config_city_id" class="form-control">
                                            <option value="0"><?php echo $this->language->get("text_user_location"); ?></option>
                                            <?php foreach ($cities as $city) { ?>
                                                <?php if ($city['city_id'] == $config_city_id) { ?>
                                                    <option value="<?php echo $city['city_id']; ?>" selected="selected"><?php echo $city['city_name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $city['city_id']; ?>"><?php echo $city['city_name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select>
                                        <span class="text-info"><?php echo $this->language->get("text_city_selection_help"); ?></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_gttimezone" class="col-sm-2 control-label required"><?php echo $this->language->get("entry_timezone"); ?></label>
                                    <div class="col-sm-9">
                                        <select name="config_gttimezone" class="form-control required" id="config_gttimezone">
                                            <option value=""><?php echo $this->language->get('text_select'); ?></option>
                                            <?php foreach ($gttzlist as $t) { ?>
                                                <option <?php echo $config_gttimezone == $t ? 'selected' : ''; ?>><?php echo $t ?></option>
                                            <?php } ?>
                                        </select>

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_language" class="col-sm-2 control-label required"><?php echo $entry_language; ?></label>
                                    <div class="col-sm-9"><select id="config_language" name="config_language" class="form-control">
                                            <?php foreach ($languages as $language) { ?>
                                                <?php if ($language['code'] == $config_language) { ?>
                                                    <option value="<?php echo $language['code']; ?>" selected="selected"><?php echo $language['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $language['code']; ?>"><?php echo $language['name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select></div>
                                </div>

                                <div class="form-group">
                                    <label for="config_admin_language" class="col-sm-2 control-label required"><?php echo $entry_admin_language; ?></label>
                                    <div class="col-sm-9"><select id="config_admin_language" name="config_admin_language" class="form-control">
                                            <?php foreach ($languages as $language) { ?>
                                                <?php if ($language['code'] == $config_admin_language) { ?>
                                                    <option value="<?php echo $language['code']; ?>" selected="selected"><?php echo $language['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $language['code']; ?>"><?php echo $language['name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select></div>
                                </div>



                                <div class="form-group">
                                    <label for="config_currency" class="col-sm-2 control-label required"><?php echo $entry_currency; ?></label>
                                    <div class="col-sm-9"><select id="config_currency" name="config_currency" class="form-control">
                                            <?php foreach ($currencies as $currency) { ?>
                                                <?php if ($currency['code'] == $config_currency) { ?>
                                                    <option value="<?php echo $currency['code']; ?>" selected="selected"><?php echo $currency['title']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $currency['code']; ?>"><?php echo $currency['title']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select></div>
                                </div>





                            </div>

                            <div class="tab-pane" id="tab-option">
                                <legend><?php echo $text_items; ?></legend>

                                <div class="form-group">
                                    <label for="config_catalog_limit" class="col-sm-2 control-label required"><?php echo $entry_catalog_limit; ?></label>
                                    <div class="col-sm-3"><input class="form-control" type="number" name="config_catalog_limit" value="<?php echo $config_catalog_limit; ?>" size="3" />
                                        <span class="text-info"><?php echo $entry_catalog_limit_help; ?></span>
                                        <?php if ($error_catalog_limit) { ?>
                                            <span class="error text-danger"><?php echo $error_catalog_limit; ?></span>
                                        <?php } ?></div>
                                </div>
                                <div class="form-group">
                                    <label for="config_admin_limit" class="col-sm-2 control-label required"><?php echo $entry_admin_limit; ?></label>
                                    <div class="col-sm-3"><input class="form-control" type="number" name="config_admin_limit" value="<?php echo $config_admin_limit; ?>" size="3" />
                                        <span class="text-info"><?php echo $entry_catalog_limit_help; ?></span>
                                        <?php if ($error_admin_limit) { ?>
                                            <span class="error text-danger"><?php echo $error_admin_limit; ?></span>
                                        <?php } ?></div>
                                </div>




                                <legend><?php echo $text_account; ?></legend>

                                <div class="form-group">
                                    <label for="config_admin_limit" class="col-sm-2 control-label required"><?php echo $entry_customer_online; ?></label>
                                    <div class="col-sm-9"><?php if ($config_customer_online) { ?>
                                            <input type="radio" name="config_customer_online" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_customer_online" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_customer_online" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_customer_online" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?></div>
                                </div>

                                <div class="form-group">
                                    <label for="config_account_id" class="col-sm-2 control-label required"><?php echo $entry_account; ?></label>
                                    <div class="col-sm-9">
                                        <select name="config_account_id" class="form-control">
                                            <option value="0"><?php echo $text_none; ?></option>
                                            <?php foreach ($informations as $information) { ?>
                                                <?php if ($information['information_id'] == $config_account_id) { ?>
                                                    <option value="<?php echo $information['information_id']; ?>" selected="selected"><?php echo $information['title']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $information['information_id']; ?>"><?php echo $information['title']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                                <legend><?php echo $text_checkout; ?></legend>


                                <div class="form-group">
                                    <label for="config_admin_limit" class="col-sm-2 control-label required"><?php echo $entry_guest_checkout; ?></label>
                                    <div class="col-sm-9"><?php if ($config_guest_checkout) { ?>
                                            <input type="radio" name="config_guest_checkout" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_guest_checkout" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_guest_checkout" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_guest_checkout" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?></div>
                                </div>

                                <div class="form-group">
                                    <label for="config_checkout_id" class="col-sm-2 control-label required"><?php echo $entry_checkout; ?></label>
                                    <div class="col-sm-9">
                                        <select name="config_checkout_id" class="form-control">
                                            <option value="0"><?php echo $text_none; ?></option>
                                            <?php foreach ($informations as $information) { ?>
                                                <?php if ($information['information_id'] == $config_checkout_id) { ?>
                                                    <option value="<?php echo $information['information_id']; ?>" selected="selected"><?php echo $information['title']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $information['information_id']; ?>"><?php echo $information['title']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_invoice_prefix" class="col-sm-2 control-label"><?php echo $entry_invoice_prefix; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_invoice_prefix" value="<?php echo $config_invoice_prefix; ?>" class="form-control" id="config_invoice_prefix" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_order_status_id" class="col-sm-2 control-label required"><?php echo $entry_order_status; ?></label>
                                    <div class="col-sm-9">
                                        <select name="config_order_status_id" class="form-control">
                                            <?php foreach ($order_statuses as $order_status) { ?>
                                                <?php if ($order_status['order_status_id'] == $config_order_status_id) { ?>
                                                    <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_complete_status_id" class="col-sm-2 control-label required"><?php echo $entry_complete_status; ?></label>
                                    <div class="col-sm-9">
                                        <select name="config_complete_status_id" class="form-control">
                                            <?php foreach ($order_statuses as $order_status) { ?>
                                                <?php if ($order_status['order_status_id'] == $config_complete_status_id) { ?>
                                                    <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>

                            </div>

                            <div class="tab-pane" id="tab-image">
                                <div class="form-group">
                                    <label for="imageInput" class="col-sm-2 control-label "><?php echo $entry_logo; ?></label>
                                    <div class="col-sm-9">
                                        <div class="row" id="deal-img-container">

                                            <div class="image well well-sm pull-left">
                                                <img src="<?php echo $logo; ?>" alt="" id="thumb-logo" />
                                                <input type="hidden" name="config_logo" value="<?php echo $config_logo; ?>" id="logo" /><br />
                                                <button type="button" class="btn btn-primary btn-sm" onclick="image_upload('logo', 'thumb-logo');"><?php echo $text_browse; ?></button>
                                                <button type="button" class="btn btn-danger btn-sm" onclick="$('#thumb-logo').attr('src', '<?php echo $no_image; ?>');
                                                        $('#logo').attr('value', '');"><?php echo $text_clear; ?></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="iconInput" class="col-sm-2 control-label "><?php echo $entry_icon; ?></label>
                                    <div class="col-sm-9">
                                        <div class="row" id="deal-img-container">

                                            <div class="image well well-sm pull-left">
                                                <img src="<?php echo $icon; ?>" alt="" id="thumb-icon" />
                                                <input type="hidden" name="config_icon" value="<?php echo $config_icon; ?>" id="icon" /><br />
                                                <button type="button" class="btn btn-primary btn-sm" onclick="image_upload('icon', 'thumb-icon');"><?php echo $text_browse; ?></button>
                                                <button type="button" class="btn btn-danger btn-sm" onclick="$('#thumb-icon').attr('src', '<?php echo $no_image; ?>');
                                                        $('#icon').attr('value', '');"><?php echo $text_clear; ?></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_image_cart_width" class="col-sm-2 control-label required"><?php echo $entry_image_cart; ?></label>
                                    <div class="col-sm-1">
                                        <input class="form-control" type="number" name="config_image_cart_width" value="<?php echo $config_image_cart_width; ?>" size="3" />
                                    </div>
                                    <div class="pull-left text-center" style="line-height:2.5;">X</div>
                                    <div class="col-sm-1">
                                        <input class="form-control" type="number" name="config_image_cart_height" value="<?php echo $config_image_cart_height; ?>" size="3" />
                                    </div>
                                </div>


                            </div>

                            <div class="tab-pane" id="tab-ftp">

                                <div class="form-group">
                                    <label for="config_ftp_host" class="col-sm-2 control-label"><?php echo $entry_ftp_host; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_ftp_host" value="<?php echo $config_ftp_host; ?>" class="form-control" id="config_ftp_host" />
                                        <?php if ($error_ftp_host) { ?>
                                            <span class="error"><?php echo $error_ftp_host; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_ftp_port" class="col-sm-2 control-label"><?php echo $entry_ftp_port; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_ftp_port" value="<?php echo $config_ftp_port; ?>" class="form-control" id="config_ftp_port" />
                                        <?php if ($error_ftp_port) { ?>
                                            <span class="error"><?php echo $error_ftp_port; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_ftp_username" class="col-sm-2 control-label"><?php echo $entry_ftp_username; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_ftp_username" value="<?php echo $config_ftp_username; ?>" class="form-control" id="config_ftp_username" />
                                        <?php if ($error_ftp_username) { ?>
                                            <span class="error"><?php echo $error_ftp_username; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_ftp_password" class="col-sm-2 control-label"><?php echo $entry_ftp_password; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_ftp_password" value="<?php echo $config_ftp_password; ?>" class="form-control" id="config_ftp_password" />
                                        <?php if ($error_ftp_password) { ?>
                                            <span class="error"><?php echo $error_ftp_password; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_ftp_root" class="col-sm-2 control-label"><?php echo $entry_ftp_root; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_ftp_root" value="<?php echo $config_ftp_root; ?>" class="form-control" id="config_ftp_root" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_ftp_status" class="col-sm-2 control-label"><?php echo $entry_ftp_status; ?></label>
                                    <div class="col-sm-9">
                                        <?php if ($config_ftp_status) { ?>
                                            <input type="radio" name="config_ftp_status" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_ftp_status" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_ftp_status" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_ftp_status" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>

                            <div class="tab-pane" id="tab-mail">

                                <div class="form-group">
                                    <label for="config_mail_protocol" class="col-sm-2 control-label"><?php echo $entry_mail_protocol; ?></label>
                                    <div class="col-sm-9">
                                        <select name="config_mail_protocol" class="form-control">
                                            <?php if ($config_mail_protocol == 'mail') { ?>
                                                <option value="mail" selected="selected"><?php echo $text_mail; ?></option>
                                            <?php } else { ?>
                                                <option value="mail"><?php echo $text_mail; ?></option>
                                            <?php } ?>
                                            <?php if ($config_mail_protocol == 'smtp') { ?>
                                                <option value="smtp" selected="selected"><?php echo $text_smtp; ?></option>
                                            <?php } else { ?>
                                                <option value="smtp"><?php echo $text_smtp; ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_mail_parameter" class="col-sm-2 control-label"><?php echo $entry_mail_parameter; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_mail_parameter" value="<?php echo $config_mail_parameter; ?>" class="form-control" id="config_mail_parameter" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_smtp_host" class="col-sm-2 control-label"><?php echo $entry_smtp_host; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_smtp_host" value="<?php echo $config_smtp_host; ?>" class="form-control" id="config_smtp_host" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_smtp_username" class="col-sm-2 control-label"><?php echo $entry_smtp_username; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_smtp_username" value="<?php echo $config_smtp_username; ?>" class="form-control" id="config_smtp_username" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_smtp_password" class="col-sm-2 control-label"><?php echo $entry_smtp_password; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_smtp_password" value="<?php echo $config_smtp_password; ?>" class="form-control" id="config_smtp_password" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_smtp_port" class="col-sm-2 control-label"><?php echo $entry_smtp_port; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_smtp_port" value="<?php echo $config_smtp_port; ?>" class="form-control" id="config_smtp_port" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_smtp_timeout" class="col-sm-2 control-label"><?php echo $entry_smtp_timeout; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_smtp_timeout" value="<?php echo $config_smtp_timeout; ?>" class="form-control" id="config_smtp_timeout" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_alert_mail" class="col-sm-2 control-label"><?php echo $entry_alert_mail; ?></label>
                                    <div class="col-sm-9">
                                        <?php if ($config_alert_mail) { ?>
                                            <input type="radio" name="config_alert_mail" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_alert_mail" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_alert_mail" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_alert_mail" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_account_mail" class="col-sm-2 control-label"><?php echo $entry_account_mail; ?></label>
                                    <div class="col-sm-9">
                                        <?php if ($config_account_mail) { ?>
                                            <input type="radio" name="config_account_mail" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_account_mail" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_account_mail" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_account_mail" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_alert_emails" class="col-sm-2 control-label"><?php echo $entry_alert_emails; ?></label>
                                    <div class="col-sm-9">
                                        <textarea name="config_alert_emails" class="form-control" rows="5"><?php echo $config_alert_emails; ?></textarea>

                                    </div>
                                </div>
                            </div>

                            <div class="tab-pane" id="tab-fraud">

                                <div class="form-group">
                                    <label for="config_fraud_detection" class="col-sm-2 control-label"><?php echo $entry_fraud_detection; ?></label>
                                    <div class="col-sm-9"><?php if ($config_fraud_detection) { ?>
                                            <input type="radio" name="config_fraud_detection" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_fraud_detection" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_fraud_detection" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_fraud_detection" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_fraud_key" class="col-sm-2 control-label"><?php echo $entry_fraud_key; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_fraud_key" value="<?php echo $config_fraud_key; ?>" class="form-control" id="config_fraud_key" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_fraud_score" class="col-sm-2 control-label"><?php echo $entry_fraud_score; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_fraud_score" value="<?php echo $config_fraud_score; ?>" class="form-control" id="config_fraud_score" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_fraud_status" class="col-sm-2 control-label"><?php echo $entry_fraud_status; ?></label>
                                    <div class="col-sm-9">
                                        <select name="config_fraud_status_id" class="form-control">
                                            <?php foreach ($order_statuses as $order_status) { ?>
                                                <?php if ($order_status['order_status_id'] == $config_fraud_status_id) { ?>
                                                    <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="tab-pane" id="tab-server">

                                <div class="form-group">
                                    <label for="config_secure" class="col-sm-2 control-label"><?php echo $entry_secure; ?></label>
                                    <div class="col-sm-9">
                                        <?php if ($config_secure) { ?>
                                            <input type="radio" name="config_secure" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_secure" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_secure" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_secure" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_shared" class="col-sm-2 control-label"><?php echo $entry_shared; ?></label>
                                    <div class="col-sm-9">
                                        <?php if ($config_shared) { ?>
                                            <input type="radio" name="config_shared" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_shared" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_shared" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_shared" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_robots" class="col-sm-2 control-label"><?php echo $entry_robots; ?></label>
                                    <div class="col-sm-9">
                                        <textarea class="form-control" name="config_robots" cols="40" rows="5"><?php echo $config_robots; ?></textarea>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_seo_url" class="col-sm-2 control-label"><?php echo $entry_seo_url; ?></label>
                                    <div class="col-sm-9">
                                        <?php if ($config_seo_url) { ?>
                                            <input type="radio" name="config_seo_url" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_seo_url" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_seo_url" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_seo_url" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>  
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_maintenance" class="col-sm-2 control-label"><?php echo $entry_maintenance; ?></label>
                                    <div class="col-sm-9">
                                        <?php if ($config_maintenance) { ?>
                                            <input type="radio" name="config_maintenance" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_maintenance" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_maintenance" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_maintenance" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>  
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_encryption" class="col-sm-2 control-label required"><?php echo $entry_encryption; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_encryption" value="<?php echo $config_encryption; ?>" class="form-control" id="config_encryption" />
                                        <?php if ($error_encryption) { ?>
                                            <span class="error text-danger"><?php echo $error_encryption; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_compression" class="col-sm-2 control-label "><?php echo $entry_compression; ?></label>
                                    <div class="col-sm-1">
                                        <input min="0" max="9" type="number" name="config_compression" value="<?php echo $config_compression; ?>" class="form-control" id="config_compression" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_error_display" class="col-sm-2 control-label "><?php echo $entry_error_display; ?></label>
                                    <div class="col-sm-9">
                                        <?php if ($config_error_display) { ?>
                                            <input type="radio" name="config_error_display" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_error_display" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_error_display" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_error_display" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_error_log" class="col-sm-2 control-label "><?php echo $entry_error_log; ?></label>
                                    <div class="col-sm-9">
                                        <?php if ($config_error_log) { ?>
                                            <input type="radio" name="config_error_log" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_error_log" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_error_log" value="1" />
                                            <?php echo $text_yes; ?>
                                            <input type="radio" name="config_error_log" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="config_error_filename" class="col-sm-2 control-label required"><?php echo $entry_error_filename; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" name="config_error_filename" value="<?php echo $config_error_filename; ?>" class="form-control" id="config_error_filename" />
                                        <?php if ($error_error_filename) { ?>
                                            <span class="error text-danger"><?php echo $error_error_filename; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                 <div class="form-group">
                                    <label for="config_google_analytics" class="col-sm-2 control-label "><?php echo $entry_google_analytics; ?></label>
                                    <div class="col-sm-9">
                                       <textarea class="form-control" name="config_google_analytics" cols="40" rows="5"><?php echo $config_google_analytics; ?></textarea>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
        
        <div class="box-footer">
            <div class="box-footer clearfix">
                    <div id="form-error" class="alert alert-danger alert-dismissable">
                        <i class="fa fa-ban"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <span></span>
                    </div>
                    <button class="btn btn-primary col-sm-offset-2" onclick="$('#form').submit();" >
                        <i class="fa fa-check"></i> <?php echo $button_save; ?>
                    </button>
                    <a href="<?php echo $cancel; ?>" class="btn btn-danger">
        <i class="fa fa-times"></i> <?php echo $button_cancel; ?>
    </a>
                </div>
        </div>
    </div>
</section><!-- /.content -->

<script type="text/javascript"><!--
    

    addOnready(function() {
        $('#template').load('index.php?route=setting/setting/template&token=<?php echo $token; ?>&template=' + encodeURIComponent($('#config_template').val()));

        $('#config_country_id').on('change', function() {
            $.ajax({
                url: 'index.php?route=setting/setting/country&token=<?php echo $token; ?>&country_id=' + this.value,
                dataType: 'json',
                beforeSend: function() {
                    $('#country_id').after('<span class="wait">&nbsp;<img src="view/image/loading.gif" alt="" /></span>');
                },
                complete: function() {
                    $('.wait').remove();
                },
                success: function(json) {
                    if (json['postcode_required'] == '1') {
                        $('#postcode-required').show();
                    } else {
                        $('#postcode-required').hide();
                    }

                    var html = '<option value=""><?php echo $text_select; ?></option>';

                    if (json['zone'] != '') {
                        for (i = 0; i < json['zone'].length; i++) {
                            html += '<option value="' + json['zone'][i]['zone_id'] + '"';

                            if (json['zone'][i]['zone_id'] == '<?php echo $config_zone_id; ?>') {
                                html += ' selected="selected"';
                            }

                            html += '>' + json['zone'][i]['name'] + '</option>';
                        }
                    } else {
                        html += '<option value="0" selected="selected"><?php echo $text_none; ?></option>';
                    }

                    $('#config_zone_id').html(html);
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        });
        $('#config_country_id').trigger('change');



    });
//--></script> 

<?php echo $footer; ?>