<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-cog"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>
<section class="page-actions">
    <a href="<?php echo $insert; ?>" class="btn btn-primary">
        <i class="fa fa-plus"></i> <?php echo $button_insert; ?>
    </a>
    <button class="btn btn-danger" onclick="$('#form').submit();">
        <i class="fa fa-times"></i> <?php echo $button_delete; ?>
    </button>

</section>

<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>
    <?php if ($success) { ?>
        <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $success; ?>
        </div>
    <?php } ?>

    <div class="box">
        <div class="box-body">
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th width="1" style="text-align: center;"><input class="selectall" type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" /></th>
                            <th class="left"><?php echo $column_name; ?></a></th>
                            <th class="left"><?php echo $column_url; ?></th>
                            <th class="right"><?php echo $column_action; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($stores) { ?>
                            <?php foreach ($stores as $store) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php if ($store['selected']) { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $store['store_id']; ?>" checked="checked" />
                                        <?php } else { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $store['store_id']; ?>" />
                                        <?php } ?></td>
                                    <td class="left"><?php echo $store['name']; ?></td>
                                    <td class="left"><?php echo $store['url']; ?></td>
                                    <td class="right"><?php foreach ($store['action'] as $action) { ?>
                                            <a class="btn btn-xs btn-primary" href="<?php echo $action['href']; ?>"><?php echo $action['text']; ?></a> 
                                        <?php } ?></td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td class="center" colspan="4"><div class="alert alert-info"><?php echo $text_no_results; ?></div></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </form>
        </div>

    </div>


</section><!-- /.content -->

<?php echo $footer; ?>