<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>
    <?php if ($success) { ?>
        <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $success; ?>
        </div>
    <?php } ?>

    <div class="box">
        <div class='row'>
            <div class='col-xs-12'>
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab-scripts" data-toggle="tab"><?php echo $tab_scripts; ?></a></li>  
                        <li><a href="#tab-settings" data-toggle="tab"><?php echo $tab_settings; ?></a></li>  
                        <li><a href="#tab-error" data-toggle="tab"><?php echo $tab_error_log; ?></a></li>                   
                    </ul>

                    <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form" class="form-horizontal">

                        <div class="tab-content">
                            <div class="tab-pane active" id="tab-scripts" >
                                <table  class="table table-bordered table-striped table-responsive">
                                    <thead>
                                        <tr>
                                            <th class="left"><?php echo $column_file_name; ?><br /><i><?php echo $column_id; ?></i></th>
                                            <th class="center"><?php echo $column_version; ?></th>
                                            <th class="center"><?php echo $column_vqmver; ?></th>
                                            <th class="center"><?php echo $column_author; ?></th>
                                            <th class="center"><?php echo $column_status; ?></th>
                                            <th class="center"><?php echo $column_action; ?></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if ($vqmods) { ?>
                                            <?php foreach ($vqmods as $vqmod) { ?>
                                                <tr >
                                                    <td class="left"><strong><?php echo $vqmod['file_name']; ?></strong><br /><div class="description"><?php echo $vqmod['id']; ?><br /><?php echo $vqmod['invalid_xml']; ?></div></td>
                                                    <td class="center"><?php echo $vqmod['version']; ?></td>
                                                    <td class="center"><?php echo $vqmod['vqmver']; ?></td>
                                                    <td class="center"><?php echo $vqmod['author']; ?></td>
                                                    <td class="center"><?php echo $vqmod['status'] ?></td>
                                                    <td class="action">
                                                        <?php if ($vqmod['file_name'] != 'vqmod_opendeal.xml'): ?>
                                                            <?php foreach ($vqmod['action'] as $action) { ?>
                                                                <a class="btn btn-primary btn-xs" href="<?php echo $action['href']; ?>"><?php echo $action['text']; ?></a> 
                                                            <?php } ?>
                                                            <a class="btn btn-danger btn-xs" href="<?php echo $vqmod['delete'] ?>"><?php echo $text_delete; ?></a> 
                                                        <?php endif; ?>
                                                    </td>
                                                </tr>
                                            <?php } ?>
                                        <?php } else { ?>
                                            <tr>
                                                <td class="center" colspan="6"><?php echo $text_no_results; ?></td>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th colspan="6">
                                    <div class="form-group">
                                        <label for="vqmod_file" class="col-sm-2 control-label required"><?php echo $entry_upload; ?></label>
                                        <div class="col-sm-7">
                                            <input type="file" name="vqmod_file" class="form-control required" id="vqmod_file" />
                                        </div>
                                        <div class="col-sm-2">
                                            <input type="submit" class="btn btn-primary" name="upload" value="<?php echo $text_upload; ?>" />
                                        </div>
                                    </div>
                                    </th>
                                    </tr>
                                    </tfoot>
                                </table>

                            </div>
                            <div class="tab-pane" id="tab-settings" >

                                <div class="form-group">
                                    <label for="vqcache" class="col-sm-2 control-label"><?php echo $entry_vqcache; ?>
                                        <span class="help-block"><?php echo $text_vqcache_help; ?></span></label>
                                    <div class="col-sm-6">


                                        <select multiple="multiple" size="7" id="vqcache" class="form-control">
                                            <?php foreach ($vqcache as $vqcache_file) { ?>
                                                <option><?php echo $vqcache_file; ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <a href="<?php echo $clear_vqcache; ?>" class="btn btn-warning"><span><?php echo $button_clear; ?></span></a>
                                        <?php if ($ziparchive) { ?>
                                            <a href="<?php echo $download_vqcache; ?>" class="btn btn-success"><span><?php echo $button_vqcache_dump; ?></span></a>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="entry_backup" class="col-sm-2 control-label"><?php echo $entry_backup; ?>

                                    </label>
                                    <div class="col-sm-9">
                                        <?php if ($ziparchive) { ?>
                                            <td><a href="<?php echo $download_scripts; ?>" class="btn btn-primary"><span><?php echo $button_backup; ?></span></a></td>
                                        <?php } else { ?>
                                            <td><?php echo $error_ziparchive; ?></td>
                                        <?php } ?>
                                    </div>
                                </div>

                                <table class="table table-bordered table-striped table-responsive table-condensed">


                                    <tr>
                                        <td><strong><?php echo $entry_vqmod_path; ?></strong></td>
                                        <td><?php echo $vqmod_path; ?></td>
                                    </tr>
                                    <?php if ($vqmod_vars) { ?>
                                        <?php foreach ($vqmod_vars as $vqmod_var) { ?>
                                            <tr>
                                                <td><strong><?php echo $vqmod_var['setting']; ?></strong></td>
                                                <td><?php echo $vqmod_var['value']; ?></td>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>
                                </table>
                            </div>
                            <div class="tab-pane" id="tab-error" >
                                <div class="form-group">
                                    <textarea rows="20" class="form-control" id="error-log"><?php echo $log; ?></textarea>
                                    <div class="clearfix">
                                        <?php if ($ziparchive) { ?><a href="<?php echo $download_log; ?>" class="btn btn-primary pull-right">
                                                <span><?php echo $button_download_log; ?></span></a>
                                        <?php } ?> 
                                        <a href="<?php echo $clear_log; ?>" class="btn btn-warning pull-right"><span><?php echo $button_clear; ?></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>

    </div>

</section><!-- /.content -->

<?php echo $footer; ?>