<?php echo $header; ?>
<div class="form-box" id="login-box">
    <div class="header"><?php echo $text_login; ?></div>
    
    <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form">

        <div class="body bg-gray">
            <?php if ($success) { ?>
        <div class="alert alert-success"><?php echo $success; ?></div>
    <?php } ?>
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger"><?php echo $error_warning; ?></div>
    <?php } ?>
            
            <div class="form-group">
                <input type="text" name="username" value="<?php echo $username; ?>" class="form-control" placeholder="<?php echo $entry_username; ?>"/>
            </div>
            <div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="<?php echo $entry_password; ?>"/>
            </div>          

        </div>
        <div class="footer">                                                               
            <button type="submit" class="btn bg-olive btn-block"><?php echo $button_login; ?></button>  

            <p><a href="<?php echo $forgotten; ?>"><?php echo $text_forgotten; ?></a></p>

        </div>
        <?php if ($redirect) { ?>
            <input type="hidden" name="redirect" value="<?php echo $redirect; ?>" />
        <?php } ?>
    </form>
</div>

<script type="text/javascript"><!--
    addOnready(function() {
        $('#form input').keydown(function(e) {
            if (e.keyCode == 13) {
                $('#form').submit();
            }
        });
    });
//--></script> 
<?php echo $footer; ?>