<?php echo $header; ?>
<div class="form-box" id="login-box">
    <div class="header"><?php echo $heading_title; ?></div>

    <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="reset">

        <div class="body bg-gray">

            <?php if ($error_warning) { ?>
                <div class="alert alert-danger"><?php echo $error_warning; ?></div>
            <?php } ?>
            <p><?php echo $text_password; ?></p>
            <div class="form-group">
                <input type="password" name="password" value="<?php echo $password; ?>" class="form-control" placeholder="<?php echo $entry_password; ?>" />
                <?php if ($error_password) { ?>
                    <span class="error text-red"><?php echo $error_password; ?></span>
                <?php } ?>
            </div>    
            <div class="form-group">
                <input type="password" name="confirm" value="<?php echo $confirm; ?>" class="form-control" placeholder="<?php echo $entry_confirm; ?>" />
                <?php if ($error_confirm) { ?>
                    <span class="error text-red"><?php echo $error_confirm; ?></span>
                <?php } ?>
            </div>  

        </div>
        <div class="footer">                                                               
            <button type="submit" class="btn bg-olive btn-block"><?php echo $button_save; ?></button>
            <a href="<?php echo $cancel; ?>" class="btn btn-block"><?php echo $button_cancel; ?></a>



        </div>

    </form>
</div>

<script type="text/javascript"><!--
    addOnready(function() {
        $('#form input').keydown(function(e) {
            if (e.keyCode == 13) {
                $('#form').submit();
            }
        });
    });
//--></script> 
<?php echo $footer; ?>