<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>
<section class="page-actions">

    <a onclick="$('#form').submit();" class="btn btn-primary">
        <i class="fa fa-plus"></i> <?php echo $button_save; ?>
    </a>
    <a href="<?php echo $cancel; ?>" class="btn btn-danger" onclick="$('#form').submit();">
        <i class="fa fa-times"></i> <?php echo $button_cancel; ?>
    </a>

</section>

<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>

    <div id="form-error" class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <span></span>
    </div>

    <div class="box">
        <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form" class="form-horizontal">
            <fieldset>
                <legend><?php echo $text_general; ?></legend>
                <div class="form-group">
                    <label for="total_status" class="col-sm-2 control-label required"><?php echo $entry_status; ?></label>
                    <div class="col-sm-9">
                        <select name="total_status" id="total_status" class="form-control">
                            <?php if ($total_status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="total_sort_order" class="col-sm-2 control-label"><?php echo $entry_sort_order; ?></label>
                    <div class="col-sm-1">
                        <input type="text" name="total_sort_order" value="<?php echo $total_sort_order; ?>" size="1" class="form-control"/>
                    </div>
                </div>
              
            </fieldset>
        </form>

    </div>

</section><!-- /.content -->

<?php echo $footer; ?>