<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>
<section class="page-actions">


</section>

<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>

    <div id="form-error" class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <span></span>
    </div>

    <div class="box">
        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form" class="form-horizontal">
                <fieldset>
                    <legend>Gateway Settings</legend>

                    <div class="form-group">
                        <label for="cod_total" class="col-sm-2 control-label required"><?php echo $entry_total; ?></label>
                        <div class="col-sm-9">
                            <input type="text" name="cod_total" value="<?php echo $cod_total; ?>" class="form-control required number" id="cod_total" />

                        </div>
                    </div>







                    <div class="form-group">
                        <label for="cod_geo_zone_id" class="col-sm-2 control-label"><?php echo $entry_geo_zone; ?></label>
                        <div class="col-sm-9">
                            <select name="cod_geo_zone_id" class="form-control">
                                <option value="0"><?php echo $text_all_zones; ?></option>
                                <?php foreach ($geo_zones as $geo_zone) { ?>
                                    <?php if ($geo_zone['geo_zone_id'] == $cod_geo_zone_id) { ?>
                                        <option value="<?php echo $geo_zone['geo_zone_id']; ?>" selected="selected"><?php echo $geo_zone['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $geo_zone['geo_zone_id']; ?>"><?php echo $geo_zone['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="cod_status" class="col-sm-2 control-label"><?php echo $entry_status; ?></label>
                        <div class="col-sm-9">
                            <select name="cod_status" class="form-control">
                                <?php if ($cod_status) { ?>
                                    <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                    <option value="0"><?php echo $text_disabled; ?></option>
                                <?php } else { ?>
                                    <option value="1"><?php echo $text_enabled; ?></option>
                                    <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>





                    <div class="form-group">
                        <label for="cod_sort_order" class="col-sm-2 control-label"><?php echo $entry_sort_order; ?></label>
                        <div class="col-sm-1">
                            <input type="text" name="cod_sort_order" value="<?php echo $cod_sort_order; ?>" size="1" class="form-control"/>
                        </div>
                    </div>

                </fieldset>
                <fieldset>
                    <legend>Order Statuses</legend>
                    <div class="form-group">
                        <label for="cod_order_status_id" class="col-sm-2 control-label"><?php echo $entry_order_status; ?></label>
                        <div class="col-sm-9">
                            <select name="cod_order_status_id" class="form-control">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $cod_order_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>



                </fieldset>
            </form>

        </div>
        <div class="box-footer clearfix">
            <a onclick="$('#form').submit();" class="btn btn-primary col-sm-offset-2">
                <i class="fa fa-plus"></i> <?php echo $button_save; ?>
            </a>
            <a href="<?php echo $cancel; ?>" class="btn btn-danger" onclick="$('#form').submit();">
                <i class="fa fa-times"></i> <?php echo $button_cancel; ?>
            </a>

        </div>
    </div>

</section><!-- /.content -->

<?php echo $footer; ?>