<?php
/**
 * admin/view/template/payment/payfast.tpl
 *
 * Copyright (c) 2009-2012 PayFast (Pty) Ltd
 * 
 * LICENSE:
 * 
 * This payment module is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 3 of the License, or (at
 * your option) any later version.
 * 
 * This payment module is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 * 
 * @author     Ron Darby
 * @copyright  2009-2012 PayFast (Pty) Ltd
 * @license    http://www.opensource.org/licenses/lgpl-license.php LGPL
 * @version    1.1.1
 */

?>
<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>
<section class="page-actions">

    <a onclick="$('#form').submit();" class="btn btn-primary">
        <i class="fa fa-plus"></i> <?php echo $button_save; ?>
    </a>
    <a href="<?php echo $cancel; ?>" class="btn btn-danger" onclick="$('#form').submit();">
        <i class="fa fa-times"></i> <?php echo $button_cancel; ?>
    </a>

</section>

<section class="content">
    
	
  <div class="box">
  
    <div class="box-body">
	<?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>
	<div id="form-error" class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <span></span>
    </div>
      <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form" class="form-horizontal">
       
           <div class="form-group" >
		   
            <label  class="col-sm-2 control-label"><?php echo $entry_merchant_id; ?></label>
			<div class="col-sm-9"><input type="text" class="form-control"  name="payfast_merchant_id" value="<?php echo $payfast_merchant_id; ?>" /></div>
          </div>
           <div class="form-group" >
            <label  class="col-sm-2 control-label"><?php echo $entry_merchant_key; ?></label>
			<div class="col-sm-9"><input type="text" class="form-control"  name="payfast_merchant_key" value="<?php echo $payfast_merchant_key; ?>" /></div>
          </div>
           <div class="form-group" >
            <label  class="col-sm-2 control-label"><?php echo $entry_sandbox; ?></label>
			<div class="col-sm-9">
              <input type="radio" name="payfast_sandbox" value="1" <?php if ($payfast_sandbox) { ?> checked="checked" <?php }; ?> />
              <?php echo $text_yes; ?>
              <input type="radio" name="payfast_sandbox" value="0" <?php if (!$payfast_sandbox) { ?> checked="checked" <?php }; ?> />
              <?php echo $text_no; ?>
             </div>
          </div>
           <div class="form-group" >
            <label  class="col-sm-2 control-label"><?php echo $text_debug; ?></label>
			<div class="col-sm-9">
              <input type="radio" name="payfast_debug" value="1" <?php if ($payfast_debug) { ?> checked="checked" <?php }; ?> />
              <?php echo $text_yes; ?>
              <input type="radio" name="payfast_debug" value="0" <?php if (!$payfast_debug) { ?> checked="checked" <?php }; ?> />
              <?php echo $text_no; ?>
             </div>
          </div>
         
           <div class="form-group" >
            <label  class="col-sm-2 control-label"><?php echo $entry_total; ?></label>
			<div class="col-sm-9"><input type="text" class="form-control"  name="payfast_total" value="<?php echo $payfast_total; ?>" /></div>
          </div>          
         
           <div class="form-group" >
            <label  class="col-sm-2 control-label"><?php echo $entry_completed_status; ?></label>
			<div class="col-sm-9"><select class="form-control" name="payfast_completed_status_id">
                <?php foreach ($order_statuses as $order_status) { ?>
                <?php if ($order_status['order_status_id'] == $payfast_completed_status_id) { ?>
                <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                <?php } else { ?>
                <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                <?php } ?>
                <?php } ?>
              </select></div>
          </div>
         
         
           <div class="form-group" >
            <label  class="col-sm-2 control-label"><?php echo $entry_failed_status; ?></label>
			<div class="col-sm-9"><select class="form-control" name="payfast_failed_status_id">
                <?php foreach ($order_statuses as $order_status) { ?>
                <?php if ($order_status['order_status_id'] == $payfast_failed_status_id) { ?>
                <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                <?php } else { ?>
                <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                <?php } ?>
                <?php } ?>
              </select></div>
          </div>
           <div class="form-group" >
            <label  class="col-sm-2 control-label"><?php echo $entry_cancelled_status; ?></label>
			<div class="col-sm-9"><select class="form-control" name="payfast_cancelled_status_id">
                <?php foreach ($order_statuses as $order_status) { ?>
                <?php if ($order_status['order_status_id'] == $payfast_cancelled_status_id) { ?>
                <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                <?php } else { ?>
                <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                <?php } ?>
                <?php } ?>
              </select></div>
          </div>
         
          
         
         
           <div class="form-group" >
            <label  class="col-sm-2 control-label"><?php echo $entry_geo_zone; ?></label>
			<div class="col-sm-9"><select class="form-control" name="payfast_geo_zone_id">
                <option value="0"><?php echo $text_all_zones; ?></option>
                <?php foreach ($geo_zones as $geo_zone) { ?>
                <?php if ($geo_zone['geo_zone_id'] == $payfast_geo_zone_id) { ?>
                <option value="<?php echo $geo_zone['geo_zone_id']; ?>" selected="selected"><?php echo $geo_zone['name']; ?></option>
                <?php } else { ?>
                <option value="<?php echo $geo_zone['geo_zone_id']; ?>"><?php echo $geo_zone['name']; ?></option>
                <?php } ?>
                <?php } ?>
              </select></div>
          </div>
           <div class="form-group" >
            <label  class="col-sm-2 control-label"><?php echo $entry_status; ?></label>
			<div class="col-sm-9"><select class="form-control" name="payfast_status">
                <?php if ($payfast_status) { ?>
                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                <option value="0"><?php echo $text_disabled; ?></option>
                <?php } else { ?>
                <option value="1"><?php echo $text_enabled; ?></option>
                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                <?php } ?>
              </select></div>
          </div>
           <div class="form-group" >
            <label  class="col-sm-2 control-label"><?php echo $entry_sort_order; ?></label>
			<div class="col-sm-2"><input type="text" class="form-control"  name="payfast_sort_order" value="<?php echo $payfast_sort_order; ?>" size="1" /></div>
          </div>
        
      </form>
    </div>
  </div>
</section>
<?php echo $footer; ?> 