<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-paypal"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>
<section class="page-actions">

    <a onclick="$('#form').submit();" class="btn btn-primary">
        <i class="fa fa-plus"></i> <?php echo $button_save; ?>
    </a>
    <a href="<?php echo $cancel; ?>" class="btn btn-danger" onclick="$('#form').submit();">
        <i class="fa fa-times"></i> <?php echo $button_cancel; ?>
    </a>

</section>
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>
    <div class="box">

        <div class="content">

     
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form" class="form-horizontal">

                <div id="tab-settings">
                    <legend><?php echo $tab_settings; ?></legend>



                    <div class="form-group">
                        <label for="pp_pro_iframe_user" class="col-sm-2 control-label required"><?php echo $entry_user; ?></label>
                        <div class="col-sm-9">
                            <input type="text" name="pp_pro_iframe_user" class="form-control required" value="<?php echo $pp_pro_iframe_user; ?>" />
                            <?php if ($error_user) { ?>
                                <span class="error text-danger"><?php echo $error_user; ?></span>
                            <?php } ?>
                        </div>

                        <label class="col-sm-2 control-label ">

                        </label>
                    </div>
                    <div class="form-group">
                        <label for="pp_pro_iframe_password" class="col-sm-2 control-label required"><?php echo $entry_password; ?></label>
                        <div class="col-sm-9"><input class="form-control" type="text" name="pp_pro_iframe_password" value="<?php echo $pp_pro_iframe_password; ?>" />
                            <?php if ($error_password) { ?>
                                <span class="error text-danger"><?php echo $error_password; ?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pp_pro_iframe_sig" class="col-sm-2 control-label required"><?php echo $entry_sig; ?></label>
                        <div class="col-sm-9"><input class="form-control" type="text" name="pp_pro_iframe_sig" value="<?php echo $pp_pro_iframe_sig; ?>" />
                            <?php if ($error_sig) { ?>
                                <span class="error text-danger"><?php echo $error_sig; ?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pp_pro_iframe_transaction_method" class="col-sm-2 control-label "><?php echo $entry_transaction_method; ?></label>

                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_transaction_method">
                                <?php if ($pp_pro_iframe_transaction_method == 'authorization') { ?>
                                    <option value="sale"><?php echo $text_sale; ?></option>
                                    <option value="authorization" selected="selected"><?php echo $text_authorization; ?></option>
                                <?php } else { ?>
                                    <option value="sale" selected="selected"><?php echo $text_sale; ?></option>
                                    <option value="authorization"><?php echo $text_authorization; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_test; ?></label>
                        <div class="col-sm-9">
                            <?php if ($pp_pro_iframe_test) { ?>
                                <input type="radio" name="pp_pro_iframe_test" value="1" checked="checked" />
                                <?php echo $text_yes; ?>
                                <input type="radio" name="pp_pro_iframe_test" value="0" />
                                <?php echo $text_no; ?>
                            <?php } else { ?>
                                <input type="radio" name="pp_pro_iframe_test" value="1" />
                                <?php echo $text_yes; ?>
                                <input type="radio" name="pp_pro_iframe_test" value="0" checked="checked" />
                                <?php echo $text_no; ?>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_debug; ?><br /><span class="help"><?php echo $help_debug ?></span></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_debug">
                                <?php if ($pp_pro_iframe_debug) { ?>
                                    <option value="1" selected="selected"><?php echo $text_yes ?></option>
                                    <option value="0"><?php echo $text_no ?></option>
                                <?php } else { ?>
                                    <option value="1"><?php echo $text_yes ?></option>
                                    <option value="0" selected="selected"><?php echo $text_no ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_checkout_method ?><br /><span class="help"><?php echo $help_checkout_method ?></span></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_checkout_method">
                                <?php if ($pp_pro_iframe_checkout_method == 'iframe'): ?>

                                    <option value="iframe" selected="selected"><?php echo $text_iframe ?></option>
                                    <option value="redirect"><?php echo $text_redirect ?></option>

                                <?php else: ?>

                                    <option value="iframe"><?php echo $text_iframe ?></option>
                                    <option value="redirect" selected="selected"><?php echo $text_redirect ?></option>

                                <?php endif; ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_total; ?></label>
                        <div class="col-sm-9">
                            <input class="form-control" type="text" name="pp_pro_iframe_total" value="<?php echo $pp_pro_iframe_total; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_geo_zone; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_geo_zone_id">
                                <option value="0"><?php echo $text_all_zones; ?></option>
                                <?php foreach ($geo_zones as $geo_zone) { ?>
                                    <?php if ($geo_zone['geo_zone_id'] == $pp_pro_iframe_geo_zone_id) { ?>
                                        <option value="<?php echo $geo_zone['geo_zone_id']; ?>" selected="selected"><?php echo $geo_zone['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $geo_zone['geo_zone_id']; ?>"><?php echo $geo_zone['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_status">
                                <?php if ($pp_pro_iframe_status) { ?>
                                    <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                    <option value="0"><?php echo $text_disabled; ?></option>
                                <?php } else { ?>
                                    <option value="1"><?php echo $text_enabled; ?></option>
                                    <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_sort_order; ?></label>
                        <div class="col-sm-1">
                            <input class="form-control" type="text" name="pp_pro_iframe_sort_order" value="<?php echo $pp_pro_iframe_sort_order; ?>" size="1" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_ipn_url; ?></label>
                        <div class="col-sm-9"><span  class="form-control"><?php echo $ipn_url ?></span></div>
                    </div>
                </div>
                <div id="tab-order-status">
                    <legend><?php echo $tab_order_status; ?></legend>

                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_canceled_reversal_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_canceled_reversal_status_id">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $pp_pro_iframe_canceled_reversal_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_completed_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_completed_status_id">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $pp_pro_iframe_completed_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_denied_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_denied_status_id">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $pp_pro_iframe_denied_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_expired_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_expired_status_id">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $pp_pro_iframe_expired_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_failed_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_failed_status_id">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $pp_pro_iframe_failed_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_pending_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_pending_status_id">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $pp_pro_iframe_pending_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_processed_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_processed_status_id">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $pp_pro_iframe_processed_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_refunded_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_refunded_status_id">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $pp_pro_iframe_refunded_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_reversed_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_reversed_status_id">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $pp_pro_iframe_reversed_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label "><?php echo $entry_voided_status; ?></label>
                        <div class="col-sm-9">
                            <select class="form-control" name="pp_pro_iframe_voided_status_id">
                                <?php foreach ($order_statuses as $order_status) { ?>
                                    <?php if ($order_status['order_status_id'] == $pp_pro_iframe_voided_status_id) { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>" selected="selected"><?php echo $order_status['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $order_status['order_status_id']; ?>"><?php echo $order_status['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php echo $footer; ?>