<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>



    <div class="box">
        <form action="<?php echo $action; ?>" class="form-horizontal form-validate" method="post" enctype="multipart/form-data" id="form">
            <div class="box-body">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab-general" data-toggle="tab"><?php echo $tab_general; ?></a></li>  
                        <li><a href="#tab-data" data-toggle="tab"><?php echo $tab_data; ?></a></li>
                        <li><a href="#tab-design" data-toggle="tab"><?php echo $tab_design; ?></a></li>

                    </ul>
                </div>
                <div class="tab-content">

                    <div class="tab-pane active" id="tab-general" >

                        <?php if (count($languages) > 1): ?>
                            <div class="nav-tabs">

                                <ul class="nav nav-tabs">
                                    <?php $i = 0; ?>
                                    <?php foreach ($languages as $language) : ?>
                                        <li class="<?php echo ($i++ == 0) ? 'active' : ''; ?>"><a href="#tab-language-<?php echo $language['language_id']; ?>" data-toggle="tab"><?php echo $language['name']; ?></a></li>  
                                    <?php endforeach; ?>

                                </ul>
                            </div>
                        <?php endif; ?>
                        <div class="tab-content">
                            <?php $i = 0; ?>
                            <?php foreach ($languages as $language) : ?>
                                <div class="tab-pane<?php echo ($i == '0') ? ' active' : ''; ?>" id="tab-language-<?php echo $language['language_id']; ?>" >


                                    <div class="form-group <?php echo (isset($error_title[$language['language_id']])) ? 'has-error' : ''; ?>">
                                        <label for="information_description_<?php echo $i; ?>_name" class="col-sm-2 control-label required"><?php echo $entry_title; ?></label>
                                        <div class="col-sm-9">
                                            <input type="text" name="information_description[<?php echo $language['language_id']; ?>][title]" value="<?php echo isset($information_description[$language['language_id']]) ? $information_description[$language['language_id']]['title'] : ''; ?>" class="form-control required" id="information_description_<?php echo $i; ?>_name" />
                                            <?php if (isset($error_title[$language['language_id']])) { ?>
                                                <span class="error text-danger"><?php echo $error_title[$language['language_id']]; ?></span>
                                            <?php } ?>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="information_description_<?php echo $i; ?>_description" class="col-sm-2 control-label required"><?php echo $entry_description; ?></label>
                                        <div class="col-sm-9">
                                            <textarea id="information_description_<?php echo $i; ?>_description" class="form-control" name="information_description[<?php echo $language['language_id']; ?>][description]" cols="40" rows="5"><?php echo isset($information_description[$language['language_id']]) ? $information_description[$language['language_id']]['description'] : ''; ?></textarea>
                                        </div>
                                    </div>



                                </div>
                                <?php $i++; ?>
                            <?php endforeach; ?>
                        </div>

                    </div>
                    <div class="tab-pane" id="tab-data" >


                        <div class="form-group">
                            <label for="keyword" class="col-sm-2 control-label "><?php echo $entry_keyword; ?></label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" name="keyword" id="keyword" value="<?php echo $keyword; ?>"/>
                            </div><!-- /.input group -->
                        </div><!-- /.form group -->



                        <div class="form-group">
                            <label for="storeInput" class="col-sm-2 control-label "><?php echo $entry_store; ?></label>
                            <div class="col-sm-6">
                                <div class="scrollbox">
                                    <ul class="list-group">
                                        <?php $class = 'even'; ?>
                                        <ul class="list-group-item <?php echo $class; ?>">
                                            <?php if (in_array(0, $information_store)) { ?>
                                                <input type="checkbox" name="information_store[]" value="0" checked="checked" />
                                                <?php echo $text_default; ?>
                                            <?php } else { ?>
                                                <input type="checkbox" name="information_store[]" value="0" />
                                                <?php echo $text_default; ?>
                                            <?php } ?>
                                            </li>
                                            <?php foreach ($stores as $store) { ?>
                                                <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                                <li class="list-group-item <?php echo $class; ?>">
                                                    <?php if (in_array($store['store_id'], $information_store)) { ?>
                                                        <input type="checkbox" name="information_store[]" value="<?php echo $store['store_id']; ?>" checked="checked" />
                                                        <?php echo $store['name']; ?>
                                                    <?php } else { ?>
                                                        <input type="checkbox" name="information_store[]" value="<?php echo $store['store_id']; ?>" />
                                                        <?php echo $store['name']; ?>
                                                    <?php } ?>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                </div>

                            </div>

                        </div>
                        <div class="form-group">
                            <label for="bottom" class="col-sm-2 control-label"><?php echo $entry_bottom; ?></label>
                            <div class="col-sm-9">
                                <?php if ($bottom) { ?>
                                    <input type="checkbox" name="bottom" value="1" checked="checked" />
                                <?php } else { ?>
                                    <input type="checkbox" name="bottom" value="1" />
                                <?php } ?>  
                            </div><!-- /.input group -->
                        </div><!-- /.form group -->





                        <div class="form-group">
                            <label for="statusInput" class="col-sm-2 control-label "><?php echo $entry_status; ?></label>
                            <div class="col-sm-9">
                                <select name="status" id="statusInput" class="form-control">
                                    <?php if ($status) { ?>
                                        <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                        <option value="0"><?php echo $text_disabled; ?></option>
                                    <?php } else { ?>
                                        <option value="1"><?php echo $text_enabled; ?></option>
                                        <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="entry_deal_times" class="col-sm-2 control-label"><?php echo $entry_sort_order; ?></label>
                            <div class="col-sm-1">
                                <input type="number" min="0" class="form-control" name="sort_order" id="sort_order" value="<?php echo $sort_order; ?>"/>
                            </div><!-- /.input group -->
                        </div><!-- /.form group -->

                    </div>


                    <div class="tab-pane" id="tab-design" >
                        <table class="table table-bordered table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th class="left" style="width: 50%"><?php echo $entry_store; ?></th>
                                    <th class="left"><?php echo $entry_layout; ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="left" style="vertical-align:middle;"><?php echo $text_default; ?></td>
                                    <td class="left"><select name="information_layout[0][layout_id]" class="form-control">
                                            <option value=""></option>
                                            <?php foreach ($layouts as $layout) { ?>
                                                <?php if (isset($information_layout[0]) && $information_layout[0] == $layout['layout_id']) { ?>
                                                    <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select></td>
                                </tr>
                            </tbody>
                            <?php foreach ($stores as $store) { ?>
                                <tbody>
                                    <tr>
                                        <td class="left" style="vertical-align:middle;"><?php echo $store['name']; ?></td>
                                        <td class="left"><select class="form-control" name="information_layout[<?php echo $store['store_id']; ?>][layout_id]">
                                                <option value=""></option>
                                                <?php foreach ($layouts as $layout) { ?>
                                                    <?php if (isset($information_layout[$store['store_id']]) && $information_layout[$store['store_id']] == $layout['layout_id']) { ?>
                                                        <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                                                    <?php } else { ?>
                                                        <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                                                    <?php } ?>
                                                <?php } ?>
                                            </select></td>
                                    </tr>
                                </tbody>
                            <?php } ?>
                        </table>
                    </div>

                </div>
                <div class="box-footer">
                    <div id="form-error" class="alert alert-danger alert-dismissable">
                        <i class="fa fa-ban"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <span></span>
                    </div>
                    <button class="btn btn-primary">
                        <i class="fa fa-check"></i> <?php echo $button_save; ?>
                    </button>
                    <a href="<?php echo $cancel; ?>" class="btn" >
                        <i class="fa fa-times"></i> <?php echo $button_cancel; ?>
                    </a>
                </div>
        </form>
    </div>

</section><!-- /.content -->

<script src="view/theme/default/js/plugins/ckeditor/ckeditor.js" type="text/javascript"></script>

<script type="text/javascript">

    addOnready(function() {
        var EditorOps = {
            filebrowserBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
            filebrowserImageBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
            filebrowserFlashBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
            filebrowserUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
            filebrowserImageUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
            filebrowserFlashUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>'
        };
<?php $i = 0; ?>
<?php foreach ($languages as $language) : ?>
            CKEDITOR.replace('information_description_<?php echo $i; ?>_description', EditorOps);
    <?php $i++; ?>
<?php endforeach; ?>

    });
</script>

<?php echo $footer; ?>