<?php echo $header; ?>
<div class="page_container">
    <?php echo $column_left; ?>
    <?php echo $column_right; ?>
    <div id="content">
        <?php echo $content_top; ?>
        <div class="breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
            <?php } ?>
        </div>
        <?php if ($success) { ?>
            <div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><?php echo $success; ?></div>
        <?php } ?>
        <h1><?php echo $heading_title; ?></h1>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $text_my_account; ?></h3>
                    </div>
                    <div class="panel-body">
                        <ul class="list-group">
                            <li class="list-group-item"><a href="<?php echo $edit; ?>"><?php echo $text_edit; ?></a></li>
                            <li class="list-group-item"><a href="<?php echo $password; ?>"><?php echo $text_password; ?></a></li>
                            <li class="list-group-item"><a href="<?php echo $address; ?>"><?php echo $text_address; ?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $text_my_orders; ?></h3>
                    </div>
                    <div class="panel-body">
                        <ul class="list-group">
                            <li class="list-group-item"><a href="<?php echo $order; ?>"><?php echo $text_order; ?></a></li>
                            <li class="list-group-item"><a href="<?php echo $transaction; ?>"><?php echo $text_transaction; ?></a></li>
                            <li class="list-group-item"><a href="#todo">Your Coupons</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>


       

        <?php echo $content_bottom; ?></div>
</div>
<?php echo $footer; ?>