<?php echo $header; ?>
<div class="page_container">
    <?php echo $column_left; ?><?php echo $column_right; ?>
    <div id="content"><?php echo $content_top; ?>
        <div class="breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
            <?php } ?>
        </div>
        <h1><?php echo $heading_title; ?></h1>
        <form action="<?php echo $action; ?>" method="post" class="form-horizontal form-validate" enctype="multipart/form-data">
            <fieldset>
                <legend><?php echo $text_edit_address; ?></legend>
                <div class="content row">

                    <div class="form-group">
                        <label for="firstnameInput" class="control-label col-md-3 required"><?php echo $entry_firstname; ?></label>
                        <div class="col-md-9">
                            <input type="text" name="firstname" id="lastnameInput" value="<?php echo $firstname; ?>" class="form-control required" placeholder="<?php echo $entry_firstname; ?>" />
                            <?php if ($error_firstname) { ?>
                                <span class="error text-danger"><?php echo $error_firstname; ?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="lastnameInput" class="control-label col-md-3 required"><?php echo $entry_lastname; ?></label>
                        <div class="col-md-9">
                            <input type="text" name="lastname" id="lastnameInput" value="<?php echo $lastname; ?>" class="form-control required" placeholder="<?php echo $entry_lastname; ?>" />
                            <?php if ($error_lastname) { ?>
                                <span class="error text-danger"><?php echo $error_lastname; ?></span>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="companyInput" class="control-label col-md-3"><?php echo $entry_company; ?></label>
                        <div class="col-md-9">
                            <input type="text" name="company" id="companyInput" value="<?php echo $company; ?>" class="form-control " placeholder="<?php echo $entry_company; ?>" />

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="address_1Input" class="control-label col-md-3 required"><?php echo $entry_address_1; ?></label>
                        <div class="col-md-9">
                            <input type="text" name="address_1" id="address_1Input" value="<?php echo $address_1; ?>" class="form-control required" placeholder="<?php echo $entry_address_1; ?>" />
                            <?php if ($error_address_1) { ?>
                                <span class="error text-danger"><?php echo $error_address_1; ?></span>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="address_2Input" class="control-label col-md-3"><?php echo $entry_address_2; ?></label>
                        <div class="col-md-9">
                            <input type="text" name="address_2" id="address_2Input" value="<?php echo $address_2; ?>" class="form-control " placeholder="<?php echo $entry_address_2; ?>" />

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="cityInput" class="control-label col-md-3 required"><?php echo $entry_city; ?></label>
                        <div class="col-md-9">
                            <input type="text" name="city" id="cityInput" value="<?php echo $city; ?>" class="form-control required" placeholder="<?php echo $entry_city; ?>" />
                            <?php if ($error_city) { ?>
                                <span class="error text-danger"><?php echo $error_city; ?></span>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="postcodeInput" class="control-label col-md-3 required"><?php echo $entry_postcode; ?></label>
                        <div class="col-md-9">
                            <input type="text" name="postcode" id="postcodeInput" value="<?php echo $postcode; ?>" class="form-control required" placeholder="<?php echo $entry_postcode; ?>" />
                            <?php if ($error_postcode) { ?>
                                <span class="error text-danger"><?php echo $error_postcode; ?></span>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="country_idInput" class="control-label col-md-3 required"><?php echo $entry_country; ?></label>
                        <div class="col-md-9">
                            <select name="country_id" id="country_idInput" class="form-control required">
                                <option value=""><?php echo $text_select; ?></option>
                                <?php foreach ($countries as $country) { ?>
                                    <?php if ($country['country_id'] == $country_id) { ?>
                                        <option value="<?php echo $country['country_id']; ?>" selected="selected"><?php echo $country['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $country['country_id']; ?>"><?php echo $country['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>

                            <?php if ($error_country) { ?>
                                <span class="error text-danger"><?php echo $error_country; ?></span>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="zone_idInput" class="control-label col-md-3 required"><?php echo $entry_zone; ?></label>
                        <div class="col-md-9">
                            <select name="zone_id" id="zone_idInput" class="form-control required">

                            </select>

                            <?php if ($error_zone) { ?>
                                <span class="error text-danger"><?php echo $error_zone; ?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="defaultInputs" class="control-label col-md-3 required"><?php echo $entry_default; ?></label>
                        <div class="col-md-9">
                        

                            <?php if ($default) { ?>
                            
                            <div class="radio">
                                <label>
                                    <input type="radio" name="default" value="1" checked /> <?php echo $text_yes; ?>
                                </label>
                            </div>
                             <div class="radio">
                                <label>
                                    <input type="radio" name="default" value="0" /> <?php echo $text_no; ?>
                                </label>
                            </div>
                            
                            <?php } else { ?>
                                <div class="radio">
                                <label>
                                    <input type="radio" name="default" value="1" /> <?php echo $text_yes; ?>
                                </label>
                            </div>
                             <div class="radio">
                                <label>
                                    <input type="radio" name="default" value="0" checked /> <?php echo $text_no; ?>
                                </label>
                            </div>
                            <?php } ?>
                        </div>
                    </div>


                    <div class="form-group buttons">
                        <a href="<?php echo $back; ?>" class="btn btn-default"><?php echo $button_back; ?></a>
                        <button type="submit" class="btn btn-primary pull-right"><?php echo $button_continue; ?></button>

                    </div>
                </div>
            </fieldset>
        </form>




    </div>

    <?php echo $content_bottom; ?></div>
<script type="text/javascript"><!--
    addOnready(function() {
        $('select[name=\'country_id\']').bind('change', function() {
            $.ajax({
                url: 'index.php?route=account/address/country&country_id=' + this.value,
                dataType: 'json',
                beforeSend: function() {
                    $('select[name=\'country_id\']').after('<span class="wait">&nbsp;<img src="public/view/theme/default/image/loading.gif" alt="" /></span>');
                },
                complete: function() {
                    $('.wait').remove();
                },
                success: function(json) {
                    if (json['postcode_required'] == '1') {
                        $('#postcode-required').show();
                    } else {
                        $('#postcode-required').hide();
                    }

                    html = '<option value=""><?php echo $text_select; ?></option>';

                    if (json['zone'] != '') {
                        for (i = 0; i < json['zone'].length; i++) {
                            html += '<option value="' + json['zone'][i]['zone_id'] + '"';

                            if (json['zone'][i]['zone_id'] == '<?php echo $zone_id; ?>') {
                                html += ' selected="selected"';
                            }

                            html += '>' + json['zone'][i]['name'] + '</option>';
                        }
                    } else {
                        html += '<option value="0" selected="selected"><?php echo $text_none; ?></option>';
                    }

                    $('select[name=\'zone_id\']').html(html);
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        });

        $('select[name=\'country_id\']').trigger('change');
    });
//--></script> 

<?php echo $footer; ?>