<?php echo $header; ?>
<div class="page_container">
    <?php echo $column_left; ?>
    <?php echo $column_right; ?>
    <div id="content">
        <?php echo $content_top; ?>
        <div class="breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
            <?php } ?>
        </div>
        <?php if ($error_warning) { ?>
            <div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><?php echo $error_warning; ?></div>
        <?php } ?>
        <h1><?php echo $heading_title; ?></h1>

        <form action="<?php echo $action; ?>" method="post" class="form-horizontal form-validate" enctype="multipart/form-data">
            <fieldset>
                <legend><?php echo $text_your_details; ?></legend>
                <div class="content row">
                    <div class="form-group">
                        <label for="firstnameInput" class="control-label col-md-3 required"><?php echo $entry_firstname; ?></label>
                        <div class="col-md-9">
                            <input type="text" name="firstname" id="firstnameInput" value="<?php echo $firstname; ?>" class="form-control required" placeholder="<?php echo $entry_firstname; ?>" />
                            <?php if ($error_firstname) { ?>
                                <span class="error text-danger"><?php echo $error_firstname; ?></span>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="lastnameInput" class="control-label col-md-3 required"><?php echo $entry_lastname; ?></label>
                        <div class="col-md-9">
                            <input type="text" name="lastname" id="lastnameInput" value="<?php echo $lastname; ?>" class="form-control required" placeholder="<?php echo $entry_lastname; ?>" />
                            <?php if ($error_lastname) { ?>
                                <span class="error text-danger"><?php echo $error_lastname; ?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="emailInput" class="control-label col-md-3 required"><?php echo $entry_email; ?></label>
                        <div class="col-md-9">
                            <input type="email" name="email" id="emailInput" value="<?php echo $email; ?>" class="form-control required" placeholder="<?php echo $entry_email; ?>" />
                            <?php if ($error_email) { ?>
                                <span class="error text-danger"><?php echo $error_email; ?></span>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="telephoneInput" class="control-label col-md-3 required"><?php echo $entry_telephone; ?></label>
                        <div class="col-md-9">
                            <input type="text" name="telephone" id="telephoneInput" value="<?php echo $telephone; ?>" class="form-control required" placeholder="<?php echo $entry_telephone; ?>" />
                            <?php if ($error_telephone) { ?>
                                <span class="error text-danger"><?php echo $error_telephone; ?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group buttons">
                        <div class="col-md-offset-3 col-md9">
                            <a href="<?php echo $back; ?>" class="btn btn-default"><?php echo $button_back; ?></a>
                            <button type="submit" class="btn btn-default"><?php echo $button_continue; ?></button>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
        <?php echo $content_bottom; ?>
    </div>
</div>
    <?php echo $footer; ?>