<?php echo $header; ?>
<div class="container">
    <?php echo $column_left; ?>
    <?php echo $column_right; ?>
    <div id="content">
        <?php echo $content_top; ?>
        <div class="breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
            <?php } ?>
        </div>
        <?php if ($success) { ?>
            <div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><?php echo $success; ?></div>
        <?php } ?>
        <?php if ($error_warning) { ?>
            <div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><?php echo $error_warning; ?></div>
        <?php } ?>
        <h1><?php echo $heading_title; ?></h1>
        <div class="login-content row">
            <div class="col-md-6 left">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $text_new_customer; ?></h3>
                    </div>
                    <div class="panel-body">
                        <p><b><?php echo $text_register; ?></b></p>
                        <p><?php echo $text_register_account; ?></p>
                        <a href="<?php echo $register; ?>" class="btn btn-primary"><?php echo $button_continue; ?></a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $text_returning_customer; ?></h3>
                    </div>
                    <div class="panel-body">
                        <p><?php echo $text_i_am_returning_customer; ?></p>
                        <form action="<?php echo $action; ?>" class="form-horizontal" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="inputEmailLogin" class="col-sm-3 control-label"><?php echo $entry_email; ?></label>
                                <div class="col-sm-9">
                                    <input name="email" type="email" class="form-control" id="inputEmailLogin" placeholder="Email" value="<?php echo $email; ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPasswordLogin" class="col-sm-3 control-label"><?php echo $entry_password; ?></label>
                                <div class="col-sm-9">
                                    <input name="password" type="password" class="form-control" id="inputPasswordLogin" placeholder="Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-9">
                                    <a href="<?php echo $forgotten; ?>"><?php echo $text_forgotten; ?></a>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="text-right col-sm-12">
                                    <button type="submit" class="btn btn-primary right"><?php echo $button_login; ?></button>
                                </div>
                            </div>
                            <?php if ($redirect) { ?>
                                <input type="hidden" name="redirect" value="<?php echo $redirect; ?>" />
                            <?php } ?>
                        </form>
                    </div>
                </div>

            </div>
        </div>

        <?php echo $content_bottom; ?></div>
</div>
<?php echo $footer; ?>