<?php echo $header; ?>
<div class="page_container">

    <?php echo $column_left; ?><?php echo $column_right; ?>


    <div id="content"><?php echo $content_top; ?>
        <div class="breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
            <?php } ?>
        </div>
        <h1><?php echo $heading_title; ?></h1>

        <div class="content">
            <div class="row">
                <div class="col-md-12">
                    <legend><?php echo $text_order_detail; ?>
                        <span class="pull-right"><?php if ($invoice_no) { ?>
                                <b><?php echo $text_invoice_no; ?></b> <?php echo $invoice_no; ?>
                            <?php } ?></span>
                    </legend>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <b><?php echo $text_order_id; ?></b> #<?php echo $order_id; ?>
                </div>
                <div class="col-md-4">
                    <b><?php echo $text_date_added; ?></b> <?php echo $date_added; ?>
                </div>
                <div class="col-md-4">
                    <?php if ($payment_method) { ?>
                        <b><?php echo $text_payment_method; ?></b> <?php echo $payment_method; ?>
                    <?php } ?>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <legend><?php echo $text_payment_address; ?></legend>

                    <?php echo $payment_address; ?>

                </div>
                <div class="col-md-6">
                    <?php if ($shipping_address) { ?>
                        <legend><?php echo $text_shipping_address; ?></legend>
                        <?php echo $shipping_address; ?>
                    <?php } ?>
                </div>
            </div>
            <hr />
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th class="left"><?php echo $column_name; ?></th>
                        <th class="left"><?php echo $column_model; ?></th>
                        <th class="text-left"><?php echo $column_quantity; ?></th>
                        <th class="text-left"><?php echo $column_delivery; ?></th>
                        <th class="text-right"><?php echo $column_price; ?></th>
                        <th class="text-right"><?php echo $column_total; ?></th>
                        <?php if ($products) { ?>
                            <th style="width: 1px;"></th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($products as $product) { ?>
                        <tr>
                            <td class="left"><?php echo $product['name']; ?></td>
                            <td class="left"><?php echo $product['option']; ?></td>
                            <td class="text-center"><?php echo $product['quantity']; ?></td>

                            <td class="text-left">
                                <?php if ($product['is_coupon']): ?>
                                    <a href="<?php echo $product['is_coupon']; ?>" class="btn btn-primary"><?php echo $button_coupon; ?></button>
                                    <?php elseif ($product['is_collect']): ?>
                                        <?php echo $text_collect; ?>
                                    <?php else: ?>
                                        <?php echo $product['shipping_method']['title']; ?>
                                    <?php endif; ?>
                            </td>
                            <td class="text-right"><?php echo $product['price']; ?></td>
                            <td class="text-right"><?php echo $product['total']; ?></td>
                            <td class="right"></td>
                        </tr>
                    <?php } ?>
                    <?php foreach ($vouchers as $voucher) { ?>
                        <tr>
                            <td class="left"><?php echo $voucher['description']; ?></td>
                            <td class="left"></td>
                            <td class="right">1</td>
                            <td ></td>
                            <td class="text-right"><?php echo $voucher['amount']; ?></td>

                            <td class="text-right"><?php echo $voucher['amount']; ?></td>
                            <?php if ($products) { ?>
                                <td></td>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                </tbody>
                <tfoot>
                    <?php foreach ($totals as $total) { ?>
                        <tr>
                            <td colspan="4"></td>
                            <td class="text-right"><b><?php echo $total['title']; ?>:</b></td>
                            <td class="text-right"><?php echo $total['text']; ?></td>
                            <?php if ($products) { ?>
                                <td></td>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                </tfoot>
            </table>
            <?php if ($comment) { ?>
                <div >
                    <legend><?php echo $text_comment; ?></legend>
                    <?php echo $comment; ?>
                </div>
            <?php } ?>
            <?php if ($histories) { ?>
                <h2><?php echo $text_history; ?></h2>
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th class="left"><?php echo $column_date_added; ?></th>
                            <th class="left"><?php echo $column_status; ?></th>
                            <th class="left"><?php echo $column_comment; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($histories as $history) { ?>
                            <tr>
                                <td class="left"><?php echo $history['date_added']; ?></td>
                                <td class="left"><?php echo $history['status']; ?></td>
                                <td class="left"><?php echo $history['comment']; ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            <?php } ?>

        </div>
        <div class="clearfix buttons">
            <a href="<?php echo $continue; ?>" class="btn btn-primary pull-right"><?php echo $button_continue; ?></a>

        </div>

    </div>

    <?php echo $content_bottom; ?></div>
<?php echo $footer; ?>