<?php echo $header; ?>
<div class="page_container">
    <?php echo $column_left; ?>
    <?php echo $column_right; ?>
    <div id="content">
        <?php echo $content_top; ?>
        <div class="breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
            <?php } ?>
        </div>

        <h1><?php echo $heading_title; ?></h1>



        <form action="<?php echo $action; ?>" method="post" class="form-horizontal form-validate" enctype="multipart/form-data">
            <fieldset>
                <legend><?php echo $text_password; ?></legend>
                <div class="content row">
                    <div class="form-group">
                        <label for="passwordInput" class="control-label col-md-3 required"><?php echo $entry_password; ?></label>
                        <div class="col-md-9">
                            <input type="password" name="password" id="passwordInput" value="" class="form-control required" placeholder="<?php echo $entry_password; ?>" />
                            <?php if ($error_password) { ?>
                                <span class="error text-danger"><?php echo $error_password; ?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="confirmInput" class="control-label col-md-3 required"><?php echo $entry_confirm; ?></label>
                        <div class="col-md-9">
                            <input type="password" name="confirm" id="confirmInput" value="" class="form-control required" placeholder="<?php echo $entry_confirm; ?>" />
                            <?php if ($error_confirm) { ?>
                                <span class="error text-danger"><?php echo $error_confirm; ?></span>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="form-group buttons">
                        <div class="col-md-offset-3 col-md9">
                            <a href="<?php echo $back; ?>" class="btn btn-default"><?php echo $button_back; ?></a>
                            <button type="submit" class="btn btn-primary"><?php echo $button_continue; ?></button>
                        </div>
                    </div>

                </div>
            </fieldset>
        </form>
        <?php echo $content_bottom; ?>
    </div>
</div>
    <?php echo $footer; ?>