<?php echo $header; ?>
<div class="page_container">
    <?php echo $column_left; ?>
    <?php echo $column_right; ?>
    <div id="content">
        <?php echo $content_top; ?>
        <div class="breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
            <?php } ?>
        </div>
        <?php if ($error_warning) { ?>
            <div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><?php echo $error_warning; ?></div>
        <?php } ?>
        <h1><?php echo $heading_title; ?></h1>
        <p><?php echo $text_account_already; ?></p>
        <form action="<?php echo $action; ?>" method="post" class="form-horizontal form-validate" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6 left">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $text_your_details; ?></h3>
                        </div>
                        <div class="panel-body">

                            <div class="form-group">
                                <label for="firstnameInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_firstname; ?></label>
                                <div class="col-sm-9 col-md-8">
                                    <input type="text" name="firstname" id="firstnameInput" value="<?php echo $firstname; ?>" class="form-control required" placeholder="<?php echo $entry_firstname; ?>" />
                                    <?php if ($error_firstname) { ?>
                                        <span class="error text-danger"><?php echo $error_firstname; ?></span>
                                    <?php } ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="lastnameInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_lastname; ?></label>
                                <div class="col-sm-9 col-md-8">
                                    <input type="text" name="lastname" id="lastnameInput" value="<?php echo $lastname; ?>" class="form-control required" placeholder="<?php echo $entry_lastname; ?>" />
                                    <?php if ($error_lastname) { ?>
                                        <span class="error text-danger"><?php echo $error_lastname; ?></span>
                                    <?php } ?>
                                </div>
                            </div>



                            <div class="form-group">
                                <label for="telephoneInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_telephone; ?></label>
                                <div class="col-sm-9 col-md-8">
                                    <input type="text" name="telephone" id="telephoneInput" value="<?php echo $telephone; ?>" class="form-control required" placeholder="<?php echo $entry_telephone; ?>" />
                                    <?php if ($error_telephone) { ?>
                                        <span class="error text-danger"><?php echo $error_telephone; ?></span>
                                    <?php } ?>
                                </div>
                            </div>




                        </div>
                    </div>
                </div>

                <div class="col-md-6 right">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $text_your_password; ?></h3>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="emailInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_email; ?></label>
                                <div class="col-sm-9 col-md-8">
                                    <input type="email" name="email" id="emailInput" value="<?php echo $email; ?>" class="form-control required" placeholder="<?php echo $entry_email; ?>" />
                                    <?php if ($error_email) { ?>
                                        <span class="error text-danger"><?php echo $error_email; ?></span>
                                    <?php } ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="passwordInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_password; ?></label>
                                <div class="col-sm-9 col-md-8">
                                    <input type="password" name="password" id="passwordInput" value="<?php echo $password; ?>" class="form-control required" placeholder="<?php echo $entry_password; ?>" />
                                    <?php if ($error_password) { ?>
                                        <span class="error text-danger"><?php echo $error_password; ?></span>
                                    <?php } ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="confirmInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_confirm; ?></label>
                                <div class="col-sm-9 col-md-8">
                                    <input type="password" name="confirm" id="confirmInput" value="<?php echo $confirm; ?>" class="form-control required" placeholder="<?php echo $entry_confirm; ?>" />
                                    <?php if ($error_confirm) { ?>
                                        <span class="error text-danger"><?php echo $error_confirm; ?></span>
                                    <?php } ?>
                                </div>
                            </div>




                        </div>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $text_your_address; ?></h3>
                        </div>
                        <div class="panel-body">




                            <div class="col-md-6">

                                <div class="form-group">
                                    <label for="companyInput" class="control-label col-sm-3 col-md-4"><?php echo $entry_company; ?></label>
                                    <div class="col-sm-9 col-md-8">
                                        <input type="text" name="company" id="companyInput" value="<?php echo $company; ?>" class="form-control " placeholder="<?php echo $entry_company; ?>" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="addressInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_address_1; ?></label>
                                    <div class="col-sm-9 col-md-8">
                                        <input type="text" name="address_1" id="addressInput" value="<?php echo $address_1; ?>" class="form-control required" placeholder="<?php echo $entry_address_1; ?>" />
                                        <?php if ($error_address_1) { ?>
                                            <span class="error text-danger"><?php echo $error_address_1; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="address2Input" class="control-label col-sm-3 col-md-4"><?php echo $entry_address_2; ?></label>
                                    <div class="col-sm-9 col-md-8">
                                        <input type="text" name="address_2" id="address2Input" value="<?php echo $address_2; ?>" class="form-control " placeholder="<?php echo $entry_address_2; ?>" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="cityInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_city; ?></label>
                                    <div class="col-sm-9 col-md-8">
                                        <input type="text" name="city" id="cityInput" value="<?php echo $city; ?>" class="form-control required" placeholder="<?php echo $entry_city; ?>" />
                                        <?php if ($error_city) { ?>
                                            <span class="error text-danger"><?php echo $error_city; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>





                            </div>

                            <div class="col-md-6">



                                <div class="form-group">
                                    <label for="countryInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_country; ?></label>
                                    <div class="col-sm-9 col-md-8">
                                        <select name="country_id" id="countryInput" class="form-control required" >
                                            <option value=""><?php echo $text_select; ?></option>
                                            <?php foreach ($countries as $country) { ?>
                                                <?php if ($country['country_id'] == $country_id) { ?>
                                                    <option value="<?php echo $country['country_id']; ?>" selected="selected"><?php echo $country['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $country['country_id']; ?>"><?php echo $country['name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select>
                                        <?php if ($error_country) { ?>
                                            <span class="error text-danger"><?php echo $error_country; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="zoneInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_zone; ?></label>
                                    <div class="col-sm-9 col-md-8">
                                        <select name="zone_id" id="zoneInput" class="form-control required">
                                        </select>
                                        <?php if ($error_zone) { ?>
                                            <span class="error text-danger"><?php echo $error_zone; ?></span>
                                        <?php } ?></div>
                                </div>

                                <div class="form-group">
                                    <label for="postcodeInput" class="control-label col-sm-3 col-md-4 required"><?php echo $entry_postcode; ?></label>
                                    <div class="col-sm-9 col-md-8">
                                        <input type="text" name="postcode" id="postcodeInput" value="<?php echo $postcode; ?>" class="form-control required" placeholder="<?php echo $entry_postcode; ?>" />
                                        <?php if ($error_postcode) { ?>
                                            <span class="error text-danger"><?php echo $error_postcode; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>


                            </div>


                        </div>

                    </div>
                </div>

                <div class="col-md-12">
                    <div class="panel panel-default">

                        <div class="panel-body">
                            <div class="form-group" >
                                <label for="newsletterInput" class="control-label col-sm-3 col-md-3"><?php echo $entry_newsletter; ?></label>
                                <div class="col-sm-9 col-md-8">

                                    <?php if ($newsletter) { ?>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="newsletter" value="1" checked="checked" />
                                                <?php echo $text_yes; ?> 
                                            </label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="newsletter" value="0" />
                                                <?php echo $text_no; ?>
                                            </label>
                                        </div>
                                    <?php } else { ?>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="newsletter" value="1" />
                                                <?php echo $text_yes; ?>
                                            </label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="newsletter" value="0" checked="checked" />
                                                <?php echo $text_no; ?>
                                            </label>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>




                        </div>
                        <div class="panel-footer">
                            <div class="row">
                                <?php if ($text_agree) : ?>
                                    <div class="col-sm-9 col-md-8">

                                        <div class="checkbox">
                                            <label>
                                                <?php if ($agree) { ?>
                                                    <input type="checkbox" name="agree" value="1" checked="checked" />
                                                <?php } else { ?>
                                                    <input type="checkbox" name="agree" value="1" />
                                                <?php } ?>
                                                <?php echo $text_agree; ?>
                                            </label>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <div class="col-sm-3 col-md-4 pull-right">
                                    <input type="submit" value="<?php echo $button_continue; ?>" class="btn btn-primary pull-right" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <?php echo $content_bottom; ?></div>
</div>

<script type="text/javascript"><!--
    addOnready(function() {


        $('#countryInput').on('change', function() {
            $.ajax({
                url: 'index.php?route=account/register/country&country_id=' + this.value,
                dataType: 'json',
                beforeSend: function() {
                    $('select[name=\'country_id\']').after('<span class="wait">&nbsp;<img src="public/view/theme/default/image/loading.gif" alt="" /></span>');
                },
                complete: function() {
                    $('.wait').remove();
                },
                success: function(json) {
                    if (json['postcode_required'] == '1') {
                        $('#postcode-required').show();
                    } else {
                        $('#postcode-required').hide();
                    }

                    html = '<option value=""><?php echo $text_select; ?></option>';

                    if (json['zone'] != '') {
                        for (i = 0; i < json['zone'].length; i++) {
                            html += '<option value="' + json['zone'][i]['zone_id'] + '"';

                            if (json['zone'][i]['zone_id'] == '<?php echo $zone_id; ?>') {
                                html += ' selected="selected"';
                            }

                            html += '>' + json['zone'][i]['name'] + '</option>';
                        }
                    } else {
                        html += '<option value="0" selected="selected"><?php echo $text_none; ?></option>';
                    }

                    $('select[name=\'zone_id\']').html(html);
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        });

        $('#countryInput').trigger('change');
        
        $('.colorbox').colorbox({width:'95%', height:'95%'});

    });
//--></script> 

<?php echo $footer; ?>