<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>


<!-- Main content -->
<section class="content">
    <?php if ($error) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error; ?>
        </div>
    <?php } ?>
    <?php if ($success) { ?>
        <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $success; ?>
        </div>
    <?php } ?>
    <div id="form-error" class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <span></span>
    </div>

    <div class="box">
        <table class="table table-bordered table-striped table-responsive">
            <thead>
                <tr>
                <tr>
                    <th class="left"><?php echo $column_name; ?></th>
                    <th></th>
                    <th class="left"><?php echo $column_status; ?></th>
                    <th class="right"><?php echo $column_sort_order; ?></th>
                    <th class="right"><?php echo $column_action; ?></th>
                </tr>

                </tr>
            </thead>
            <tbody>
                <?php if ($extensions) { ?>
                    <?php foreach ($extensions as $extension) { ?>
                        <tr>
                            <td class="left"><?php echo $extension['name']; ?></td>
                            <td class="center"><?php echo $extension['link'] ?></td>
                            <td class="left"><?php echo $extension['status'] ?></td>
                            <td class="right"><?php echo $extension['sort_order']; ?></td>
                            <td class="right"><?php foreach ($extension['action'] as $action) { ?>
                                    [ <a href="<?php echo $action['href']; ?>"><?php echo $action['text']; ?></a> ]
                                <?php } ?></td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td class="center" colspan="8"><div class="alert alert-info"><?php echo $text_no_results; ?></div></td>
                    </tr>
                <?php } ?>
            </tbody>

        </table>

    </div>

</section><!-- /.content -->

<?php echo $footer; ?>