<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>



    <div class="box">
        <form action="<?php echo $action; ?>" class="form-horizontal form-validate" method="post" enctype="multipart/form-data" id="form">
            <div class="box-body">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab-general" data-toggle="tab"><?php echo $tab_general; ?></a></li>  
                        <li><a href="#tab-data" data-toggle="tab"><?php echo $tab_data; ?></a></li>
                        <li><a href="#tab-design" data-toggle="tab"><?php echo $tab_design; ?></a></li>

                    </ul>
                </div>
                <div class="tab-content">

                    <div class="tab-pane active" id="tab-general" >

                        <?php if (count($languages) > 1): ?>
                            <div class="nav-tabs">

                                <ul class="nav nav-tabs">
                                    <?php $i = 0; ?>
                                    <?php foreach ($languages as $language) : ?>
                                        <li class="<?php echo ($i++ == 0) ? 'active' : ''; ?>"><a href="#tab-language-<?php echo $language['language_id']; ?>" data-toggle="tab"><?php echo $language['name']; ?></a></li>  
                                    <?php endforeach; ?>

                                </ul>
                            </div>
                        <?php endif; ?>
                        <div class="tab-content">
                            <?php $i = 0; ?>
                            <?php foreach ($languages as $language) : ?>
                                <div class="tab-pane<?php echo ($i == '0') ? ' active' : ''; ?>" id="tab-language-<?php echo $language['language_id']; ?>" >

                                    <div class="form-group <?php echo (isset($error_name[$language['language_id']])) ? 'has-error' : ''; ?>">
                                        <label for="category_description_<?php echo $i; ?>_name" class="col-sm-2 control-label required"><?php echo $entry_name; ?></label>
                                        <div class="col-sm-9">
                                            <input type="text" name="category_description[<?php echo $language['language_id']; ?>][name]" value="<?php echo isset($category_description[$language['language_id']]) ? $category_description[$language['language_id']]['name'] : ''; ?>" class="form-control required" id="category_description_<?php echo $i; ?>_name" />
                                            <?php if (isset($error_name[$language['language_id']])) { ?>
                                                <span class="error text-danger"><?php echo $error_name[$language['language_id']]; ?></span>
                                            <?php } ?>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="category_description_<?php echo $i; ?>_meta_desc" class="col-sm-2 control-label"><?php echo $entry_meta_keyword; ?></label>
                                        <div class="col-sm-9">
                                            <textarea id="category_description_<?php echo $i; ?>_meta_desc" class="form-control" name="category_description[<?php echo $language['language_id']; ?>][meta_description]" cols="40" rows="5"><?php echo isset($category_description[$language['language_id']]) ? $category_description[$language['language_id']]['meta_description'] : ''; ?></textarea>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="category_description_<?php echo $i; ?>_meta_keyw" class="col-sm-2 control-label"><?php echo $entry_meta_description; ?></label>
                                        <div class="col-sm-9">
                                            <textarea id="category_description_<?php echo $i; ?>_meta_keyw" class="form-control" name="category_description[<?php echo $language['language_id']; ?>][meta_keyword]" cols="40" rows="5"><?php echo isset($category_description[$language['language_id']]) ? $category_description[$language['language_id']]['meta_keyword'] : ''; ?></textarea>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="category_description_<?php echo $i; ?>_description" class="col-sm-2 control-label"><?php echo $entry_description; ?></label>
                                        <div class="col-sm-9">
                                            <textarea id="category_description_<?php echo $i; ?>_description" class="form-control" name="category_description[<?php echo $language['language_id']; ?>][description]" cols="40" rows="5"><?php echo isset($category_description[$language['language_id']]) ? $category_description[$language['language_id']]['description'] : ''; ?></textarea>
                                        </div>
                                    </div>
                                </div>
                                <?php $i++; ?>
                            <?php endforeach; ?>
                        </div>

                    </div>
                    <div class="tab-pane" id="tab-data" >
                        <div class="form-group">
                            <label for="entry_parent" class="col-sm-2 control-label"><?php echo $entry_parent; ?></label>
                            <div class="col-sm-9">
                                <input id='entry_parent' type="text" class="form-control" name="path" value="<?php echo $path; ?>" size="100" />
                                <input type="hidden" name="parent_id" value="<?php echo $parent_id; ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="keyword" class="col-sm-2 control-label"><?php echo $entry_keyword; ?></label>
                            <div class="col-sm-9">
                                <input id='keyword' type="text" name="keyword" value="<?php echo $keyword; ?>" class="form-control"/>
                                <?php if ($error_duplicate_seo) { ?>
                                    <span class="error text-danger"><?php echo $error_duplicate_seo; ?></span>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="imageInput" class="col-sm-2 control-label "><?php echo $entry_image; ?></label>
                            <div class="col-sm-9">
                                <div class="image">
                                    <img src="<?php echo $thumb; ?>" alt="" id="thumb" />
                                    <input type="hidden" name="image" value="<?php echo $image; ?>" id="image" /><br />
                                    <button type="button" class="btn btn-primary btn-sm" onclick="image_upload('image', 'thumb');"><?php echo $text_browse; ?></button>
                                    <button type="button" class="btn btn-danger btn-sm" onclick="$('#thumb').attr('src', '<?php echo $no_image; ?>');
                                            $('#image').attr('value', '');"><?php echo $text_clear; ?></button>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="storeInput" class="col-sm-2 control-label "><?php echo $entry_store; ?></label>
                            <div class="col-sm-6">
                                <div class="scrollbox">
                                    <ul class="list-group">
                                        <?php $class = 'even'; ?>
                                        <ul class="list-group-item <?php echo $class; ?>">
                                            <?php if (in_array(0, $category_store)) { ?>
                                                <input type="checkbox" name="category_store[]" value="0" checked="checked" />
                                                <?php echo $text_default; ?>
                                            <?php } else { ?>
                                                <input type="checkbox" name="category_store[]" value="0" />
                                                <?php echo $text_default; ?>
                                            <?php } ?>
                                            </li>
                                            <?php foreach ($stores as $store) { ?>
                                                <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                                <li class="list-group-item <?php echo $class; ?>">
                                                    <?php if (in_array($store['store_id'], $category_store)) { ?>
                                                        <input type="checkbox" name="category_store[]" value="<?php echo $store['store_id']; ?>" checked="checked" />
                                                        <?php echo $store['name']; ?>
                                                    <?php } else { ?>
                                                        <input type="checkbox" name="category_store[]" value="<?php echo $store['store_id']; ?>" />
                                                        <?php echo $store['name']; ?>
                                                    <?php } ?>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                </div>

                            </div>

                        </div>




                        <div class="form-group">
                            <label for="statusInput" class="col-sm-2 control-label "><?php echo $entry_status; ?></label>
                            <div class="col-sm-9">
                                <select name="status" id="statusInput" class="form-control">
                                    <?php if ($status) { ?>
                                        <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                        <option value="0"><?php echo $text_disabled; ?></option>
                                    <?php } else { ?>
                                        <option value="1"><?php echo $text_enabled; ?></option>
                                        <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                    </div>

                    <div class="tab-pane" id="tab-design" >
                        <table class="table table-bordered table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th class="left" style="width: 50%"><?php echo $entry_store; ?></th>
                                    <th class="left"><?php echo $entry_layout; ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="left" style="vertical-align:middle;"><?php echo $text_default; ?></td>
                                    <td class="left"><select name="category_layout[0][layout_id]" class="form-control">
                                            <option value=""></option>
                                            <?php foreach ($layouts as $layout) { ?>
                                                <?php if (isset($category_layout[0]) && $category_layout[0] == $layout['layout_id']) { ?>
                                                    <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                                                <?php } ?>
                                            <?php } ?>
                                        </select></td>
                                </tr>
                            </tbody>
                            <?php foreach ($stores as $store) { ?>
                                <tbody>
                                    <tr>
                                        <td class="left" style="vertical-align:middle;"><?php echo $store['name']; ?></td>
                                        <td class="left"><select class="form-control" name="category_layout[<?php echo $store['store_id']; ?>][layout_id]">
                                                <option value=""></option>
                                                <?php foreach ($layouts as $layout) { ?>
                                                    <?php if (isset($category_layout[$store['store_id']]) && $category_layout[$store['store_id']] == $layout['layout_id']) { ?>
                                                        <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                                                    <?php } else { ?>
                                                        <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                                                    <?php } ?>
                                                <?php } ?>
                                            </select></td>
                                    </tr>
                                </tbody>
                            <?php } ?>
                        </table>
                    </div>

                </div>
                <div class="box-footer">
                    <div id="form-error" class="alert alert-danger alert-dismissable">
                        <i class="fa fa-ban"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <span></span>
                    </div>
                    <button class="btn btn-primary">
                        <i class="fa fa-check"></i> <?php echo $button_save; ?>
                    </button>
                    <a href="<?php echo $cancel; ?>" class="btn" onclick="$('#form').submit();">
                        <i class="fa fa-times"></i> <?php echo $button_cancel; ?>
                    </a>
                </div>
        </form>
    </div>

</section><!-- /.content -->

<script src="view/theme/default/js/plugins/ckeditor/ckeditor.js" type="text/javascript"></script>

<script type="text/javascript">



                        addOnready(function() {

                            $('#category_description_0_name').on('keyup', function() {
                                var inputname = $(this).val();
                                inputname = inputname.replace(/[^A-Za-z0-9\s]+/g, '');
                                $('#keyword').val("cat-" + inputname.replace(/\s+/g, '-').toLowerCase());
                            });

<?php $i = 0; ?>
<?php foreach ($languages as $language) : ?>
                                CKEDITOR.replace('category_description_<?php echo $i++; ?>_description', {
                                    filebrowserBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                    filebrowserImageBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                    filebrowserFlashBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                    filebrowserUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                    filebrowserImageUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                    filebrowserFlashUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>'
                                });
<?php endforeach; ?>

                            $('input[name=\'path\']').autocomplete({
                                delay: 500,
                                source: function(request, response) {
                                    $.ajax({
                                        url: 'index.php?route=deal/category/autocomplete&token=<?php echo $token; ?>&filter_name=' + encodeURIComponent(request.term),
                                        dataType: 'json',
                                        success: function(json) {
                                            json.unshift({
                                                'category_id': 0,
                                                'name': '<?php echo $text_none; ?>'
                                            });

                                            response($.map(json, function(item) {
                                                return {
                                                    label: item.name,
                                                    value: item.category_id
                                                }
                                            }));
                                        }
                                    });
                                },
                                select: function(event, ui) {
                                    $('input[name=\'path\']').val(ui.item.label);
                                    $('input[name=\'parent_id\']').val(ui.item.value);

                                    return false;
                                },
                                focus: function(event, ui) {
                                    return false;
                                }
                            });

                        });
</script>

<?php echo $footer; ?>