<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>


<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>



    <div class="box">
        <form action="<?php echo $action; ?>" class="form-horizontal form-validate" method="post" enctype="multipart/form-data" id="form">
            <div class="box-body">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab-profile" data-toggle="tab"><?php echo $tab_profile; ?></a></li>  
                        <li><a href="#tab-location" data-toggle="tab"><?php echo $tab_location; ?></a></li>
                       <!-- <li><a href="#tab-staff" data-toggle="tab"><?php echo $tab_staff; ?></a></li> -->

                    </ul>
                </div>
                <div class="tab-content">

                    <div class="tab-pane active" id="tab-profile" >
                        <div class="form-group <?php echo ($error_name) ? 'has-error' : ''; ?>">
                            <label for="nameInput" class="col-sm-2 control-label required"><?php echo $entry_company; ?></label>
                            <div class="col-sm-9">
                                <input type="text" name="name" value="<?php echo $name; ?>" class="form-control required" id="nameInput" />
                                <?php if ($error_name) { ?>
                                    <span class="error text-danger"><?php echo $error_name; ?></span>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="websiteInput" class="col-sm-2 control-label "><?php echo $entry_website; ?></label>
                            <div class="col-sm-9">
                                <input type="url" name="website" value="<?php echo $website; ?>" class="form-control " id="websiteInput" />

                            </div>
                        </div>

                        <div class="form-group <?php echo ($error_commission) ? 'has-error' : ''; ?>">
                            <label for="commissionInput" class="col-sm-2 control-label "><?php echo $entry_commission; ?></label>
                            <div class="col-sm-9">
                                <input type="text" name="commission" value="<?php echo $commission; ?>" class="form-control number " id="commissionInput" />
                                <?php if ($error_commission) { ?>
                                    <span class="error text-danger"><?php echo $error_commission; ?></span>
                                <?php } ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="aboutInput" class="col-sm-2 control-label "><?php echo $entry_about; ?></label>
                            <div class="col-sm-9">
                                <textarea name="about" id="aboutInput" class="form-control"><?php echo $about; ?></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="imageInput" class="col-sm-2 control-label "><?php echo $entry_image; ?></label>
                            <div class="col-sm-9">
                                <div class="image">
                                    <img src="<?php echo $thumb; ?>" alt="" id="thumb" />
                                    <input type="hidden" name="image" value="<?php echo $image; ?>" id="image" /><br />
                                    <button type="button" class="btn btn-primary btn-sm" onclick="image_upload('image', 'thumb');"><?php echo $text_browse; ?></button>
                                    <button type="button" class="btn btn-danger btn-sm" onclick="$('#thumb').attr('src', '<?php echo $no_image; ?>');
                                            $('#image').attr('value', '');"><?php echo $text_clear; ?></button>
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="statusInput" class="col-sm-2 control-label "><?php echo $entry_status; ?></label>
                            <div class="col-sm-9">
                                <select name="status" id="statusInput" class="form-control">
                                    <?php if ($status) { ?>
                                        <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                        <option value="0"><?php echo $text_disabled; ?></option>
                                    <?php } else { ?>
                                        <option value="1"><?php echo $text_enabled; ?></option>
                                        <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="storeInput" class="col-sm-2 control-label "><?php echo $entry_store; ?></label>
                            <div class="col-sm-6">
                                <div class="scrollbox">
                                    <ul class="list-group">
                                        <?php $class = 'even'; ?>
                                        <ul class="list-group-item <?php echo $class; ?>">
                                            <?php if (in_array(0, $company_store)) { ?>
                                                <input type="checkbox" name="company_store[]" value="0" checked="checked" />
                                                <?php echo $text_default; ?>
                                            <?php } else { ?>
                                                <input type="checkbox" name="company_store[]" value="0" />
                                                <?php echo $text_default; ?>
                                            <?php } ?>
                                            </li>
                                            <?php foreach ($stores as $store) { ?>
                                                <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                                <li class="list-group-item <?php echo $class; ?>">
                                                    <?php if (in_array($store['store_id'], $company_store)) { ?>
                                                        <input type="checkbox" name="company_store[]" value="<?php echo $store['store_id']; ?>" checked="checked" />
                                                        <?php echo $store['name']; ?>
                                                    <?php } else { ?>
                                                        <input type="checkbox" name="company_store[]" value="<?php echo $store['store_id']; ?>" />
                                                        <?php echo $store['name']; ?>
                                                    <?php } ?>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                </div>

                            </div>

                        </div>



                    </div>
                    <div class="tab-pane " id="tab-location" >

                        <?php if ($company_location): ?>
                            <?php foreach ($company_location as $i => $location): ?>

                                <fieldset>
                                    <legend><?php echo $text_location; ?> <?php if ($i > 0) : ?><button type="button" class="pull-right remove_location btn btn-danger btn-sm">X</button><?php endif; ?></legend>

                                    <div class="form-group <?php echo (isset($error_location[$i])) ? 'has-error' : ''; ?>">
                                        <label for="company_location_<?php echo $i; ?>_address" class="col-sm-2 control-label required"><?php echo $entry_address; ?></label>
                                        <div class="col-sm-9">
                                            <input data-rel="company_location_<?php echo $i; ?>" type="text" name="company_location[<?php echo $i; ?>][address]" value="<?php echo $location['address']; ?>" class="form-control google_address required" id="company_location_<?php echo $i; ?>_address" />
                                            <input type="hidden" value="<?php echo $location['latitude']; ?>" name="company_location[<?php echo $i; ?>][latitude]" id="company_location_<?php echo $i; ?>_latitude"/>
                                            <input type="hidden" value="<?php echo $location['longitude']; ?>" name="company_location[<?php echo $i; ?>][longitude]" id="company_location_<?php echo $i; ?>_longitude"/>
                                            <?php if (isset($error_location[$i])) : ?>
                                                <span class="error text-danger"><?php echo $error_location[$i]; ?></span>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="company_location_<?php echo $i; ?>_phone" class="col-sm-2 control-label "><?php echo $entry_phone; ?></label>
                                        <div class="col-sm-9">
                                            <input type="telephone" name="company_location[<?php echo $i; ?>][phone]" value="<?php echo $location['phone']; ?>" class="form-control" id="company_location_<?php echo $i; ?>_phone" />
                                        </div>
                                    </div>
                                </fieldset>
                            <?php endforeach; ?>
                        <?php endif; ?>

                        <button type="button" id="add_location" class="btn btn-primary"><?php echo $button_add_location; ?></button>


                    </div>
                    <div class="tab-pane " id="tab-staff" >

                    </div>
                </div>
                <div class="box-footer">
                    <div id="form-error" class="alert alert-danger alert-dismissable">
                        <i class="fa fa-ban"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <span></span>
                    </div>
                    <button class="btn btn-primary">
                        <i class="fa fa-check"></i> <?php echo $button_save; ?>
                    </button>
                    <a href="<?php echo $cancel; ?>" class="btn" onclick="$('#form').submit();">
                        <i class="fa fa-times"></i> <?php echo $button_cancel; ?>
                    </a>
                </div>
            </div>
        </form>
</section><!-- /.content -->

<script src="view/theme/default/js/plugins/ckeditor/ckeditor.js" type="text/javascript"></script>

<script type="text/javascript">
                        addOnready(function() {
                            CKEDITOR.replace('aboutInput', {
                                filebrowserBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                filebrowserImageBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                filebrowserFlashBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                filebrowserUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                filebrowserImageUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                filebrowserFlashUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>'
                            });

                        });
</script>
<script type="text/javascript" src="//maps.google.com/maps/api/js?libraries=places&sensor=false"></script>
<script type='text/javascript'>


                        var google_addresses = {};

                        var location_count = <?php echo (int) count($company_location); ?>;

                        function bindAddressInput(input) {
                            var id = $('#' + input).attr('id');
                            var datarel = $('#' + input).attr('data-rel');
                            google_addresses[id] = new google.maps.places.Autocomplete(document.getElementById(input), {
                                types: ['geocode']
                            });

                            $('#' + input).on('keydown', function() {
                                $('#' + datarel + '_latitude').val('');
                                $('#' + datarel + '_longitude').val('');
                            });

                            google.maps.event.addListener(google_addresses[id], 'place_changed', function() {
                                console.log('triggered');
                                var objLocation = google_addresses[id].getPlace();
                                setTimeout(function() {
                                    console.log(objLocation);
                                    $('#' + datarel + '_latitude').val(objLocation.geometry.location.lat());
                                    $('#' + datarel + '_longitude').val(objLocation.geometry.location.lng());

                                }, 500);

                            });
                        }

                        addOnready(function() {
                            $.each($('.google_address'), function(i, input) {
                                bindAddressInput($(input).attr('id'));

                            });

                            $('.remove_location').on('click', function() {
                                $(this).closest('fieldset').remove();
                            });
                            $('#add_location').on("click", function() {
                                location_count++;
                                var xhtml = '<fieldset><legend><?php echo $text_location; ?><button type="button" class="pull-right remove_location btn btn-sm btn-danger">X</button></legend>';
                                xhtml += '<div class="form-group">';
                                xhtml += '<label for="company_location_' + location_count + '_address" class="col-sm-2 control-label required"><?php echo $entry_address; ?></label>';
                                xhtml += '<div class="col-sm-9">';
                                xhtml += '    <input data-rel="company_location_' + location_count + '" type="text" name="company_location[' + location_count + '][address]" value="" class="form-control google_address required" id="company_location_' + location_count + '_address" />';
                                xhtml += '    <input type="hidden" value="" name="company_location[' + location_count + '][latitude]" id="company_location_' + location_count + '_latitude"/>';
                                xhtml += '    <input type="hidden" value="" name="company_location[' + location_count + '][longitude]" id="company_location_' + location_count + '_longitude"/>';
                                xhtml += '</div>';
                                xhtml += '</div>';
                                xhtml += '<div class="form-group">';
                                xhtml += '<label for="company_location_' + location_count + '_phone" class="col-sm-2 control-label "><?php echo $entry_phone; ?></label>';
                                xhtml += '<div class="col-sm-9">';
                                xhtml += '   <input type="telephone" name="company_location[' + location_count + '][phone]" value="" class="form-control" id="company_location_' + location_count + '_phone" />';
                                xhtml += '</div>';
                                xhtml += '</div>';
                                xhtml += '</fieldset>';
                                $('#add_location').before(xhtml);
                                $('.remove_location').on('click', function() {
                                    $(this).closest('fieldset').remove();
                                });
                                bindAddressInput('company_location_' + location_count + '_address');


                            });





                        });



</script>

<?php echo $footer; ?>