<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>



    <div class="box">
        <form action="<?php echo $action; ?>" class="form-horizontal form-validate" method="post" enctype="multipart/form-data" id="form">
            <div class="box-body">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab-general" data-toggle="tab"><?php echo $tab_general; ?></a></li>  
                        <li><a href="#tab-data" data-toggle="tab"><?php echo $tab_data; ?></a></li>
                        <li><a href="#tab-link" data-toggle="tab"><?php echo $tab_link; ?></a></li>
                        <li><a href="#tab-image" data-toggle="tab"><?php echo $tab_image; ?></a></li>
                        <li><a href="#tab-design" data-toggle="tab"><?php echo $tab_design; ?></a></li>

                    </ul>
                </div>
                <div class="tab-content">

                    <div class="tab-pane active" id="tab-general" >

                        <?php if (count($languages) > 1): ?>
                            <div class="nav-tabs">

                                <ul class="nav nav-tabs">
                                    <?php $i = 0; ?>
                                    <?php foreach ($languages as $language) : ?>
                                        <li class="<?php echo ($i++ == 0) ? 'active' : ''; ?>"><a href="#tab-language-<?php echo $language['language_id']; ?>" data-toggle="tab"><?php echo $language['name']; ?></a></li>  
                                    <?php endforeach; ?>

                                </ul>
                            </div>
                        <?php endif; ?>
                        <div class="tab-content">
                            <?php $i = 0; ?>
                            <?php foreach ($languages as $language) : ?>
                                <div class="tab-pane<?php echo ($i == '0') ? ' active' : ''; ?>" id="tab-language-<?php echo $language['language_id']; ?>" >

                                    <div class="form-group <?php echo (isset($error_title[$language['language_id']])) ? 'has-error' : ''; ?>">
                                        <label for="freepon_description_<?php echo $i; ?>_name" class="col-sm-2 control-label required"><?php echo $entry_name; ?></label>
                                        <div class="col-sm-9">
                                            <input type="text" name="freepon_description[<?php echo $language['language_id']; ?>][name]" value="<?php echo isset($freepon_description[$language['language_id']]) ? $freepon_description[$language['language_id']]['name'] : ''; ?>" class="form-control required" id="freepon_description_<?php echo $i; ?>_name" />
                                            <?php if (isset($error_title[$language['language_id']])) { ?>
                                                <span class="error text-danger"><?php echo $error_title[$language['language_id']]; ?></span>
                                            <?php } ?>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="freepon_description_<?php echo $i; ?>_description" class="col-sm-2 control-label required"><?php echo $entry_description; ?></label>
                                        <div class="col-sm-9">
                                            <textarea id="freepon_description_<?php echo $i; ?>_description" class="form-control" name="freepon_description[<?php echo $language['language_id']; ?>][description]" cols="40" rows="5"><?php echo isset($freepon_description[$language['language_id']]) ? $freepon_description[$language['language_id']]['description'] : ''; ?></textarea>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="freepon_description_<?php echo $i; ?>_usage" class="col-sm-2 control-label"><?php echo $entry_usage; ?></label>
                                        <div class="col-sm-9">
                                            <textarea id="freepon_description_<?php echo $i; ?>_usage" class="form-control" name="freepon_description[<?php echo $language['language_id']; ?>][usage]" cols="40" rows="5"><?php echo isset($freepon_description[$language['language_id']]) ? $freepon_description[$language['language_id']]['usage'] : ''; ?></textarea>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="freepon_description_<?php echo $i; ?>_meta_keyw" class="col-sm-2 control-label"><?php echo $entry_meta_keyword; ?></label>
                                        <div class="col-sm-9">
                                            <textarea id="freepon_description_<?php echo $i; ?>_meta_keyw" class="form-control" name="freepon_description[<?php echo $language['language_id']; ?>][meta_keyword]" cols="40" rows="5"><?php echo isset($freepon_description[$language['language_id']]) ? $freepon_description[$language['language_id']]['meta_keyword'] : ''; ?></textarea>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="freepon_description_<?php echo $i; ?>_meta_desc" class="col-sm-2 control-label"><?php echo $entry_meta_description; ?></label>
                                        <div class="col-sm-9">
                                            <textarea id="freepon_description_<?php echo $i; ?>_meta_desc" class="form-control" name="freepon_description[<?php echo $language['language_id']; ?>][meta_description]" cols="40" rows="5"><?php echo isset($freepon_description[$language['language_id']]) ? $freepon_description[$language['language_id']]['meta_description'] : ''; ?></textarea>
                                        </div>
                                    </div>

                                </div>
                                <?php $i++; ?>
                            <?php endforeach; ?>
                        </div>

                    </div>
                    <div class="tab-pane" id="tab-data" >



                        <div class="form-group">
                            <label for="freepon_download" class="col-sm-2 control-label"><?php echo $entry_download; ?></label>
                            <div class="col-sm-9">

                                <div class="input-group">
                                    <span id="freepon_download_span" class="form-control"><?php echo $freepon_download; ?></span>
                                    <input type="hidden" name="freepon_download" value="<?php echo $freepon_download; ?>" class="form-control" id="freepon_download" />

                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="button" onclick="file_upload('freepon_download', 'freepon_download_span');"><?php echo $text_browse; ?></button>
                                        <button class="btn btn-danger" type="button" onclick="$('#freepon_download_span').text('');
                                                $('#freepon_download').val('');"><?php echo $text_clear; ?></button>
                                    </span>
                                </div><!-- /input-group -->

                            </div>
                        </div>

                        <div class="form-group">
                            <label for="entry_code" class="col-sm-2 control-label"><?php echo $entry_code; ?></label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" name="freepon_code" id="entry_code" value="<?php echo $freepon_code; ?>"/>
                            </div><!-- /.input group -->

                        </div>



                        <div class="form-group">
                            <label for="entry_deal_times" class="col-sm-2 control-label required"><?php echo $entry_deal_times; ?></label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control required" name="freepon_times" id="reservationtime" value="<?php echo $freepon_times; ?>"/>
                            </div><!-- /.input group -->
                        </div><!-- /.form group -->


                        <div class="form-group">
                            <label for="feature_weight" class="col-sm-2 control-label"><?php echo $entry_priority; ?></label>
                            <div class="col-sm-9">
                                <input type="text" name="feature_weight" value="<?php echo $feature_weight; ?>" class="form-control number" id="feature_weight" />
                                <span class="text-info"><?php echo $entry_priority_about; ?></span>
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="statusInput" class="col-sm-2 control-label "><?php echo $entry_status; ?></label>
                            <div class="col-sm-9">
                                <select name="status" id="statusInput" class="form-control">
<?php if ($status) { ?>
                                        <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                        <option value="0"><?php echo $text_disabled; ?></option>
<?php } else { ?>
                                        <option value="1"><?php echo $text_enabled; ?></option>
                                        <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
<?php } ?>
                                </select>
                            </div>
                        </div>

                    </div>



                    <div class="tab-pane" id="tab-link">


                        <div class="form-group">
                            <label for="keyword" class="col-sm-2 control-label"><?php echo $entry_keyword; ?></label>
                            <div class="col-sm-9">
                                <input id='keyword' type="text" name="keyword" value="<?php echo $keyword; ?>" class="form-control"/>
                                <?php if ($error_duplicate_seo) { ?>
                                    <span class="error text-danger"><?php echo $error_duplicate_seo; ?></span>
<?php } ?>
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="entry_company" class="col-sm-2 control-label required"><?php echo $entry_company; ?></label>
                            <div class="col-sm-9">
                                <input id='entry_company' type="text" class="form-control" name="path" value="<?php echo $company; ?>" size="100" />
                                <input type="hidden" name="company_id" class="required" value="<?php echo $company_id; ?>" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="category_id" class="col-sm-2 control-label"><?php echo $entry_category; ?></label>
                            <div class="col-sm-9">
                                <input id='category_select' type="text"  class="form-control" autocomplete="false"/>
                                <div  class="scrollbox">
                                    <ul id="deal_category" class="list-group">
                                        <?php $class = 'odd'; ?>
                                        <?php foreach ($freepon_categories as $freepon_category) { ?>
    <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>

                                            <li id="freepon_category<?php echo $freepon_category['category_id']; ?>" class="list-group-item <?php echo $class; ?>"><?php echo $freepon_category['name']; ?><button class="btn btn-xs btn-danger btn-delete-category pull-right" type="btn" >x</button>
                                                <input type="hidden" name="freepon_category[]" value="<?php echo $freepon_category['category_id']; ?>" />
                                            </li>
<?php } ?>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="city_id" class="col-sm-2 control-label"><?php echo $entry_city; ?></label>
                            <div class="col-sm-9">
                                <input id='city_select' type="text"  class="form-control" autocomplete="false"/>
                                <div  class="scrollbox">
                                    <ul id="deal_city" class="list-group">
                                        <?php $class = 'odd'; ?>
                                        <?php foreach ($freepon_cities as $freepon_city) { ?>
    <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>

                                            <li id="deal_city<?php echo $freepon_city['city_id']; ?>" class="list-group-item <?php echo $class; ?>"><?php echo $freepon_city['name']; ?><button class="btn btn-xs btn-danger pull-right" type="btn" >x</button>
                                                <input type="hidden" name="freepon_city[]" value="<?php echo $freepon_city['city_id']; ?>" />
                                            </li>
<?php } ?>
                                    </ul>
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="storeInput" class="col-sm-2 control-label "><?php echo $entry_store; ?></label>
                            <div class="col-sm-6">
                                <div class="scrollbox">
                                    <ul class="list-group">
                                            <?php $class = 'even'; ?>
                                        <ul class="list-group-item <?php echo $class; ?>">
                                            <?php if (in_array(0, $freepon_store)) { ?>
                                                <input type="checkbox" name="freepon_store[]" value="0" checked="checked" />
                                                <?php echo $text_default; ?>
                                            <?php } else { ?>
                                                <input type="checkbox" name="freepon_store[]" value="0" />
                                                <?php echo $text_default; ?>
                                            <?php } ?>
                                            </li>
                                            <?php foreach ($stores as $store) { ?>
                                                    <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                                <li class="list-group-item <?php echo $class; ?>">
                                                    <?php if (in_array($store['store_id'], $freepon_store)) { ?>
                                                        <input type="checkbox" name="freepon_store[]" value="<?php echo $store['store_id']; ?>" checked="checked" />
                                                        <?php echo $store['name']; ?>
                                                    <?php } else { ?>
                                                        <input type="checkbox" name="freepon_store[]" value="<?php echo $store['store_id']; ?>" />
                                                        <?php echo $store['name']; ?>
                                                <?php } ?>
                                                </li>
<?php } ?>
                                        </ul>
                                </div>

                            </div>

                        </div>
                    </div>

                    <div class="tab-pane" id="tab-image">
                        <div class="form-group">
                            <label for="imageInput" class="col-sm-2 control-label "><?php echo $entry_image; ?><br /><button type="button" id="add-deal-image" class="btn btn-primary"><?php echo $text_add_image; ?></button></label>
                            <div class="col-sm-9">
                                <div class="row" id="deal-img-container">
                                    <?php if ($images): ?>
    <?php foreach ($images as $i => $image): ?>
                                            <div class="image well well-sm pull-left">
                                                <img src="<?php echo $image['thumb']; ?>" alt="" id="thumb_<?php echo $i; ?>" />
                                                <input type="hidden" name="images[]" value="<?php echo $image['image']; ?>" id="image_<?php echo $i; ?>" /><br />
                                                <button type="button" class="btn btn-primary btn-sm" onclick="image_upload('image_<?php echo $i; ?>', 'thumb_<?php echo $i; ?>');"><?php echo $text_browse; ?></button>
                                                <button type="button" class="btn btn-danger btn-sm" onclick="$('#thumb').attr('src', '<?php echo $no_image; ?>');
                                                        $('#image').attr('value', '');"><?php echo $text_clear; ?></button>
                                            </div>
                                        <?php endforeach; ?>
<?php else: ?>
                                        <div class="image well well-sm pull-left">
                                            <img src="<?php echo $no_image; ?>" alt="" id="thumb_0" />
                                            <input type="hidden" name="images[]" value="" id="image_0" /><br />
                                            <button type="button" class="btn btn-primary btn-sm" onclick="image_upload('image_0', 'thumb_0');"><?php echo $text_browse; ?></button>
                                            <button type="button" class="btn btn-danger btn-sm" onclick="$('#thumb').attr('src', '<?php echo $no_image; ?>');
                                                    $('#image').attr('value', '');"><?php echo $text_clear; ?></button>
                                        </div>
<?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>



                    <div class="tab-pane" id="tab-design" >
                        <table class="table table-bordered table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th class="left" style="width: 50%"><?php echo $entry_store; ?></th>
                                    <th class="left"><?php echo $entry_layout; ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="left" style="vertical-align:middle;"><?php echo $text_default; ?></td>
                                    <td class="left"><select name="freepon_layout[0][layout_id]" class="form-control">
                                            <option value=""></option>
                                            <?php foreach ($layouts as $layout) { ?>
                                                <?php if (isset($freepon_layout[0]) && $freepon_layout[0] == $layout['layout_id']) { ?>
                                                    <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                                                <?php } ?>
<?php } ?>
                                        </select></td>
                                </tr>
                            </tbody>
<?php foreach ($stores as $store) { ?>
                                <tbody>
                                    <tr>
                                        <td class="left" style="vertical-align:middle;"><?php echo $store['name']; ?></td>
                                        <td class="left"><select class="form-control" name="category_layout[<?php echo $store['store_id']; ?>][layout_id]">
                                                <option value=""></option>
                                                <?php foreach ($layouts as $layout) { ?>
                                                    <?php if (isset($freepon_layout[$store['store_id']]) && $freepon_layout[$store['store_id']] == $layout['layout_id']) { ?>
                                                        <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                                                    <?php } else { ?>
                                                        <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                                                    <?php } ?>
    <?php } ?>
                                            </select></td>
                                    </tr>
                                </tbody>
<?php } ?>
                        </table>
                    </div>

                </div>
                <div class="box-footer">
                    <div id="form-error" class="alert alert-danger alert-dismissable">
                        <i class="fa fa-ban"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <span></span>
                    </div>
                    <button class="btn btn-primary">
                        <i class="fa fa-check"></i> <?php echo $button_save; ?>
                    </button>
                    <a href="<?php echo $cancel; ?>" class="btn" >
                        <i class="fa fa-times"></i> <?php echo $button_cancel; ?>
                    </a>
                </div>
        </form>
    </div>

</section><!-- /.content -->

<script src="view/theme/default/js/plugins/ckeditor/ckeditor.js" type="text/javascript"></script>

<script type="text/javascript">
                                            var deal_img_count = <?php echo count($images); ?>;

                                            addOnready(function() {


                                                $('#freepon_description_0_name').on('keyup', function() {
                                                    var inputname = $(this).val();
                                                    inputname = inputname.replace(/[^A-Za-z0-9\s]+/g, '');
                                                    $('#keyword').val("coupon-" + inputname.replace(/\s+/g, '-').toLowerCase());
                                                });

                                                var EditorOps = {
                                                    filebrowserBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                                    filebrowserImageBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                                    filebrowserFlashBrowseUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                                    filebrowserUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                                    filebrowserImageUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>',
                                                    filebrowserFlashUploadUrl: 'index.php?route=common/filemanager&token=<?php echo $token; ?>'
                                                };
<?php $i = 0; ?>
<?php foreach ($languages as $language) : ?>
                                                    CKEDITOR.replace('freepon_description_<?php echo $i; ?>_description', EditorOps);
    <?php $i++; ?>
<?php endforeach; ?>

                                                $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'YYYY/MM/DD h:mm A'});




                                                $('#add-deal-image').on('click', function() {
                                                    deal_img_count++;
                                                    var xhtml = '<div class="image well well-sm pull-left">';
                                                    xhtml += '<img src="<?php echo $no_image; ?>" alt="" id="thumb_' + deal_img_count + '" />';
                                                    xhtml += '<input type="hidden" name="images[]" value="" id="image_' + deal_img_count + '" /><br />';
                                                    xhtml += '<button type="button" class="btn btn-primary btn-sm" onclick="image_upload(\'image_' + deal_img_count + '\', \'thumb_' + deal_img_count + '\');"><?php echo $text_browse; ?></button>';
                                                    xhtml += '<button type="button" class="btn btn-danger btn-sm" onclick="$(\'#thumb_' + deal_img_count + '\').attr(\'src\', \'<?php echo $no_image; ?>\');$(\'#image\').attr(\'value\', \'\');"><?php echo $text_clear; ?></button>';
                                                    xhtml += '</div>';
                                                    $('#deal-img-container').append(xhtml);
                                                });




                                                $('#category_select').autocomplete({
                                                    delay: 500,
                                                    source: function(request, response) {
                                                        $.ajax({
                                                            url: 'index.php?route=deal/category/autocomplete&token=<?php echo $token; ?>&filter_name=' + encodeURIComponent(request.term),
                                                            dataType: 'json',
                                                            success: function(json) {
                                                                response($.map(json, function(item) {
                                                                    return {
                                                                        label: item.name,
                                                                        value: item.category_id
                                                                    }
                                                                }));
                                                            }
                                                        });
                                                    },
                                                    select: function(event, ui) {
                                                        $('#deal_category' + ui.item.value).remove();

                                                        $('#deal_category').append('<li id="deal_category' + ui.item.value + '">' + ui.item.label + '<button class="btn btn-xs btn-danger btn-delete-category pull-right" type="button" >x</button><input type="hidden" name="freepon_category[]" value="' + ui.item.value + '" /></li>');

                                                        $('#deal_category li:odd').attr('class', 'list-group-item odd');
                                                        $('#deal_category li:even').attr('class', 'list-group-item even');
                                                        $('#deal_category li button').off('click').on('click', function() {

                                                            $(this).parent().remove();
                                                            $('#deal_category li:odd').attr('class', 'list-group-item odd');
                                                            $('#deal_category li:even').attr('class', 'list-group-item even');
                                                        });

                                                        return false;
                                                    },
                                                    focus: function(event, ui) {
                                                        return false;
                                                    }
                                                });

                                                $('#deal_category li button').on('click', function() {

                                                    $(this).parent().remove();
                                                    $('#deal_category li:odd').attr('class', 'list-group-item odd');
                                                    $('#deal_category li:even').attr('class', 'list-group-item even');
                                                });

                                                $('.datetime').datetimepicker({
                                                    format: 'yyyy/mm/dd hh:ii P',
                                                    weekStart: 1,
                                                    todayBtn: 1,
                                                    autoclose: 1,
                                                    todayHighlight: 1,
                                                    startView: 2,
                                                    forceParse: 0,
                                                    showMeridian: 1
                                                });

                                                $('#city_select').autocomplete({
                                                    delay: 500,
                                                    source: function(request, response) {
                                                        $.ajax({
                                                            url: 'index.php?route=localisation/city/autocomplete&token=<?php echo $token; ?>&filter_name=' + encodeURIComponent(request.term),
                                                            dataType: 'json',
                                                            success: function(json) {
                                                                response($.map(json, function(item) {
                                                                    return {
                                                                        label: item.name,
                                                                        value: item.city_id
                                                                    }
                                                                }));
                                                            }
                                                        });
                                                    },
                                                    select: function(event, ui) {
                                                        $('#deal_city' + ui.item.value).remove();

                                                        $('#deal_city').append('<li id="deal_city' + ui.item.value + '">' + ui.item.label + '<button class="btn btn-xs btn-danger pull-right" type="button" >x</button><input type="hidden" name="freepon_city[]" value="' + ui.item.value + '" /></li>');

                                                        $('#deal_city li:odd').attr('class', 'list-group-item odd');
                                                        $('#deal_city li:even').attr('class', 'list-group-item even');
                                                        $('#deal_city li button').off('click').on('click', function() {

                                                            $(this).parent().remove();
                                                            $('#deal_city li:odd').attr('class', 'list-group-item odd');
                                                            $('#deal_city li:even').attr('class', 'list-group-item even');
                                                        });

                                                        return false;
                                                    },
                                                    focus: function(event, ui) {
                                                        return false;
                                                    }
                                                });



                                                $('#deal_city li button').on('click', function() {

                                                    $(this).parent().remove();
                                                    $('#deal_city li:odd').attr('class', 'list-group-item odd');
                                                    $('#deal_city li:even').attr('class', 'list-group-item even');
                                                });


                                                $('#entry_company').autocomplete({
                                                    delay: 500,
                                                    source: function(request, response) {
                                                        $.ajax({
                                                            url: 'index.php?route=deal/company/autocomplete&token=<?php echo $token; ?>&filter_name=' + encodeURIComponent(request.term),
                                                            dataType: 'json',
                                                            success: function(json) {
                                                                /*json.unshift({
                                                                 'category_id': 0,
                                                                 'name': '<?php echo $text_none; ?>'
                                                                 });*/

                                                                response($.map(json, function(item) {
                                                                    return {
                                                                        label: item.name,
                                                                        value: item.company_id
                                                                    }
                                                                }));
                                                            }
                                                        });
                                                    },
                                                    select: function(event, ui) {
                                                        $('#entry_company').val(ui.item.label);
                                                        $('input[name=\'company_id\']').val(ui.item.value);

                                                        return false;
                                                    },
                                                    focus: function(event, ui) {
                                                        return false;
                                                    }
                                                });

                                            });
</script>

<?php echo $footer; ?>