<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-user"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>


<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>

    <form action="<?php echo $action; ?>" class="form-horizontal form-validate" method="post" enctype="multipart/form-data" id="form">





        <div class="box">

            <div class="box-body">

                <div class="form-group">
                    <label class="col-sm-2 control-label required"><?php echo $entry_name; ?></label>
                    <div class="col-sm-9"><input class="form-control required" type="text" name="name" value="<?php echo $name; ?>" />
                        <?php if ($error_name) { ?>
                            <span class="error text-danger"><?php echo $error_name; ?></span>
                        <?php } ?></div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label required"><?php echo $entry_code; ?></label>
                    <div class="col-sm-9"><input class="form-control required" type="text" name="code" value="<?php echo $code; ?>" />
                        <?php if ($error_code) { ?>
                            <span class="error text-danger"><?php echo $error_code; ?></span>
                        <?php } ?></div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label required"><?php echo $entry_locale; ?></label>
                    <div class="col-sm-9"><input class="form-control required" type="text" name="locale" value="<?php echo $locale; ?>" />
                        <?php if ($error_locale) { ?>
                            <span class="error text-danger"><?php echo $error_locale; ?></span>
                        <?php } ?></div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label required"><?php echo $entry_image; ?></label>
                    <div class="col-sm-9"><input class="form-control required" type="text" name="image" value="<?php echo $image; ?>" />
                        <?php if ($error_image) { ?>
                            <span class="error text-danger"><?php echo $error_image; ?></span>
                        <?php } ?></div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label required"><?php echo $entry_directory; ?></label>
                    <div class="col-sm-9"><input class="form-control required" type="text" name="directory" value="<?php echo $directory; ?>" />
                        <?php if ($error_directory) { ?>
                            <span class="error text-danger"><?php echo $error_directory; ?></span>
                        <?php } ?></div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label required"><?php echo $entry_filename; ?></label>
                    <div class="col-sm-9"><input class="form-control required" type="text" name="filename" value="<?php echo $filename; ?>" />
                        <?php if ($error_filename) { ?>
                            <span class="error text-danger"><?php echo $error_filename; ?></span>
                        <?php } ?></div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label "><?php echo $entry_status; ?></label>
                    <div class="col-sm-9"><select class="form-control required" name="status">
                            <?php if ($status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select></div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label "><?php echo $entry_sort_order; ?></label>
                    <div class="col-sm-2"><input class="form-control " type="text" name="sort_order" value="<?php echo $sort_order; ?>" size="1" /></div>
                </div>
            </div>
            <div class="box-footer text-center">
                <button class="btn btn-primary">
                    <i class="fa fa-check"></i> <?php echo $button_save; ?>
                </button>
                <a href="<?php echo $cancel; ?>" class="btn" onclick="$('#form').submit();">
                    <i class="fa fa-times"></i> <?php echo $button_cancel; ?>
                </a>

            </div>
        </div>
    </form>
</section>
<?php echo $footer; ?>