<?php echo $header; ?>
<div class="container">
    <?php echo $column_left; ?>
    <?php echo $column_right; ?>
    <div id="content">
        <?php echo $content_top; ?>
        <div class="breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
            <?php } ?>
        </div>
        <?php if ($success) { ?>
            <div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><?php echo $success; ?></div>
        <?php } ?>
        <?php if ($error_warning) { ?>
            <div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><?php echo $error_warning; ?></div>
        <?php } ?>
        <h1><?php echo $heading_title; ?></h1>
        <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data">

            <div class="cart-info">
                <table class="table table-striped table-bordered table-responsive">
                    <thead>
                        <tr>
                            <th class="image"><?php echo $column_image; ?></th>
                            <th class="name"><?php echo $column_name; ?></th>
                            <th class="quantity"><?php echo $column_quantity; ?></th>
                            <th class="price"><?php echo $column_price; ?></th>
                            <th class="price"><?php echo $column_shipping; ?></th>
                            <th class="total"><?php echo $column_total; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($products as $product) { ?>

                            <tr>
                                <td class="image"><?php if ($product['thumb']) { ?>
                                        <a href="<?php echo $product['href']; ?>"><img src="<?php echo $product['thumb']; ?>" alt="<?php echo $product['name']; ?>" title="<?php echo $product['name']; ?>" /></a>
                                    <?php } ?></td>
                                <td class="name"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a>
                                    <?php if (!$product['stock']) { ?>
                                        <span class="stock">***</span>
                                    <?php } ?>
                                    <div>
                                        - <small><?php echo $product['option']['title']; ?></small><br />
                                        <?php if ($product['is_coupon']): ?>
                                            - <small>Printable Coupon</small>
                                        <?php else: ?>
                                            - <small><?php echo $product['shipping']['title']; ?> : <?php echo ($product['shipping']['price'] > 0) ? $this->currency->format($product['shipping']['price']) : 'Free'; ?></small>

                                        <?php endif; ?>
                                    </div>
                                </td>

                                <td class="quantity">
                                    <input type="text" name="quantity[<?php echo $product['key']; ?>]" value="<?php echo $product['quantity']; ?>" size="1" class="form-control"/>
                                    <button type="submit" class='btn btn-primary fa-icon-refresh btn-square' title='<?php echo $button_update; ?>'></button>
                                    <a href="<?php echo $product['remove']; ?>" class="btn btn-danger fa-icon-remove btn-square" alt="<?php echo $button_remove; ?>" title="<?php echo $button_remove; ?>" ></a></td>
                                <td class="price"><?php echo $product['price']; ?></td>
                                <td class="price"><?php echo ($product['is_coupon'] || $product['shipping']['price'] == 0) ? 'Free' : $this->currency->format($product['shipping']['price']); ?></td>
                                <td class="total"><?php echo $product['total']; ?></td>
                            </tr>
                        <?php } ?>

                        <?php foreach ($vouchers as $vouchers) { ?>
                            <tr>
                                <td class="image"></td>
                                <td class="name"><?php echo $vouchers['description']; ?></td>

                                <td class="quantity">
                                    <input type="text" name="" value="1" size="1" disabled="disabled" class="form-control"/>

                                    <a href="<?php echo $vouchers['remove']; ?>" class="btn btn-danger fa-icon-remove btn-square" alt="<?php echo $button_remove; ?>" title="<?php echo $button_remove; ?>" ></a>

                                </td>
                                <td class="price"><?php echo $vouchers['amount']; ?></td>
                                <td class="price"></td>
                                <td class="total"><?php echo $vouchers['amount']; ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </form>
        <?php if ($coupon_status || $voucher_status) { ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title"><?php echo $text_next; ?></h2>
                    <p><?php echo $text_next_choice; ?></p>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <table class="table table-hover table-condensed">
                                <?php if ($coupon_status) { ?>
                                    <tr>
                                        <td>
                                            <div class="radio">
                                                <label for="use_coupon">
                                                    <?php if ($next == 'coupon') { ?>
                                                        <input type="radio" name="next" value="coupon" id="use_coupon" checked="checked" />
                                                    <?php } else { ?>
                                                        <input type="radio" name="next" value="coupon" id="use_coupon" />
                                                    <?php } ?><?php echo $text_use_coupon; ?></label>
                                            </div></td>
                                    </tr>
                                <?php } ?>
                                <?php if ($voucher_status) { ?>
                                    <tr>
                                        <td>
                                            <div class="radio">
                                                <label for="use_voucher">
                                                    <?php if ($next == 'voucher') { ?>
                                                        <input type="radio" name="next" value="voucher" id="use_voucher" checked="checked" />
                                                    <?php } else { ?>
                                                        <input type="radio" name="next" value="voucher" id="use_voucher" />
                                                    <?php } ?><?php echo $text_use_voucher; ?></label>
                                            </div></td>
                                    </tr>
                                <?php } ?>
                            </table>
                        </div>

                        <div class="col-md-7 col-sm-7 col-xs-12">
                            <div class="cart-module">
                                <div id="coupon" class="content" style="display: <?php echo ($next == 'coupon' ? 'block' : 'none'); ?>;">
                                    <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data">
                                        <div class="form-group">
                                            <label for="couponInput"> <?php echo $entry_coupon; ?></label>
                                            <input type="text" name="coupon" value="<?php echo $coupon; ?>" class="form-control" id="couponInput"/>
                                            <input type="hidden" name="next" value="coupon" />
                                        </div>
                                        <button type="submit" class="btn btn-primary pull-right"><?php echo $button_coupon; ?></button>

                                    </form>
                                </div>
                                <div id="voucher" class="content" style="display: <?php echo ($next == 'voucher' ? 'block' : 'none'); ?>;">
                                    <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data">
                                        <div class="form-group">
                                            <label for="voucherInput"> <?php echo $entry_voucher; ?></label>
                                            <input type="text" name="voucher" value="<?php echo $voucher; ?>" class="form-control" id="voucherInput"/>
                                            <input type="hidden" name="next" value="voucher" />
                                        </div>
                                        <button type="submit" class="btn btn-primary pull-right"><?php echo $button_voucher; ?></button>


                                    </form>
                                </div>


                            </div>
                        </div>
                    </div>
                </div>

            </div>
        <?php } ?>
        <div class="row">
            <div class="cart-total col-md-4 col-sm-8 cols-xs-12 pull-right">
                <table id="total" class="table table-bordered table-responsive table-condensed">
                    <?php foreach ($totals as $total) { ?>
                        <tr>
                            <td class="total"><b><?php echo $total['title']; ?>:</b></td>
                            <td class="total"><?php echo $total['text']; ?></td>
                        </tr>
                    <?php } ?>
                </table>
            </div>
        </div>

        <div class="buttons clearfix">
            <a href="<?php echo $checkout; ?>" class="btn btn-primary pull-right"><?php echo $button_checkout; ?></a>
            <a href="<?php echo $continue; ?>" class="btn btn-primary pull-left"><?php echo $button_shopping; ?></a>
        </div>
        <?php echo $content_bottom; ?></div>
</div>
<script>
    addOnready(function() {
        $('input[name=\'next\']').on('change', function() {
            $('.cart-module > div').hide();

            $('#' + this.value).show();
        });
    });
</script>
<?php echo $footer; ?>