<?php if (!isset($redirect)) { ?>
    <div class="checkout-product">

        <table class="table table-striped table-bordered table-responsive">
            <thead>
                <tr>
                    <th class="name"><?php echo $column_name; ?></th>
                    <th class="quantity"><?php echo $column_quantity; ?></th>
                    <th class="price hidden-xs hidden-sm"><?php echo $column_price; ?></th>
                    <th class="price hidden-xs hidden-sm"><?php echo $column_shipping; ?></th>
                    <th class="total"><?php echo $column_total; ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($products as $product) { ?>  

                    <tr>
                        <td class="name"><a href="<?php echo $product['href']; ?>"><?php echo $product['title']; ?></a>
                            <?php if (!$product['stock']) { ?>
                                <span class="stock">***</span>
                            <?php } ?>
                            <div>
                                - <small><?php echo $product['option']['title']; ?></small><br />
                                <?php if ($product['is_coupon']): ?>
                                    - <small>Printable Coupon</small>
                                <?php else: ?>
                                    - <small><?php echo $product['shipping']['title']; ?> : <?php echo ($product['shipping']['price'] > 0) ? $this->currency->format($product['shipping']['price']) : 'Free'; ?></small>

                                <?php endif; ?>
                            </div>
                        </td>
                        <td class="quantity">
                            <?php echo $product['quantity']; ?>

                        </td>
                        <td class="price  hidden-xs hidden-sm"><?php echo $product['price']; ?></td>
                        <td class="price  hidden-xs hidden-sm"><?php echo ($product['is_coupon'] || $product['shipping']['price'] == 0) ? 'Free' : $this->currency->format($product['shipping']['price']); ?></td>
                        <td class="total"><?php echo $product['total']; ?></td>

                    </tr>
                <?php } ?>
                <?php foreach ($vouchers as $voucher) { ?>
                    <tr>
                        <td class="name"><?php echo $voucher['description']; ?></td>

                        <td class="quantity">1</td>
                        <td class="price hidden-xs hidden-sm"><?php echo $voucher['amount']; ?></td>
                        <td class="price hidden-xs hidden-sm"></td>
                        <td class="total"><?php echo $voucher['amount']; ?></td>
                    </tr>
                <?php } ?>
            </tbody>
            <tfoot>
                <?php foreach ($totals as $total) { ?>
                    <tr>
                        <td colspan="2" class="price hidden-xs hidden-sm"></td>
                        <td colspan="2" class="price"><b><?php echo $total['title']; ?>:</b></td>
                        <td class="total"><?php echo $total['text']; ?></td>
                    </tr>
                <?php } ?>
            </tfoot>
        </table>
    </div>
    <div class="payment"><?php echo $payment; ?></div>
<?php } else { ?>
    <script type="text/javascript"><!--
    location = '<?php echo $redirect; ?>';
        //--></script> 
<?php } ?>