<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"><?php echo $text_new_customer; ?></h2>

            </div>
            <div class="panel-body">
                <p><?php echo $text_checkout; ?></p>
                <div class="radio">
                    <label for="register">
                        <?php if ($account == 'register') { ?>
                            <input type="radio" name="account" value="register" id="register" checked="checked" />
                        <?php } else { ?>
                            <input type="radio" name="account" value="register" id="register" />
                        <?php } ?>
                        <b><?php echo $text_register; ?></b></label>
                </div>
                <?php if ($guest_checkout) : ?>
                    <div class="radio">
                        <label for="guest">
                            <?php if ($account == 'guest') { ?>
                                <input type="radio" name="account" value="guest" id="guest" checked="checked" />
                            <?php } else { ?>
                                <input type="radio" name="account" value="guest" id="guest" />
                            <?php } ?>
                            <b><?php echo $text_guest; ?></b></label>
                    </div>
                <?php endif; ?>
                <p class="well well-sm"><?php echo $text_register_account; ?></p>
                <button type="button" id="button-account" class="btn btn-primary pull-right" ><?php echo $button_continue; ?></button>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"><?php echo $text_returning_customer; ?></h2>

            </div>
            <div class="panel-body" id="login" >
                <p><?php echo $text_i_am_returning_customer; ?></p>
                <div class="form-group">
                    <label for="InputEmail1"><?php echo $entry_email; ?></label>
                    <input name="email" type="email" class="form-control" value="" id="InputEmail1" placeholder="<?php echo $entry_email; ?>">
                </div>

                <div class="form-group">
                    <label for="InputPassword1"><?php echo $entry_password; ?></label>
                    <input name="password" type="password" class="form-control" value="" id="InputPassword1" placeholder="<?php echo $entry_password; ?>">
                </div>
                <div class="clearfix">
                    <a class="btn btn-link pull-left" href="<?php echo $forgotten; ?>"><?php echo $text_forgotten; ?></a>
                    <button type="button" class="btn btn-primary pull-right" id="button-login"><?php echo $button_login; ?></button>
                </div>

            </div>
        </div>

    </div>
</div>
