<?php if ($addresses) { ?>
    <input type="radio" name="payment_address" value="existing" id="payment-address-existing" checked="checked" />
    <label for="payment-address-existing"><?php echo $text_address_existing; ?></label>
    <div id="payment-existing">
        <select name="address_id" class="form-control">
            <?php foreach ($addresses as $address) { ?>
                <?php if ($address['address_id'] == $address_id) { ?>
                    <option value="<?php echo $address['address_id']; ?>" selected="selected"><?php echo $address['firstname']; ?> <?php echo $address['lastname']; ?>, <?php echo $address['address_1']; ?>, <?php echo $address['city']; ?>, <?php echo $address['zone']; ?>, <?php echo $address['country']; ?></option>
                <?php } else { ?>
                    <option value="<?php echo $address['address_id']; ?>"><?php echo $address['firstname']; ?> <?php echo $address['lastname']; ?>, <?php echo $address['address_1']; ?>, <?php echo $address['city']; ?>, <?php echo $address['zone']; ?>, <?php echo $address['country']; ?></option>
                <?php } ?>
            <?php } ?>
        </select>
    </div>
    <p>
        <input type="radio" name="payment_address" value="new" id="payment-address-new" />
        <label for="payment-address-new"><?php echo $text_address_new; ?></label>
    </p>
<?php } ?>
<div id="payment-new" style="display: <?php echo ($addresses ? 'none' : 'block'); ?>;" class="form-horizontal">

    <div class="form-group">
        <label for="paymentFirstname" class="col-sm-2 control-label required"><?php echo $entry_firstname; ?></label>
        <div class="col-sm-10">
            <input type="text" name="firstname" class="form-control required" id="paymentFirstname" placeholder="<?php echo $entry_firstname; ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="paymentLastname" class="col-sm-2 control-label required"><?php echo $entry_lastname; ?></label>
        <div class="col-sm-10">
            <input type="text" name="lastname" class="form-control required" id="paymentLastname" placeholder="<?php echo $entry_lastname; ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="paymentCompany" class="col-sm-2 control-label "><?php echo $entry_company; ?></label>
        <div class="col-sm-10">
            <input type="text" name="company" class="form-control " id="paymentCompany" placeholder="<?php echo $entry_company; ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="paymentaddress_1" class="col-sm-2 control-label required"><?php echo $entry_address_1; ?></label>
        <div class="col-sm-10">
            <input type="text" name="address_1" class="form-control required" id="paymentaddress_1" placeholder="<?php echo $entry_address_1; ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="paymentaddress_2" class="col-sm-2 control-label "><?php echo $entry_address_2; ?></label>
        <div class="col-sm-10">
            <input type="text" name="address_2" class="form-control " id="paymentaddress_2" placeholder="<?php echo $entry_address_2; ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="paymentcity" class="col-sm-2 control-label required"><?php echo $entry_city; ?></label>
        <div class="col-sm-10">
            <input type="text" name="city" class="form-control required" id="paymentcity" placeholder="<?php echo $entry_city; ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="paymentpostcode" class="col-sm-2 control-label required"><?php echo $entry_postcode; ?></label>
        <div class="col-sm-10">
            <input type="text" name="postcode" class="form-control required" id="paymentpostcode" placeholder="<?php echo $entry_postcode; ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="paymentcountry_id" class="col-sm-2 control-label required"><?php echo $entry_country; ?></label>
        <div class="col-sm-10">
            <select name="country_id" class="form-control required" id="paymentcountry_id">
                <option value=""><?php echo $text_select; ?></option>
                <?php foreach ($countries as $country) { ?>
                    <?php if ($country['country_id'] == $country_id) { ?>
                        <option value="<?php echo $country['country_id']; ?>" selected="selected"><?php echo $country['name']; ?></option>
                    <?php } else { ?>
                        <option value="<?php echo $country['country_id']; ?>"><?php echo $country['name']; ?></option>
                    <?php } ?>
                <?php } ?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="paymentzone_id" class="col-sm-2 control-label required"><?php echo $entry_zone; ?></label>
        <div class="col-sm-10">
            <select name="zone_id" class="form-control required" id="paymentzone_id">

            </select>
        </div>
    </div>
</div>
<div class="buttons clearfix">

    <button type="button" id="button-payment-address" class="btn btn-primary pull-right"><?php echo $button_continue; ?></button>

</div>
<script type="text/javascript"><!--
$('#payment-address input[name=\'payment_address\']').on('change', function() {
        if (this.value == 'new') {
            $('#payment-existing').hide();
            $('#payment-new').show();
        } else {
            $('#payment-existing').show();
            $('#payment-new').hide();
        }
    });
//--></script> 
<script type="text/javascript"><!--
    $('#payment-address select[name=\'country_id\']').on('change', function() {
        if (this.value == '')
            return;
        $.ajax({
            url: 'index.php?route=checkout/checkout/country&country_id=' + this.value,
            dataType: 'json',
            beforeSend: function() {
                $('#payment-address select[name=\'country_id\']').after('<span class="wait">&nbsp;<img src="public/view/theme/default/image/loading.gif" alt="" /></span>');
            },
            complete: function() {
                $('.wait').remove();
            },
            success: function(json) {
                if (json['postcode_required'] == '1') {
                    $('#payment-postcode-required').show();
                } else {
                    $('#payment-postcode-required').hide();
                }

                html = '<option value=""><?php echo $text_select; ?></option>';

                if (json['zone'] != '') {
                    for (i = 0; i < json['zone'].length; i++) {
                        html += '<option value="' + json['zone'][i]['zone_id'] + '"';

                        if (json['zone'][i]['zone_id'] == '<?php echo $zone_id; ?>') {
                            html += ' selected="selected"';
                        }

                        html += '>' + json['zone'][i]['name'] + '</option>';
                    }
                } else {
                    html += '<option value="0" selected="selected"><?php echo $text_none; ?></option>';
                }

                $('#payment-address select[name=\'zone_id\']').html(html);
            },
            error: function(xhr, ajaxOptions, thrownError) {
                alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
            }
        });
    });

    $('#payment-address select[name=\'country_id\']').trigger('change');
//--></script>