<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>


<!-- Main content -->
<section class="content">


    <div class="box">
        <div class="box-body">

            <table class="table table-bordered table-striped table-responsive">
                <thead>
                    <tr>
                        <th class="left"><?php echo $column_ip; ?></th>
                        <th class="left"><?php echo $column_customer; ?></th>
                        <th class="left"><?php echo $column_url; ?></th>
                        <th class="left"><?php echo $column_referer; ?></th>
                        <th class="left"><?php echo $column_date_added; ?></th>
                        <th class="right"><?php echo $column_action; ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="filter">
                        <td align="left"><input type="text" name="filter_ip" value="<?php echo $filter_ip; ?>" /></td>
                        <td align="left"><input type="text" name="filter_customer" value="<?php echo $filter_customer; ?>" /></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td align="right"><a onclick="filter();" class="btn btn-primary btn-sm"><?php echo $button_filter; ?></a></td>
                    </tr>
                    <?php if ($customers) { ?>
                        <?php foreach ($customers as $customer) { ?>
                            <tr>
                                <td class="left"><a href="http://whatismyipaddress.com/ip/<?php echo $customer['ip']; ?>" target="_blank"><?php echo $customer['ip']; ?></a></td>
                                <td class="left"><?php echo $customer['customer']; ?></td>
                                <td class="left"><a href="<?php echo $customer['url']; ?>" target="_blank"><?php echo implode('<br/>', str_split($customer['url'], 30)); ?></a></td>
                                <td class="left"><?php if ($customer['referer']) { ?>
                                        <a href="<?php echo $customer['referer']; ?>" target="_blank"><?php echo implode('<br/>', str_split($customer['referer'], 30)); ?></a>
                                    <?php } ?></td>
                                <td class="left"><?php echo $customer['date_added']; ?></td>
                                <td class="right"><?php foreach ($customer['action'] as $action) { ?>
                                        [ <a href="<?php echo $action['href']; ?>"><?php echo $action['text']; ?></a> ]
                                    <?php } ?></td>            
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                        <tr>
                            <td class="center" colspan="6"><?php echo $text_no_results; ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
            </form>
        </div>
        <div class="box-footer">
            <div class="row">
                <div class="pagination-container">
                    <?php echo $pagination; ?>
                </div>
            </div>
        </div>
    </div>

</section><!-- /.content -->



<script type="text/javascript"><!--
function filter() {
        url = 'index.php?route=report/customer_online&token=<?php echo $token; ?>';

        var filter_customer = $('input[name=\'filter_customer\']').attr('value');

        if (filter_customer) {
            url += '&filter_customer=' + encodeURIComponent(filter_customer);
        }

        var filter_ip = $('input[name=\'filter_ip\']').attr('value');

        if (filter_ip) {
            url += '&filter_ip=' + encodeURIComponent(filter_ip);
        }

        location = url;
    }
//--></script> 

<?php echo $footer; ?>