<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>

    <div id="form-error" class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <span></span>
    </div>

    <div class="box">

    </div>

</section><!-- /.content -->

<?php echo $footer; ?>