<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>
<section class="page-actions">
    <button onclick="$('#form').attr('action', '<?php echo $approve; ?>');
            $('form').submit();" class="btn btn-primary">
        <i class="fa fa-check"></i> <?php echo $button_approve; ?>
    </button>
    <a href="<?php echo $insert; ?>" class="btn btn-primary">
        <i class="fa fa-plus"></i> <?php echo $button_insert; ?>
    </a>
    <button class="btn btn-danger" onclick="$('#form').attr('action', '<?php echo $delete; ?>');
            $('form').submit();
            ;">
        <i class="fa fa-times"></i> <?php echo $button_delete; ?>
    </button>

</section>

<!-- Main content -->
<section class="content">
    <?php if ($error_warning) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $error_warning; ?>
        </div>
    <?php } ?>
    <?php if ($success) { ?>
        <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?php echo $success; ?>
        </div>
    <?php } ?>

    <div class="box">
        <div class="box-body">
            <form action="" method="post" enctype="multipart/form-data" id="form">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th width="1" style="text-align: center;"><input class="selectall" type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" /></th>
                            <th class="left"><?php if ($sort == 'name') { ?>
                                    <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php if ($sort == 'email') { ?>
                                    <a href="<?php echo $sort_email; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_email; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_email; ?>"><?php echo $column_email; ?></a>
                                <?php } ?></th>
                           
                            <th class="left"><?php if ($sort == 'status') { ?>
                                    <a href="<?php echo $sort_status; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_status; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_status; ?>"><?php echo $column_status; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php if ($sort == 'approved') { ?>
                                    <a href="<?php echo $sort_approved; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_approved; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_approved; ?>"><?php echo $column_approved; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php if ($sort == 'ip') { ?>
                                    <a href="<?php echo $sort_ip; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_ip; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_ip; ?>"><?php echo $column_ip; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php if ($sort == 'date_added') { ?>
                                    <a href="<?php echo $sort_date_added; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_date_added; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_date_added; ?>"><?php echo $column_date_added; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php echo $column_login; ?></th>
                            <th class="right"><?php echo $column_action; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="filter">
                            <td></td>
                            <td><input type="text" name="filter_name" value="<?php echo $filter_name; ?>" class="form-control"/></td>
                            <td><input type="text" name="filter_email" value="<?php echo $filter_email; ?>" class="form-control"/></td>
                            
                            <td><select name="filter_status" class="form-control">
                                    <option value="*"></option>
                                    <?php if ($filter_status) { ?>
                                        <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                    <?php } else { ?>
                                        <option value="1"><?php echo $text_enabled; ?></option>
                                    <?php } ?>
                                    <?php if (!is_null($filter_status) && !$filter_status) { ?>
                                        <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                    <?php } else { ?>
                                        <option value="0"><?php echo $text_disabled; ?></option>
                                    <?php } ?>
                                </select></td>
                            <td><select name="filter_approved" class="form-control">
                                    <option value="*"></option>
                                    <?php if ($filter_approved) { ?>
                                        <option value="1" selected="selected"><?php echo $text_yes; ?></option>
                                    <?php } else { ?>
                                        <option value="1"><?php echo $text_yes; ?></option>
                                    <?php } ?>
                                    <?php if (!is_null($filter_approved) && !$filter_approved) { ?>
                                        <option value="0" selected="selected"><?php echo $text_no; ?></option>
                                    <?php } else { ?>
                                        <option value="0"><?php echo $text_no; ?></option>
                                    <?php } ?>
                                </select></td>
                            <td><input type="text" data-inputmask="'alias': 'ip'" name="filter_ip" value="<?php echo $filter_ip; ?>" class="form-control"/></td>
                            <td><input type="text" name="filter_date_added" value="<?php echo $filter_date_added; ?>" data-date="<?php echo $filter_date_added; ?>" size="12" id="date" class="form-control" data-date-format="yyyy-mm-dd"/></td>
                            <td></td>
                            <td align="right"><button onclick="filter();" class="btn btn-primary"><?php echo $button_filter; ?></button></td>
                        </tr>
                        <?php if ($customers) { ?>
                            <?php foreach ($customers as $customer) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php if ($customer['selected']) { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $customer['customer_id']; ?>" checked="checked" />
                                        <?php } else { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $customer['customer_id']; ?>" />
                                        <?php } ?></td>
                                    <td class="left"><?php echo $customer['name']; ?></td>
                                    <td class="left"><?php echo $customer['email']; ?></td>
                                    <td class="left"><?php echo $customer['status']; ?></td>
                                    <td class="left"><?php echo $customer['approved']; ?></td>
                                    <td class="left"><?php echo $customer['ip']; ?></td>
                                    <td class="left"><?php echo $customer['date_added']; ?></td>
                                    <td class="left"><select onchange="((this.value !== '') ? window.open('index.php?route=sale/customer/login&token=<?php echo $token; ?>&customer_id=<?php echo $customer['customer_id']; ?>&store_id=' + this.value) : null);
                              this.value = '';">
                                            <option value=""><?php echo $text_select; ?></option>
                                            <option value="0"><?php echo $text_default; ?></option>
                                            <?php foreach ($stores as $store) { ?>
                                                <option value="<?php echo $store['store_id']; ?>"><?php echo $store['name']; ?></option>
                                            <?php } ?>
                                        </select></td>
                                    <td class="right"><?php foreach ($customer['action'] as $action) { ?>
                                             <a href="<?php echo $action['href']; ?>" class="btn btn-primary btn-xs"><?php echo $action['text']; ?></a>
                                        <?php } ?></td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td class="center" colspan="10"><div class="alert alert-info"><?php echo $text_no_results; ?></div></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </form>
        </div>
        <div class="box-footer">
            <div class="row">
                <div class="pagination-container">
                    <?php echo $pagination; ?>
                </div>
            </div>
        </div>
    </div>

</section><!-- /.content -->


<script type="text/javascript">
    addOnready(function() {
        $('#date').datepicker();
        $('#form input').keydown(function(e) {
	if (e.keyCode == 13) {
		filter();
	}
});
    });
</script>

<?php echo $footer; ?>