<?php echo $header; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-dashboard"></i> <?php echo $heading_title; ?><small></small>
    </h1>
    <ol class="breadcrumb">
        <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ol>
</section>
<section class="page-actions">
    <a href="<?php echo $invoice; ?>" target="_blank" class="btn btn-primary"><?php echo $button_invoice; ?></a>
    <a href="<?php echo $cancel; ?>" class="btn btn-default"><?php echo $button_cancel; ?></a>



</section>

<!-- Main content -->
<section class="content">

    <div id="form-error" class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <span></span>
    </div>

    <div class="box">
        <div class="box-body">
            <div class="tabbable tabs-left clearfix">
                <ul class="nav nav-tabs">

                    <li class="active"><a href="#tab-order"  data-toggle="tab"><?php echo $tab_order; ?></a></li>
                    <li><a href="#tab-payment"  data-toggle="tab"><?php echo $tab_payment; ?></a></li>
                    <?php if ($shipping_method) { ?>
                        <li><a href="#tab-shipping"  data-toggle="tab"><?php echo $tab_shipping; ?></a></li>
                    <?php } ?>
                    <li><a href="#tab-product"  data-toggle="tab"><?php echo $tab_product; ?></a></li>
                    <li><a href="#tab-history" data-toggle="tab"><?php echo $tab_history; ?></a></li>
                    <?php if ($maxmind_id) { ?>
                        <li><a href="#tab-fraud"  data-toggle="tab"><?php echo $tab_fraud; ?></a></li>
                    <?php } ?>

                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab-order">
                        <legend><?php echo $tab_order; ?></legend>
                        <table class="table table-responsive">
                            <tr>
                                <td><?php echo $text_order_id; ?></td>
                                <td>#<?php echo $order_id; ?></td>
                            </tr>
                            <?php if (!empty($amazon_order_id)) { ?>

                                <tr>
                                    <td><?php echo $text_amazon_order_id; ?></td>
                                    <td><?php echo $amazon_order_id; ?></td>
                                </tr>

                            <?php } ?>
                            <tr>
                                <td><?php echo $text_invoice_no; ?></td>
                                <td><?php if ($invoice_no) { ?>
                                        <?php echo $invoice_no; ?>
                                    <?php } else { ?>
                                        <span id="invoice"><b>[</b> <a id="invoice-generate"><?php echo $text_generate; ?></a> <b>]</b></span>
                                    <?php } ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $text_store_name; ?></td>
                                <td><?php echo $store_name; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $text_store_url; ?></td>
                                <td><a href="<?php echo $store_url; ?>" target="_blank"><u><?php echo $store_url; ?></u></a></td>
                            </tr>
                            <?php if ($customer) { ?>
                                <tr>
                                    <td><?php echo $text_customer; ?></td>
                                    <td><a href="<?php echo $customer; ?>"><?php echo $firstname; ?> <?php echo $lastname; ?></a></td>
                                </tr>
                            <?php } else { ?>
                                <tr>
                                    <td><?php echo $text_customer; ?></td>
                                    <td><?php echo $firstname; ?> <?php echo $lastname; ?></td>
                                </tr>
                            <?php } ?>

                            <tr>
                                <td><?php echo $text_email; ?></td>
                                <td><?php echo $email; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $text_telephone; ?></td>
                                <td><?php echo $telephone; ?></td>
                            </tr>
                            <?php if ($fax) { ?>
                                <tr>
                                    <td><?php echo $text_fax; ?></td>
                                    <td><?php echo $fax; ?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td><?php echo $text_total; ?></td>
                                <td><?php echo $total; ?>
                                    <?php if ($credit && $customer) { ?>
                                        <?php if (!$credit_total) { ?>
                                            <span id="credit"><b>[</b> <a id="credit-add"><?php echo $text_credit_add; ?></a> <b>]</b></span>
                                        <?php } else { ?>
                                            <span id="credit"><b>[</b> <a id="credit-remove"><?php echo $text_credit_remove; ?></a> <b>]</b></span>
                                        <?php } ?>
                                    <?php } ?></td>
                            </tr>
                            <?php if ($order_status) { ?>
                                <tr>
                                    <td><?php echo $text_order_status; ?></td>
                                    <td id="order-status"><?php echo $order_status; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($comment) { ?>
                                <tr>
                                    <td><?php echo $text_comment; ?></td>
                                    <td><?php echo $comment; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($affiliate) { ?>
                                <tr>
                                    <td><?php echo $text_affiliate; ?></td>
                                    <td><a href="<?php echo $affiliate; ?>"><?php echo $affiliate_firstname; ?> <?php echo $affiliate_lastname; ?></a></td>
                                </tr>
                                <tr>
                                    <td><?php echo $text_commission; ?></td>
                                    <td><?php echo $commission; ?>
                                        <?php if (!$commission_total) { ?>
                                            <span id="commission"><b>[</b> <a id="commission-add"><?php echo $text_commission_add; ?></a> <b>]</b></span>
                                        <?php } else { ?>
                                            <span id="commission"><b>[</b> <a id="commission-remove"><?php echo $text_commission_remove; ?></a> <b>]</b></span>
                                        <?php } ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip) { ?>
                                <tr>
                                    <td><?php echo $text_ip; ?></td>
                                    <td><?php echo $ip; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($forwarded_ip) { ?>
                                <tr>
                                    <td><?php echo $text_forwarded_ip; ?></td>
                                    <td><?php echo $forwarded_ip; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($user_agent) { ?>
                                <tr>
                                    <td><?php echo $text_user_agent; ?></td>
                                    <td><?php echo $user_agent; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($accept_language) { ?>
                                <tr>
                                    <td><?php echo $text_accept_language; ?></td>
                                    <td><?php echo $accept_language; ?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td><?php echo $text_date_added; ?></td>
                                <td><?php echo $date_added; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $text_date_modified; ?></td>
                                <td><?php echo $date_modified; ?></td>
                            </tr>
                        </table>
                    </div>
                    <div class="tab-pane" id="tab-payment">
                        <legend><?php echo $tab_payment; ?></legend>
                        <table class="table table-responsive">
                            <tr>
                                <td><?php echo $text_firstname; ?></td>
                                <td><?php echo $payment_firstname; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $text_lastname; ?></td>
                                <td><?php echo $payment_lastname; ?></td>
                            </tr>
                            <?php if ($payment_company) { ?>
                                <tr>
                                    <td><?php echo $text_company; ?></td>
                                    <td><?php echo $payment_company; ?></td>
                                </tr>
                            <?php } ?>

                            <tr>
                                <td><?php echo $text_address_1; ?></td>
                                <td><?php echo $payment_address_1; ?></td>
                            </tr>
                            <?php if ($payment_address_2) { ?>
                                <tr>
                                    <td><?php echo $text_address_2; ?></td>
                                    <td><?php echo $payment_address_2; ?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td><?php echo $text_city; ?></td>
                                <td><?php echo $payment_city; ?></td>
                            </tr>
                            <?php if ($payment_postcode) { ?>
                                <tr>
                                    <td><?php echo $text_postcode; ?></td>
                                    <td><?php echo $payment_postcode; ?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td><?php echo $text_zone; ?></td>
                                <td><?php echo $payment_zone; ?></td>
                            </tr>
                            <?php if ($payment_zone_code) { ?>
                                <tr>
                                    <td><?php echo $text_zone_code; ?></td>
                                    <td><?php echo $payment_zone_code; ?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td><?php echo $text_country; ?></td>
                                <td><?php echo $payment_country; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $text_payment_method; ?></td>
                                <td><?php echo $payment_method; ?></td>
                            </tr>
                        </table>
                    </div>
                    <div class="tab-pane" id="tab-shipping">
                        <legend><?php echo $tab_shipping; ?></legend>
                        <table class="table table-responsive">


                            <tr>
                                <td><?php echo $text_firstname; ?></td>
                                <td><?php echo $shipping_firstname; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $text_lastname; ?></td>
                                <td><?php echo $shipping_lastname; ?></td>
                            </tr>

                            <?php if ($shipping_company) { ?>
                                <tr>
                                    <td><?php echo $text_company; ?></td>
                                    <td><?php echo $shipping_company; ?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td><?php echo $text_address_1; ?></td>
                                <td><?php echo $shipping_address_1; ?></td>
                            </tr>
                            <?php if ($shipping_address_2) { ?>
                                <tr>
                                    <td><?php echo $text_address_2; ?></td>
                                    <td><?php echo $shipping_address_2; ?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td><?php echo $text_city; ?></td>
                                <td><?php echo $shipping_city; ?></td>
                            </tr>
                            <?php if ($shipping_postcode) { ?>
                                <tr>
                                    <td><?php echo $text_postcode; ?></td>
                                    <td><?php echo $shipping_postcode; ?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td><?php echo $text_zone; ?></td>
                                <td><?php echo $shipping_zone; ?></td>
                            </tr>
                            <?php if ($shipping_zone_code) { ?>
                                <tr>
                                    <td><?php echo $text_zone_code; ?></td>
                                    <td><?php echo $shipping_zone_code; ?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td><?php echo $text_country; ?></td>
                                <td><?php echo $shipping_country; ?></td>
                            </tr>

                        </table>
                    </div>
                    <div class="tab-pane" id="tab-product">
                        <legend><?php echo $tab_product; ?></legend>

                        <table class="table table-responsive">
                            <thead>
                                <tr>
                                    <td class="left"><?php echo $column_product; ?></td>
                                    <td class="right"><?php echo $column_quantity; ?></td>
                                    <td class="right"><?php echo $column_price; ?></td>
                                    <td class="right"><?php echo $column_total; ?></td>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($products as $product) { ?>
                                    <tr>
                                        <td class="left"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a>
                                            <br />&nbsp;<small> - <?php echo $text_option; ?> : <?php echo $product['option']['title']; ?></small>
                                            <br />&nbsp;<small> - <?php echo $text_delivery; ?> : <?php if ($product['shipping']): ?><?php echo $product['shipping']['title']; ?> <?php else: ?>  
                                                    <?php if ($product['is_coupon']): ?>
                                                        <?php echo $text_coupon; ?>
                                                    <?php else: ?>
                                                        <?php echo $text_collect; ?>
                                                    <?php endif; ?>
                                                <?php endif; ?></small>

                                        </td>
                                        <td class="right"><?php echo $product['quantity']; ?></td>
                                        <td class="right"><?php echo $product['price']; ?></td>
                                        <td class="right"><?php echo $product['total']; ?></td>
                                    </tr>
                                <?php } ?>
                                <?php foreach ($vouchers as $voucher) { ?>
                                    <tr>
                                        <td class="left"><a href="<?php echo $voucher['href']; ?>"><?php echo $voucher['description']; ?></a></td>

                                        <td class="right">1</td>
                                        <td class="right"><?php echo $voucher['amount']; ?></td>
                                        <td class="right"><?php echo $voucher['amount']; ?></td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                            <?php foreach ($totals as $totals) { ?>
                                <tbody id="totals">
                                    <tr>
                                        <td colspan="3" class="right"><?php echo $totals['title']; ?>:</td>
                                        <td class="right"><?php echo $totals['text']; ?></td>
                                    </tr>
                                </tbody>
                            <?php } ?>
                        </table>
                    </div>
                    <div class="tab-pane" id="tab-history">
                        <legend><?php echo $tab_history; ?></legend>
                        <div class="well well-sm">
                        <div id="history"></div>
                        </div>
                        <table class="table table-responsive">
                            <tr>
                                <td><?php echo $entry_order_status; ?></td>
                                <td>
                                    <input type="hidden" name="old_order_status_id" value="<?php echo $order_status_id; ?>" id="old_order_status_id" />
                                    <select name="order_status_id" class="form-control">
                                        <?php foreach ($order_statuses as $order_statuses) { ?>
                                            <?php if ($order_statuses['order_status_id'] == $order_status_id) { ?>
                                                <option value="<?php echo $order_statuses['order_status_id']; ?>" selected="selected"><?php echo $order_statuses['name']; ?></option>
                                            <?php } else { ?>
                                                <option value="<?php echo $order_statuses['order_status_id']; ?>"><?php echo $order_statuses['name']; ?></option>
                                            <?php } ?>
                                        <?php } ?>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td><?php echo $entry_notify; ?></td>
                                <td><input type="checkbox" name="notify" value="1" /></td>
                            </tr>
                            <tr>
                                <td><?php echo $entry_comment; ?></td>
                                <td><textarea name="comment" cols="40" rows="8" style="width: 99%"></textarea>
                                    <div style="margin-top: 10px; text-align: right;"><a id="button-history" class="btn btn-primary"><?php echo $button_add_history; ?></a></div></td>
                            </tr>
                        </table>
                    </div>
                    <div class="tab-pane" id="tab-fraud">
                        <legend><?php echo $tab_fraud; ?></legend>
                        <table class="table table-responsive">
                            <?php if ($country_match) { ?>
                                <tr>
                                    <td><?php echo $text_country_match; ?></td>
                                    <td><?php echo $country_match; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($country_code) { ?>
                                <tr>
                                    <td><?php echo $text_country_code; ?></td>
                                    <td><?php echo $country_code; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($high_risk_country) { ?>
                                <tr>
                                    <td><?php echo $text_high_risk_country; ?></td>
                                    <td><?php echo $high_risk_country; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($distance) { ?>
                                <tr>
                                    <td><?php echo $text_distance; ?></td>
                                    <td><?php echo $distance; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_region) { ?>
                                <tr>
                                    <td><?php echo $text_ip_region; ?></td>
                                    <td><?php echo $ip_region; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_city) { ?>
                                <tr>
                                    <td><?php echo $text_ip_city; ?></td>
                                    <td><?php echo $ip_city; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_latitude) { ?>
                                <tr>
                                    <td><?php echo $text_ip_latitude; ?></td>
                                    <td><?php echo $ip_latitude; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_longitude) { ?>
                                <tr>
                                    <td><?php echo $text_ip_longitude; ?></td>
                                    <td><?php echo $ip_longitude; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_isp) { ?>
                                <tr>
                                    <td><?php echo $text_ip_isp; ?></td>
                                    <td><?php echo $ip_isp; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_org) { ?>
                                <tr>
                                    <td><?php echo $text_ip_org; ?></td>
                                    <td><?php echo $ip_org; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_asnum) { ?>
                                <tr>
                                    <td><?php echo $text_ip_asnum; ?></td>
                                    <td><?php echo $ip_asnum; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_user_type) { ?>
                                <tr>
                                    <td><?php echo $text_ip_user_type; ?></td>
                                    <td><?php echo $ip_user_type; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_country_confidence) { ?>
                                <tr>
                                    <td><?php echo $text_ip_country_confidence; ?></td>
                                    <td><?php echo $ip_country_confidence; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_region_confidence) { ?>
                                <tr>
                                    <td><?php echo $text_ip_region_confidence; ?></td>
                                    <td><?php echo $ip_region_confidence; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_city_confidence) { ?>
                                <tr>
                                    <td><?php echo $text_ip_city_confidence; ?></td>
                                    <td><?php echo $ip_city_confidence; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_postal_confidence) { ?>
                                <tr>
                                    <td><?php echo $text_ip_postal_confidence; ?></td>
                                    <td><?php echo $ip_postal_confidence; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_postal_code) { ?>
                                <tr>
                                    <td><?php echo $text_ip_postal_code; ?></td>
                                    <td><?php echo $ip_postal_code; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_accuracy_radius) { ?>
                                <tr>
                                    <td><?php echo $text_ip_accuracy_radius; ?></td>
                                    <td><?php echo $ip_accuracy_radius; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_net_speed_cell) { ?>
                                <tr>
                                    <td><?php echo $text_ip_net_speed_cell; ?></td>
                                    <td><?php echo $ip_net_speed_cell; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_metro_code) { ?>
                                <tr>
                                    <td><?php echo $text_ip_metro_code; ?></td>
                                    <td><?php echo $ip_metro_code; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_area_code) { ?>
                                <tr>
                                    <td><?php echo $text_ip_area_code; ?></td>
                                    <td><?php echo $ip_area_code; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_time_zone) { ?>
                                <tr>
                                    <td><?php echo $text_ip_time_zone; ?></td>
                                    <td><?php echo $ip_time_zone; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_region_name) { ?>
                                <tr>
                                    <td><?php echo $text_ip_region_name; ?></td>
                                    <td><?php echo $ip_region_name; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_domain) { ?>
                                <tr>
                                    <td><?php echo $text_ip_domain; ?></td>
                                    <td><?php echo $ip_domain; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_country_name) { ?>
                                <tr>
                                    <td><?php echo $text_ip_country_name; ?></td>
                                    <td><?php echo $ip_country_name; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_continent_code) { ?>
                                <tr>
                                    <td><?php echo $text_ip_continent_code; ?></td>
                                    <td><?php echo $ip_continent_code; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ip_corporate_proxy) { ?>
                                <tr>
                                    <td><?php echo $text_ip_corporate_proxy; ?></td>
                                    <td><?php echo $ip_corporate_proxy; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($anonymous_proxy) { ?>
                                <tr>
                                    <td><?php echo $text_anonymous_proxy; ?></td>
                                    <td><?php echo $anonymous_proxy; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($proxy_score) { ?>
                                <tr>
                                    <td><?php echo $text_proxy_score; ?></td>
                                    <td><?php echo $proxy_score; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($is_trans_proxy) { ?>
                                <tr>
                                    <td><?php echo $text_is_trans_proxy; ?></td>
                                    <td><?php echo $is_trans_proxy; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($free_mail) { ?>
                                <tr>
                                    <td><?php echo $text_free_mail; ?></td>
                                    <td><?php echo $free_mail; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($carder_email) { ?>
                                <tr>
                                    <td><?php echo $text_carder_email; ?></td>
                                    <td><?php echo $carder_email; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($high_risk_username) { ?>
                                <tr>
                                    <td><?php echo $text_high_risk_username; ?></td>
                                    <td><?php echo $high_risk_username; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($high_risk_password) { ?>
                                <tr>
                                    <td><?php echo $text_high_risk_password; ?></td>
                                    <td><?php echo $high_risk_password; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($bin_match) { ?>
                                <tr>
                                    <td><?php echo $text_bin_match; ?></td>
                                    <td><?php echo $bin_match; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($bin_country) { ?>
                                <tr>
                                    <td><?php echo $text_bin_country; ?></td>
                                    <td><?php echo $bin_country; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($bin_name_match) { ?>
                                <tr>
                                    <td><?php echo $text_bin_name_match; ?></td>
                                    <td><?php echo $bin_name_match; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($bin_name) { ?>
                                <tr>
                                    <td><?php echo $text_bin_name; ?></td>
                                    <td><?php echo $bin_name; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($bin_phone_match) { ?>
                                <tr>
                                    <td><?php echo $text_bin_phone_match; ?></td>
                                    <td><?php echo $bin_phone_match; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($bin_phone) { ?>
                                <tr>
                                    <td><?php echo $text_bin_phone; ?></td>
                                    <td><?php echo $bin_phone; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($customer_phone_in_billing_location) { ?>
                                <tr>
                                    <td><?php echo $text_customer_phone_in_billing_location; ?></td>
                                    <td><?php echo $customer_phone_in_billing_location; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ship_forward) { ?>
                                <tr>
                                    <td><?php echo $text_ship_forward; ?></td>
                                    <td><?php echo $ship_forward; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($city_postal_match) { ?>
                                <tr>
                                    <td><?php echo $text_city_postal_match; ?></td>
                                    <td><?php echo $city_postal_match; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($ship_city_postal_match) { ?>
                                <tr>
                                    <td><?php echo $text_ship_city_postal_match; ?></td>
                                    <td><?php echo $ship_city_postal_match; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($score) { ?>
                                <tr>
                                    <td><?php echo $text_score; ?></td>
                                    <td><?php echo $score; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($explanation) { ?>
                                <tr>
                                    <td><?php echo $text_explanation; ?></td>
                                    <td><?php echo $explanation; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($risk_score) { ?>
                                <tr>
                                    <td><?php echo $text_risk_score; ?></td>
                                    <td><?php echo $risk_score; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($queries_remaining) { ?>
                                <tr>
                                    <td><?php echo $text_queries_remaining; ?></td>
                                    <td><?php echo $queries_remaining; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($maxmind_id) { ?>
                                <tr>
                                    <td><?php echo $text_maxmind_id; ?></td>
                                    <td><?php echo $maxmind_id; ?></td>
                                </tr>
                            <?php } ?>
                            <?php if ($error) { ?>
                                <tr>
                                    <td><?php echo $text_error; ?></td>
                                    <td><?php echo $error; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer">
        </div>
    </div>

</section><!-- /.content -->

<script type="text/javascript"><!--


    addOnready(function() {

        $('#history').load('index.php?route=sale/order/history&token=<?php echo $token; ?>&order_id=<?php echo $order_id; ?>');

        $('#invoice-generate').on('click', function() {
            $.ajax({
                url: 'index.php?route=sale/order/createinvoiceno&token=<?php echo $token; ?>&order_id=<?php echo $order_id; ?>',
                dataType: 'json',
                beforeSend: function() {
                    $('#invoice').after('<img src="view/image/loading.gif" class="loading" style="padding-left: 5px;" />');
                },
                complete: function() {
                    $('.loading').remove();
                },
                success: function(json) {
                    $('.alert-success, .alert-danger').remove();

                    if (json['error']) {
                        $('#tab-order').prepend('<div class="alert alert-danger" style="display: none;">' + json['error'] + '</div>');

                        $('.warning').fadeIn('slow');
                    }

                    if (json.invoice_no) {
                        $('#invoice').fadeOut('slow', function() {
                            $('#invoice').html(json['invoice_no']);

                            $('#invoice').fadeIn('slow');
                        });
                    }
                }
            });
        });

        $('#history .pagination a').on('click', function() {
            $('#history').load(this.href);
            return false;
        });

        $('#button-history').on('click', function() {
            $.ajax({
                url: 'index.php?route=sale/order/history&token=<?php echo $token; ?>&order_id=<?php echo $order_id; ?>',
                type: 'post',
                dataType: 'html',
                data: 'order_status_id=' + encodeURIComponent($('select[name=\'order_status_id\']').val()) + '&notify=' + encodeURIComponent($('input[name=\'notify\']').attr('checked') ? 1 : 0) + '&append=' + encodeURIComponent($('input[name=\'append\']').attr('checked') ? 1 : 0) + '&comment=' + encodeURIComponent($('textarea[name=\'comment\']').val()),
                beforeSend: function() {
                    $('.success, .warning').remove();
                    $('#button-history').attr('disabled', true);
                    $('#history').prepend('<div class="attention"><img src="view/image/loading.gif" alt="" /> <?php echo $text_wait; ?></div>');
                },
                complete: function() {
                    $('#button-history').attr('disabled', false);
                    $('.attention').remove();
                },
                success: function(html) {
                    $('#history').html(html);

                    $('textarea[name=\'comment\']').val('');

                    $('#order-status').html($('select[name=\'order_status_id\'] option:selected').text());
                }
            });
        });
    });
    -->
</script>

<?php echo $footer; ?>