<?php echo $header; ?>
<div class="page_container">
    <?php echo $column_left; ?>
    <?php echo $column_right; ?>
    <div id="content">
        <ol class="breadcrumb">
            <?php $i = 0; ?>
            <?php foreach ($breadcrumbs as $i => $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo ($i == 0) ? '<i class="fa fa-dashboard"></i> ' : ''; ?><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ol>
        <?php echo $content_top; ?>

        <h1><?php echo $heading_title; ?></h1>
         <div class="well well-sm filter-well">
            <div class="clearfix">
                <div class="limit pull-right col-lg-2 col-md-3 col-sm-4 col-xs-6">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default" tabindex="-1"><?php echo $text_limit; ?></button>
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><?php echo $limit; ?> <span class="caret"></span></button>
                        <ul class="dropdown-menu pull-right">
                            <?php foreach ($limits as $limits) { ?>
                                <li>
                                    <?php if ($limits['value'] == $limit) { ?>
                                        <a><em><?php echo $limits['text']; ?></em></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $limits['href']; ?>"><?php echo $limits['text']; ?></a>
                                    <?php } ?>
                                <?php } ?>
                            </li>
                        </ul>
                    </div>
                </div>
                
                <div class="limit pull-right col-lg-3 col-md-4 col-sm-5 col-xs-6">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default" tabindex="-1"><?php echo $text_sort; ?></button>
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><?php echo $sorts[$sort . '-' . $order]['text']; ?> <span class="caret"></span></button>
                        <ul class="dropdown-menu pull-right">
                            <?php foreach ($sorts as $_sorts) { ?>
                                <li>
                                    <?php if ($_sorts['value'] == $sort . '-' . $order) { ?>
                                        <a><em><?php echo $_sorts['text']; ?></em></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $_sorts['href']; ?>"><?php echo $_sorts['text']; ?></a>
                                    <?php } ?>
                                <?php } ?>
                            </li>
                        </ul>
                    </div>
                </div>


               
            </div>

        </div>
        <?php if ($deals) : ?>
            <div class="deals-list row">
                <?php foreach ($deals as $deal): ?>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 deal-item">

                        <div class="panel panel-default">
                            <!-- Default panel contents -->
                            <div class="panel-heading"><h4 class="text-center nowrap"><i class="icon-fullscreen"></i> <a href="<?php echo $deal['url']; ?>" ><?php echo $deal['title']; ?></a></h4></div>
                            <div class="panel-body nopad">
                                <div class="thumbnail nopad">
                                    <img src="<?php echo (($deal['image'])) ? $deal['image'] : $no_image; ?>" class="img-responsive" alt="">
                                </div>

                            </div>

                            <!-- List group -->
                            <ul class="list-group">
                                <li class="list-group-item"><?php echo $deal['introduction']; ?></li>
                                <li class="list-group-item "><span class="wasprice"><?php echo $this->currency->format($deal['market_price']); ?></span> <span class="nowprice"><?php echo $this->currency->format($deal['deal_price']); ?></span></li>

                                <li class="list-group-item">

                                    <?php if ($deal['state'] == ModelDealDeal::DEAL_AVAILABLE): ?>
                                        <div class="countdown_block">
                                            <div id="deal_countdown_<?php echo $deal['deal_id']; ?>" class="hasCountdown" data-time="<?php echo $deal['time_diff']; ?>"></div>
                                            <script type="text/javascript">
                                                addOnready(function()
                                                {
                                                    $('#deal_countdown_<?php echo $deal['deal_id']; ?>').countdown({
                                                        timezone: <?php echo ((date('Z') / 3600) > 0)? '+':''; echo (date('Z') / 3600);?>,
                                                        until: +<?php echo $deal['time_diff']; ?>

                                                    });
                                                    $('#deal_countdown_<?php echo $deal['deal_id']; ?>').countdown($.countdown.regionalOptions['<?php echo $this->language->get('code'); ?>']);
                                                });</script>
                                        </div>
                                    <?php else: ?>
                                        <div class="alert alert-danger"><?php echo $this->language->get("deal_state_" . (int) $deal['state']); ?></div>
                                    <?php endif; ?>

                                </li>
                                <li class="list-group-item"><a class="btn btn-success btn-block" href="<?php echo $deal['url']; ?>">View Deal</a></li>
                            </ul>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>


            <div class="pagination-container row">
                <?php echo $pagination; ?>
            </div>
        <?php else: ?>
            <div class="alert alert-info">
                <?php echo $text_no_results; ?>
            </div>
        <?php endif; ?>
        <?php echo $content_bottom; ?></div>
</div>
<script>
    addOnready(function()
    {
        $.getScript('/public/view/theme/default/javascript/isotope.pkgd.min.js', function() {
            $('.deals-list').isotope({
                
                itemSelector: '.deal-item'
            });
        });
    });
</script>
<?php echo $footer; ?>
