</div> <!-- //wrapper -->

<footer>
    <div class="container">
        <div class="row">
            <?php if ($informations) : ?>
                <div class="col-md-4">
                    <h4 class="line3 center standart-h4title"><span><?php echo $text_information; ?></span></h4>
                    <ul class="footer-links">
                        <?php foreach ($informations as $information) { ?>
                            <li><a href="<?php echo $information['href']; ?>"><?php echo $information['title']; ?></a></li>
                        <?php } ?>
                    </ul>
                </div>
            <?php endif; ?>

            <div class="col-md-4">
                <h4 class="line3 center standart-h4title"><span><?php echo $text_service; ?></span></h4>
                <ul class="footer-links">
                    <li><a href="<?php echo $contact; ?>"><?php echo $text_contact; ?></a></li>
                    <li><a href="<?php echo $sitemap; ?>"><?php echo $text_sitemap; ?></a></li>
                </ul>
            </div>



            <div class="col-md-4">
                <h4 class="line3 center standart-h4title"><span><?php echo $text_account; ?></span></h4>
                <ul class="footer-links">
                    <li><a href="<?php echo $account; ?>"><?php echo $text_account; ?></a></li>
                    <li><a href="<?php echo $order; ?>"><?php echo $text_order; ?></a></li>
                    <li><a href="<?php echo $newsletter; ?>"><?php echo $text_newsletter; ?></a></li>
                </ul>
            </div>


            </footer>

            <!--
       OpenDeal is open source software and you are free to remove the powered by OpenDeal if you want, but its generally accepted practice to make a small donation.
       Please donate via PayPal to vxdhost@gmail.com
       //-->
            <div id="powered"><?php echo $powered; ?></div>


            <script type="text/javascript" src="public/view/javascript/jquery.js"></script>
            <script type="text/javascript" src="public/view/javascript/bootstrap.min.js"></script>
            <!-- PAGE CUSTOM SCROLLER -->
            <script type="text/javascript" src="public/view/theme/default/javascript/jquery.nicescroll.min.js"></script>
            <script src="public/view/theme/default/javascript/jquery.parallax-1.1.3.js" type="text/javascript" ></script>
            <script src="public/view/theme/default/javascript/jquery.localscroll-1.2.7-min.js" type="text/javascript" ></script>
            <script src="public/view/theme/default/javascript/jquery.scrollTo-1.4.2-min.js" type="text/javascript" ></script>


            <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=true"></script>
            <script src="http://maps.gstatic.com/intl/en_us/mapfiles/api-3/16/4/main.js" type="text/javascript"></script>

            <script type="text/javascript" src="public/view/javascript/common.js"></script>
            <script type="text/javascript" src="public/view/theme/default/javascript/theme.js"></script>
            <?php foreach ($scripts as $script) { ?>
                <script type="text/javascript" src="<?php echo $script; ?>"></script>
            <?php } ?>


            <script type="text/javascript"><!--
            $(document).ready(function() {
<?php if ($stores) { ?>
    <?php foreach ($stores as $store) { ?>
                            $('body').prepend('<iframe src="<?php echo $store; ?>" style="display: none;"></iframe>');
    <?php } ?>
<?php } ?>

                    $.each(onReadyCallbacks, function(i, callback) {
                        if (callback instanceof Function) {
                            callback();
                        }
                    });
                });
//--></script>

            <?php echo $google_analytics; ?>

 <div class="modal fade" id="city_popup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel"><?php echo $this->language->get("heading_select_region"); ?></h4>
                        </div>
                        <div class="modal-body">
                            <p><?php echo $text_select_region; ?></p>     
                            <form action="<?php echo $home;?>" class="form-horizontal form-validate" role="form" id="city_modal_form" method="GET">
                                
                                <div class="form-group">
                                    
                                    <div class="controls col-sm-10 col-sm-offset-1">
                                        <select name="city_id" id="city_change" class="form-control">
                                            <?php foreach ($cities as $city): ?>
                                                <option value="<?php echo $city['city_id']; ?>"><?php echo $city['city_name']; ?></option>
                                            <?php endforeach; ?>

                                        </select>
                                    </div>
                                </div>

                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->language->get("button_close"); ?></button>
                            <button type="button" class="btn btn-primary" onclick="$('#city_modal_form').submit();"><?php echo $this->language->get("button_select_region"); ?></button>
                        </div>
                    </div>
                </div>
            </div>


            <div class="modal fade" id="landing_popup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel"><?php echo $this->language->get("heading_subscribe_region"); ?></h4>
                        </div>
                        <div class="modal-body">
                            <p><?php echo $text_subscribe; ?></p>     
                            <form action="<?php echo $action;?>" class="form-horizontal form-validate" role="form" id="newsletter_modal_form" method="POST">
                                <div class="form-group">
                                    <label class="control-label required col-sm-3" for="modalEmailInput"><?php echo $text_email; ?></label>
                                    <div class="controls col-sm-9 ">
                                        <input name="odcitysubscribe" id="modalEmailInput" class="form-control required" type="email" value="<?php echo $email_address; ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-3" for="subscription_location"><?php echo $text_location; ?></label>
                                    <div class="controls col-sm-9 ">
                                        <select name="odcity" id="landing_odcity" class="form-control">
                                            <?php foreach ($cities as $city): ?>
                                                <option value="<?php echo $city['city_id']; ?>"><?php echo $city['city_name']; ?></option>
                                            <?php endforeach; ?>

                                        </select>
                                    </div>
                                </div>

                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->language->get("button_close"); ?></button>
                            <button type="button" class="btn btn-primary" onclick="$('#newsletter_modal_form').submit();"><?php echo $this->language->get("button_ok"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
            <?php if ($showWelcome): ?>
                <script>
                    $(document).ready(function() {
                        $('#landing_popup').modal();
                    });
                </script>
            <?php endif; ?>

            </body></html>