<!DOCTYPE html>
<html dir="<?php echo $direction; ?>" lang="<?php echo $lang; ?>">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title><?php echo $title; ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="author" content="Craig G Smith - OmniHostNZ">
        <base href="<?php echo $base; ?>" />
        <?php if ($description) { ?>
            <meta name="description" content="<?php echo $description; ?>" />
        <?php } ?>
        <?php if ($keywords) { ?>
            <meta name="keywords" content="<?php echo $keywords; ?>" />
        <?php } ?>
        <?php if ($icon) { ?>
            <link href="<?php echo $icon; ?>" rel="icon" />
        <?php } ?>
        <?php foreach ($links as $link) { ?>
            <link href="<?php echo $link['href']; ?>" rel="<?php echo $link['rel']; ?>" />
        <?php } ?>

        <!-- Le styles -->
        <link rel="stylesheet" type="text/css" href="public/view/theme/default/stylesheet/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="public/view/theme/default/stylesheet/theme.css" />
        <link rel="stylesheet" type="text/css" href="public/view/theme/default/stylesheet/font-awesome.min.css" />


        <!--[if lt IE 7]>
                <link href="assets/css/font-awesome-ie7.min.css" rel="stylesheet">
                <![endif]-->
        <!-- Fav and touch icons -->


        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
              <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
            <![endif]-->
        <!-- Le fav and touch icons -->
        <?php foreach ($styles as $style) { ?>
            <link rel="<?php echo $style['rel']; ?>" type="text/css" href="<?php echo $style['href']; ?>" media="<?php echo $style['media']; ?>" />
        <?php } ?>

        <?php echo implode("\n", $meta); ?>



        <script type="text/javascript">
            /** Hack to make sure that inline code can reference $.ready style functionality **/
            var onReadyCallbacks = [];
            var addOnready = function(callback) {
                onReadyCallbacks.push(callback);
            }

        </script>
    </head>
    <body>

        <!-- MAIN WRAPPER class="wrapper" max-width="1110px"-->
        <div class="wrapper">

            <header>

                <div id="header" class="clearfix">
                    <div class="col-md-3">
                        <?php if ($logo) { ?>
                            <div id="logo"><a href="<?php echo $home; ?>"><img src="<?php echo $logo; ?>" title="<?php echo $name; ?>" alt="<?php echo $name; ?>" /></a></div>
                        <?php } ?>
                    </div>
                    <div class="col-md-6">
                        <h2 class="column"><?php echo $city_head; ?></h2>
                    </div>
                    <div class="col-md-3">
                        <a data-toggle="modal" href="#city_popup"><?php echo $change_city; ?></a> | <a href="<?php echo $newsletter; ?>"><?php echo $daily_arerts; ?></a>
                    </div>
                </div>

                <nav class="navbar navbar-inverse" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand visible-sm visible-xs" href="#">Navigation</a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse navbar-ex1-collapse">
                            <ul class="nav navbar-nav">
                                <li><a href="<?php echo $home; ?>"><?php echo $text_home; ?></a></li>
                                <li><a href="<?php echo $freepon; ?>"><?php echo $text_freepon; ?></a></li>
                                <li><a href="<?php echo $current_deals; ?>"><?php echo $text_all_deals; ?></a></li>
                                <li><a href="<?php echo $past_deals; ?>"><?php echo $text_past_deals; ?></a></li>
                                <li><a href="<?php echo $future_deals; ?>"><?php echo $text_future_deals; ?></a></li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <?php if (!$logged) : ?>
                                    <li ><a href="<?php echo $link_login; ?>"><?php echo $text_login; ?></a></li>
                                    <li><a href="<?php echo $link_register; ?>"><?php echo $text_register; ?></a></li>
                                <?php else: ?>
                                    <li><a><?php echo $text_logged; ?></a></li>
                                    <li class="hidden-lg"><a href="<?php echo $this->url->link('account/account'); ?>" class="dropdown-toggle" ><?php echo $text_account; ?></a></li>
                                    <li class="hidden-lg"><a href="<?php echo $this->url->link('account/logout'); ?>"><?php echo $text_logout; ?></a></li>
                                    <li class="dropdown visible-lg">

                                        <a href="#" class="dropdown-toggle " data-toggle="dropdown"><?php echo $text_account; ?> <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?php echo $this->url->link('account/account'); ?>"><?php echo $text_account; ?></a></li>
                                            <li><a href="<?php echo $this->url->link('account/edit'); ?>"><?php echo $text_edit_account; ?></a></li>
                                            <li><a href="<?php echo $this->url->link('account/password'); ?>"><?php echo $text_edit_password; ?></a></li>
                                            <li><a href="<?php echo $this->url->link('account/address'); ?>"><?php echo $text_address_book; ?></a></li>
                                            <li><a href="<?php echo $this->url->link('account/logout'); ?>"><?php echo $text_logout; ?></a></li>
                                        </ul>
                                    </li>
                                <?php endif; ?>
                            </ul>

                        </div>
                    </div><!-- /.navbar-collapse -->
                </nav>
            </header>



