<!DOCTYPE html>
<html dir="<?php echo $direction; ?>" lang="<?php echo $lang; ?>">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="author" content="Craig G Smith - OmniHostNZ">
        <?php if ($description) { ?>
            <meta name="description" content="<?php echo $description; ?>" />
        <?php } ?>
        <?php if ($keywords) { ?>
            <meta name="keywords" content="<?php echo $keywords; ?>" />
        <?php } ?>
        <?php if ($icon) { ?>
            <link href="<?php echo $icon; ?>" rel="icon" />
        <?php } ?>
        <?php foreach ($links as $link) { ?>
            <link href="<?php echo $link['href']; ?>" rel="<?php echo $link['rel']; ?>" />
        <?php } ?>

        <title><?php echo $title; ?></title>
        <base href="<?php echo $base; ?>" />

        <!-- Bootstrap -->
        <link href="public/view/theme/default/maintenance/css/bootstrap.css" rel="stylesheet">
        <link href="public/view/theme/default/maintenance/css/bootstrap-theme.css" rel="stylesheet">

        <!-- siimple style -->
        <link href="public/view/theme/default/maintenance/css/style.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <div id="wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                         <?php if ($logo) { ?>
                        <h1><div id="logo"><img src="<?php echo $logo; ?>" title="<?php echo $name; ?>" alt="<?php echo $name; ?>" /></div></h1>
                        <?php }else { ?>
                        <h1><?php echo $name; ?></h1>
                        <?php } ?>
                        <h2 class="subtitle"><?php echo $message; ?></h2>
                        <div id="countdown"></div>
                        <form class="form-inline signup" role="form">

                            <a href="http://rankedbyreview.co.nz" class="btn btn-theme ">Visit Ranked By Review!</a>
                        </form>		

                    </div>

                </div>		
            </div>
        </div>
        <script src="public/view/javascript/jquery.js"></script>
        <script src="public/view/theme/default/maintenance/js/bootstrap.min.js"></script>
        <script src="public/view/theme/default/maintenance/js/jquery.countdown.min.js"></script>
        <script type="text/javascript">
            $('#countdown').countdown('<?php echo $countdown_till; ?>', function(event) {
                $(this).html(event.strftime('<?php echo $countdown_format; ?>'));
            });
        </script>
    </body>
</html>
